### ISSUE TITLE
frescobaldi-3.0.0 problem on Linux some feedback 

### ISSUE THREAD

**Issue by bitwo** [wbsoft/frescobaldi#1012]
frescobaldi-3.0.0 problem on Linux
some feedback 

Version 16.04.3 LTS (Xenial Xerus) 64 bit 
MATE 1.12.1

I installed python-poppler-qt5-0.24.2 as described. 

Installing frescobaldi-3.0.0 as described tells me

Running python-poppler-qt5-0.24.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9pWhsk/python-poppler-qt5-0.24.2/egg-dist-tmp-7mjDMD
warning: no previously-included files found matching 'version.sip'
sip: QDomElement is undefined
error: Setup script exited with error: command '/usr/bin/sip' failed with exit status 1

I can start frescobaldi-3.0.0 from the subdirectory frescobaldi-3.0.0 with "python3 frescobaldi" 
but not with "python frescobaldi". 
I cannot start frescobaldi outside the subdirectory with "frescobaldi" 

bb@bb:~$ frescobaldi
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 4, in <module>
    __import__('pkg_resources').run_script('frescobaldi==2.20.0', u'frescobaldi')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-poppler-qt5' distribution was not found and is required by frescobaldi

and not with "python3 frescobaldi" eather
bb@bb:~$ python3 frescobaldi
python3: can't open file 'frescobaldi': [Errno 2] No such file or directory

**Comment by soundsfromsound** [comment]
Hello bitwo,

If running Frescobaldi from outside the directory fails, I suggest checking the path maybe...have you made sure to add the path so your system can run it from anywhere?
https://github.com/wbsoft/frescobaldi/wiki/Run-Frescobaldi-from-git

(i.e. 
export PYTHONPATH=/path/to/python-ly
export PATH=/path/to/frescobaldi:$PATH
)

That solved my issue, hope you get it working!

**Comment by uliska** [comment]
> I can start frescobaldi-3.0.0 from the subdirectory frescobaldi-3.0.0 with "python3 frescobaldi"
> but not with "python frescobaldi".

This is obvious as Frescobaldi 3 does not support Python2 anymore.

> I cannot start frescobaldi outside the subdirectory with "frescobaldi"

Hm, *how* did you install Frescobaldi?

What is the content of `/usr/local/bin/frescobaldi`? The error message is strange, pointing a) to Python2.7 and b) to Frescobaldi 2.20. It seems you have some leftovers from a previous installation (how was that done?).

> and not with "python3 frescobaldi" eather
> bb@bb:~$ python3 frescobaldi

For this to work Python must know where to look for Frescobaldi, something like 

```
python3 /path/to/frescobaldi/frescobaldi
```

or even

```
PYTHONPATH=$PYTHONPATH:/path/to/python-ly python3 /path/to/frescobaldi/frescobaldi
```

**Comment by bitwo** [comment]
Thanks for response.

Because I could not get running frescobaldi-3.0.0 without trouble I
installed frescobaldi-2.20.0. That runs withoutproblems. Maybe I have
overwritten somethingand my details to follow up are not actual for the
1st installation trial (offrescobaldi-3.0.0).


Am 22.09.2017 um 14:58 schrieb Urs Liska:
>
>     I can start frescobaldi-3.0.0 from the subdirectory
>     frescobaldi-3.0.0 with "python3 frescobaldi" but not with "python
>     frescobaldi".
>
> This is obvious as Frescobaldi 3 does not support Python2 anymore.
>
In the INSTALL document the start sequence without installation is
described as python3 frescobaldi. That is working. I would recommend top
mention EXPLICITLY that ONLY python3 is supported for dummies like me.
(I argued that already.)
>
>     I cannot start frescobaldi outside the subdirectory with "frescobaldi"
>
> Hm, /how/ did you install Frescobaldi?
>
With my installation I followed the INSTALL document.
sudo python3 setup.py install --prefix=/usr
As mentioned above I switched to version 2.20 because I could not get
running 3.0.0. It did not start with "frecobaldi" from terminal.
>
> What is the content of |/usr/local/bin/frescobaldi|?
>
#!/usr/bin/python
# EASY-INSTALL-SCRIPT: 'frescobaldi==2.20.0',u'frescobaldi'
__requires__ = 'frescobaldi==2.20.0'
__import__('pkg_resources').run_script('frescobaldi==2.20.0',
u'frescobaldi')

I actually tried
    sudo python3 setup.py install
from subdir frescobaldi-3.0.0 and the content did not change!
>
> The error message is strange, pointing a) to Python2.7 and b) to
> Frescobaldi 2.20. It seems you have some leftovers from a previous
> installation (how was that done?).
>
>     and not with "python3 frescobaldi" eather bb@bb:~$ python3 frescobaldi
>
bb@bb~ $ python3 frescobaldi
python3: can't open file 'frescobaldi': [Errno 2] No such file or directory

> For this to work Python must know where to look for Frescobaldi,
> something like
>
> |python3 /path/to/frescobaldi/frescobaldi |
>
> or even
>
> |PYTHONPATH=$PYTHONPATH:/path/to/python-ly python3
> /path/to/frescobaldi/frescobaldi|
|BTW all that was not the only problem. I had to update Qt5 and to
update to python-poppler-qt5-0.24.2 as well.

May be I forgot to mention that I get the message  with the core content: |
|

Das Paket python-ly ist nicht verfügbar oder zu alt.

Frescobaldi benötigt mindestens Version 0.9.4.

BUT:

bb@bb~ $ ly -v ly 0.9.5 bb@bb~ $

so I arrived the point ro argue that there mustz be something wrong with
the installation code.

I actually work with 2.20.0 and do not change over to 3.0.0 as long as
this is not made clear.

Thank you anyway!

Regards BB

|
