### ISSUE TITLE
cannot run, cannot install

### ISSUE THREAD

**Issue by bitwo** [wbsoft/frescobaldi#1019]
this worked in the last trial:
bb@bb ~/frescobaldi-3.0.0 $ ./frescobaldi
Traceback (most recent call last):
  File "./frescobaldi", line 7, in <module>
    import main
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/main.py", line 33, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
ImportError: No module named PyQt5.QtCore
bb@bb ~/frescobaldi-3.0.0 $
rying to start frescobaldi:
bb@bb ~/frescobaldi-3.0.0 $ python3 frescobaldi
get the message ... python-ly not available or to old ... and so on
BUT:
bb@bb ~ $ ly -v
ly 0.9.5
bb@bb ~ $
I do not have an old version of python-ly on the system.  

Regards bitwo

**Comment by uliska** [comment]
I'm not fully sure what your log actually means, I can't really see what you did. I see three times the command prompt but don't understand what the second does. So the following is some guesswork:

When you run `python3 frescobaldi` and get a complaint about missing python-ly there are two possible reasons:
1. You do have the correct python-ly but Frescobaldi doesn't know how to find it (probable cause)
2. There is an old version of python-ly *within* your Frescobaldi directory (this is only thinkable if you have Frescobaldi running from Git and have done so for quite some time)

If you have python-ly present in a separate directory Frescobaldi has to know about it, and this is done through the `PYTHONPATH` environment variable. So you either have to make sure the shell from which you start Python3 has this variable set or you pass it directly to the command.

I have a Frescobaldi starter file in `~/bin` containing 

```
PYTHONPATH=$PYTHONPATH:~/git/lilypond/python-ly python3 ~/git/lilypond/frescobaldi/frescobaldi $@
```
