### ISSUE TITLE
Import of MusicXML may lead to wrong lyrics

### ISSUE THREAD

**Issue by HansGeiser** [wbsoft/frescobaldi#1020]
Imported the file
[05 Santctus.xml.txt](https://github.com/wbsoft/frescobaldi/files/1410737/05.Santctus.xml.txt)
The result of the import is in 
[05 Santctus.ly.txt](https://github.com/wbsoft/frescobaldi/files/1410753/05.Santctus.ly.txt)
There were multiple failures in the text. See for example in measure 6 eg. line 131 of the imported/converted file:
PartPOneVoiceOneLyricsOne =  \lyricmode {
  Sanc -- "tus," Sanc -- "tus,"
  Sanc -- "tus," Do -- nus De -- us Sa -- "oth," De -- us Sa -- "oth,"
This should read as
PartPOneVoiceOneLyricsOne =  \lyricmode {
  Sanc -- "tus," Sanc -- "tus,"
  Sanc -- "tus," Do -- mi -- nus De -- us Sa -- ba -- "oth," De -- us Sa -- ba -- "oth,"
The XML should be ok, see measure 6 eq. lines 307 to 364.
See also 
[05 Santctus.pdf](https://github.com/wbsoft/frescobaldi/files/1410778/05.Santctus.pdf)

**Comment by uliska** [comment]
This is not a Frescobaldi issue but LilyPond. While Fresocbaldi implements MusicXML *export* itself (or rather in the python-ly library) the *import* is done by the `musicxml2ly` script shipping with LilyPond.

I did only check with the *current* version of LilyPond, and there this issue doesn't occur, the syllables are correct.

Obviously this bug has already been fixed, and I'm sure it will not be backported to 2.18. Instead I suggest you try out the current development version.

What *is* fishy with the imported code is that the barnumberchecks don't go well with the repeats, so there are lots of barcheck errors. And I noticed that the tempo was converted to a floating point number ...
