### ISSUE TITLE
'Could not load the popplerqt5 module'

### ISSUE THREAD

**Issue by remylindsay** [wbsoft/frescobaldi#1052]
I have a fresh install of Frescobaldi on Windows 10. Inside the right tab, an error is displayed saying 'Could not load the popplerqt5 module'. The link is directed [here](https://github.com/wbsoft/python-poppler-qt4), which ironically is the python-poppler-qt4 page. The instructions in the readme there are simply:

```
import popplerqt4
d = popplerqt4.Poppler.Document.load('file.pdf')
```

whatever that means. On the Frescobaldi website, there's a link that goes [here](http://www.qt-project.org/), which is a massive download, even though the much smaller Frescobaldi installer is described where apparently "a full installer is provided, containing all components needed by Frescobaldi". I'm utterly confused, what is qt4 or qt5, and what am I supposed to download (even though I shouldn't need to)?

**Comment by Dapuva76** [comment]
Yeah I'm having the same issue.

**Comment by fedelibre** [comment]
@Dapuva76 Have you tried the **latest installer** for Windows? That is:

> Frescobaldi.Setup.3.0.0-2.exe (latest version of full Windows installer, includes a dll that fixes printing) 1bbc985a0c912c0715d23d3af1b8852344259249ce5281a88e146e20f9364aac

I've just made a fresh install on Windows 10 and everything works fine. (the first ly compilation may take a lot of time but it's a none issue)

Do you know that you **have to install LilyPond separately**, as it's not included in Frescobaldi, right?

**Comment by uliska** [comment]
But not being able to load the Poppler module (needed for the Music Preview) is not related to a LilyPond installation m
