### ISSUE TITLE
Using Sound Fonts

### ISSUE THREAD

**Issue by quinndaly** [wbsoft/frescobaldi#1054]
I love using Frescobaldi and Lilypond, but I don't like the way midi sounds with the out-of-the-box computer generated sounds. So, my suggestion is for a future version of Frescobaldi to have a sound-font loader for each instrument. I know it's a lot to ask.

Thanks for considering it.

Quinn

**Comment by fedelibre** [comment]
@quinndaly It's not Frescobaldi who is playing the midi files. You can change the soundfonts to be used in your MIDI synthesizer, which may be timidity or fluidsynth if you are using Linux.
You can find more information in the [wiki](https://github.com/wbsoft/frescobaldi/wiki).

@uliska I think this can be closed?
BTW, there are some open MIDI issues missing the midi label.

**Comment by quinndaly** [comment]
Thanks so much for the help. Let’s do consider it closed.

Quinn

**Comment by fedelibre** [comment]
@quinndaly  you can close it (using the browser)
