### ISSUE TITLE
Automatic engraving not working

### ISSUE THREAD

**Issue by MaartenDeen** [wbsoft/frescobaldi#1059]
I have Frescobaldi on my Ubuntu computer, older version, 2.0.13, and that works fine. Now I installed 3.0.1 on my windows computer and it will not do automatic engraving. I have the option automatic engrave checked, but no matter what I type, it is not engraving.
When I do it manually it will engrave.

Why is that?

**Comment by fedelibre** [comment]
I'm using Frescobaldi 3 from master (commit 77e2c0de374e9c91a9063e9b752c57ce5246b95c) and everything works fine.

Please provide more information:

- have you tried with a minimal example/a small file?
- how did you install Frescobaldi 3? From Ubuntu repository? (BTW, Frescobaldi 3.0.1 has not been released yet)

**Comment by evanwill** [comment]
Have you installed [Lilypond](http://lilypond.org/website/download.html)? 

This confused me coming from Linux to Windows as well--Frescobaldi for Windows does not come bundled with Lilypond. You need to install both (unlike linux where the dependencies are automatically tracked down and installed).

**Comment by MaartenDeen** [comment]
I have tried again now and it works as expected. No idea what I was doing wrong last time, I was using the same file on both systems.
And yes, I have lilypond installed, it did engrave manually, it would not do that if there was no lilypond available.
