### ISSUE TITLE
log fontsize change has no visible effect

### ISSUE THREAD

**Issue by mmeyn** [wbsoft/frescobaldi#1066]
The log font and fontsize can be changed at Edit→Preferences→Tools. These settings can be found in the file `frescobaldi.conf`:

```
[log]
fontfamily=Inconsolata
fontsize=16
```

But the fontsize setting seems to have no effect.

**Comment by JoanEliot** [comment]
On Windows the current binary offered for download does not have the change made in commit #1115 (the .exe filename is Frescobaldi Setup.3.0.0-2 and its referred to as 3.0.0-2 on the web site , but the About dialog calls it version 3.01). I can confirm that un-sticking the log font size requires only that you comment out line #124 in log.py:
 `output.setProperty(QTextFormat.FontSizeAdjustment, 0)`
. But that change doesn't seem to have made it into the Windows binary.
