### ISSUE TITLE
Snippets and templates menus not working on Mac

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#1073]
Snippets and templates work as expected if inserted via the snippet manager or keyboard shortcuts but not if inserted via the menu entries (see also #986).
Apparently [`slotTriggered`](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/snippet/menu.py#L97) is never called.
I tried to look into this but couldn't solve it.

@wbsoft Any ideas?
This issue has become critical since MacPorts ceased support for poppler-qt4, so I want to complete the switch to Qt 5 soon.

**Comment by dliessi** [comment]
@uliska @fedelibre @PeterBjuhr Any ideas about this?

**Comment by fedelibre** [comment]
I can only say that snippets menu work in Linux.
Which versions are you running? Here's mine:

```
Frescobaldi: 3.0.0
Python: 3.6.6
python-ly: 0.9.5
Qt: 5.10.1
PyQt: 5.10
sip: 4.19.7
poppler: 0.61.1
python-poppler-qt: 0.24.1
OS: Linux-4.17.9-200.fc28.x86_64-x86_64-with-fedora-28-Twenty_Eight
```
I won't have access to a Mac until September.

**Comment by dliessi** [comment]
```
Frescobaldi: 3.0.0
Python: 3.6.6
python-ly: 0.9.5
Qt: 5.10.1
PyQt: 5.10.1
sip: 4.19.12
poppler: 0.66.0
python-poppler-qt: 0.24.2
OS: Darwin-15.6.0-x86_64-i386-64bit
installation kind: command line
```

**Comment by dliessi** [comment]
Might it be a bug in the `triggered` signal of `QMenu`? Is it plausible that such a bug passed under the radar and is still present in Qt 5.10?

**Comment by marnen** [comment]
Would the Qt folks have any insight on that?

**Comment by uliska** [comment]
@dliessi what exactly is not working: Am I getting it right that the menu entries are correctly built (you can see the menu and click on entries) but clicking doesn't have any effect? What about snippets that trigger a dialog, such as "Document Fonts" (still there on master) or "Manage Snippets"?

**Comment by dliessi** [comment]
I finally decided to start from the whole Frescobaldi and reduce it to a minimal example.

```
from PyQt5.QtCore import (Qt)
from PyQt5.QtWidgets import (QAction, QApplication, QMainWindow, QMenu)

qApp = QApplication([])
win = QMainWindow()
menu = QMenu()
menu.setTitle('Menu')
menu.triggered.connect(lambda: print('menu.triggered'))
win.menuBar().addMenu(menu)
win.show()

action1 = QAction(win)
action1.setText('Action 1')
action1.triggered.connect(lambda: print('action1.triggered'))
menu.addAction(action1)

action2 = QAction(win)
action2.setText('Action 2')
#menu.addAction(action2)
menu.aboutToShow.connect(lambda: menu.addAction(action2))
menu.aboutToHide.connect(lambda: menu.removeAction(action2), Qt.QueuedConnection)

qApp.exec_()
```

`action2` should print `menu.triggered`, but it does not.
Uncommenting the commented line (`menu.addAction(action2)`) and commenting the following two lines (`menu.aboutTo...`), `action2` prints the message.

**Comment by dliessi** [comment]
> Am I getting it right that the menu entries are correctly built (you can see the menu and click on entries) but clicking doesn't have any effect?

Yes.

> What about snippets that trigger a dialog, such as "Document Fonts" (still there on master) or "Manage Snippets"?

They work as expected.

I think the problem is in how the entries are added to the menu (see the example above).

**Comment by uliska** [comment]
In your example there is a

```python
action2.triggered.connect(lambda: print('action2.triggered'))
```
missing in the "action2" block. When I add that the printout is correct regardless of the way the action is added.
Could you please verify this?

**Comment by dliessi** [comment]
On my machine, even adding that line, prints related to `action2` appear only with the `menu.addAction(action2)` line.

To understand the example, have a look at `frescobaldi_app/snippets/menu.py` to see how snippets are added to the menu.
You'll notice that the actions of the single snippets rely on the signal sent by the parent menu, instead of a signal for each individual snippet.
Also, snippets are added to the menu via the `aboutTo...` signals.

In my example, `action1` correspond to a "normal" menu entry and `action2` to how snippets are dealt with in Frescobaldi.

**Comment by uliska** [comment]
OK, I now see what you mean - the example wasn't really obvious, I didn't notice that you are explicitly interested in the *menu*'s `triggered` signal.

I can confirm that your minimal example behaves correctly on my System
```
Frescobaldi: 3.0.0
Python: 3.6.6
python-ly: 0.9.4
Qt: 5.10.1
PyQt: 5.11.2
sip: 4.19.12
poppler: 0.63.0
python-poppler-qt: 0.24.2
OS: Linux-4.16.0-2-amd64-x86_64-with-debian-buster-sid
```

I think this makes it clear that the problem is not related to any specific code in Frescobaldi but that `QMenu.aboutToSow` seems to behave differently on Mac than on Linux (no idea about Windows). I have no idea if that should be called a programming error in Frescobaldi or a bug in Qt, although nothing in the Qt documentation indicates that you shouldn't add actions within that slot.

From the mininal example we can also infer that
* `aboutToShow` *is* and the action added to the menu called because otherwise the menu item wouldn't appear
* The action is added to the menu but clicking doesn't cause the *menu*'s `triggered` signal to be emitted.

I will post that question on StackOverflow.

**Comment by uliska** [comment]
One more remark and a question:
* If that interpretation is correct it is clear that it is also the cause for #1086, and a fix to either will also fix the other.
* Am I right to understand that the issue wasn't present in Python2/PyQt4?

**Comment by dliessi** [comment]
I think that the StackOverflow issue you posted in #1086 might indeed help in both issues.
And yes, the issue was not present in Py2/PyQt4.

I think that adding the action directly to the single snippets is an acceptable workaround.
I'll work on that (and test your fix for #1086) later.
Anyway, I would consider this a bug in Qt, since the documentation explicitly says (I read it yesterday, but now I cannot find it) that menu entries trigger the action associated to the menu.

**Comment by dliessi** [comment]
I think that the problem is in the `aboutToHide` part rather than in the `aboutToShow`, since commenting the `aboutToHide` line everything seems to work as expected.
However I think that the rationale behind recreating all snippets in the menu each time it is shown is that the settings may have changed in the meantime.
A solution is to both clean the menu and recreate its entries in `aboutToShow` instead of separating the two tasks.

In my minimal example this works.
I'm going to apply the same fix in Frescobaldi and I'll push the results in a branch.

**Comment by dliessi** [comment]
With the change in branch `debug/issue1073` the snippets and templates menus work as expected.
Could you please test whether they are still working on Linux?
I expect it to work on all platforms, but you never know...

**Comment by uliska** [comment]
Seems to work here too, no differences noticed to the previous (correct) behaviour. Great to see progress on Mac compatibility.
