### ISSUE TITLE
How to deal with failure to install music fonts?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#1083]
I'm writing code to "install" notation fonts in the LilyPond installations. This means linking or copying files into LilyPond's datadir. Depending on the type of LilyPond installation this may fail due to denied permissions.

Does anyone know how (if) I can repeat the step after asking the user for its password? Is that even appropriate?

See https://stackoverflow.com/questions/51599374/pass-root-privilege-to-os-commands-in-python?noredirect=1#comment90164911_51599374

**Comment by uliska** [comment]
If there's no solution to that all I could do is show the user a message telling about the issue, detailing the problem and the files, maybe offering to open the font dir in the explorer for self-inspection. Ah wait, that won't work either since that file explorer won't be opened with root privileges either. Maybe suggest opening the terminal and copying the necessary shell code to the clipboard?

**Comment by uliska** [comment]
OK, [this answer](https://stackoverflow.com/a/51600535/2107724) explains in depth why we shouldn't try installing notation fonts when LilyPond is installed in protected directories. (to be updated)

**Comment by fedelibre** [comment]
I prefer option 2 (copy command to clipboard) over option 3 (script).
But I wonder how complex is it to adapt the command to every OS.

Option 4 (describe the problem and - my addition - link to a section in the documentation which explains how to solve it) may be a good solution as well.

**Comment by uliska** [comment]
For now I've implemented a Message box:

![image](https://user-images.githubusercontent.com/1812148/43579962-1b9ead32-9654-11e8-84a0-108210f2afab.png)

So far there is no documentation anyway, so linking into it won't work ...
