### ISSUE TITLE
Include-path not stored correctly on Windows

### ISSUE THREAD

**Issue by aujo** [wbsoft/frescobaldi#1094]
I tried to run the Edition Engraver today with Frescobaldi. It didn't work on Windows (though I could get it running on Linux.)
I pointed Frescobaldi's includepath to the folder containing OpenLilyLib (on my machine: "D:/OpenLilyLib"). Nevertheless I got the error "cannot find '/oll-core/package.ily' ". It turns out Frescobaldi saves the includepath without a trailing slash ("D:/OpenLilyLib"). I had to manually append the slash in Windows registry so it read "D:/OpenLilyLib/". After that, Frescobaldi/Lilypond could find the correct packages.

So it seems Frescobaldi should be updated to append a slash to a Windows-folder in the includepath settings panel.

**Comment by uliska** [comment]
Could you please verify this by running LilyPond from the command line, both with `-I D:/OpenLilyLIb` and `-I D:/OpenLilyLib/` options?

It seems it's *LilyPond* that expects a trailing slash in the include path (which is *not* documented in the manual). If so we'll of course support that.

**Comment by uliska** [comment]
http://lists.gnu.org/archive/html/bug-lilypond/2018-08/msg00027.html

BTW: If this is true I'm not sure if we should add the slash in the preferences or while constructing the job.

**Comment by aujo** [comment]
I checked the commandline before I went searching for the location where Frescobaldi stores its settings. So I can verify that running Lilypond from the commandline with `-I D:/OpenLilyLib` fails, whereas `-I D:/OpenLilyLib/ ` is successful

**Comment by uliska** [comment]
Could someone please check the behaviour of this on MacOS? It seems 
Linux doesn't care whether there's a trailing slash or not, so the fix 
could be easy if it doesn't break things on Mac.

**Comment by uliska** [comment]
Please test #1095

**Comment by aujo** [comment]
With the patch applied (I checked out the branch includepath-slash) Frescobaldi doesn't compile at all. Reverting to master restores Frescobaldi's capability to compile Lilypond-files.

**Comment by uliska** [comment]
What exactly is happening, nothing, errors in the LilyPond log, an error dialog?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by aujo** [comment]
No errors in the log, no error dialog, just nothing happens

**Comment by uliska** [comment]
I had produced something totally stupid while cleaning up Git branches. Please update the branch and try again.

**Comment by aujo** [comment]
Same thing happens, i.e. nothing....

**Comment by aujo** [comment]
Sorry, sorry, my bad. I forgot that I not only have to check out the new branch locally, but have to 'pull' as well to get your most recent changes. I'm still a bit new to this git-stuff.

With the updated includepath-slash branch Frescobaldi does find the Edition Engraver!
