### ISSUE TITLE
Python Version queue.py

### ISSUE THREAD

**Issue by jpvoigt** [wbsoft/frescobaldi#1112]
In `frescobaldi_app/job/queue.py` the line
`from enum import Enum , auto` references a python 3.6 thing

It should either be corrected in the requirements running frescobaldi 3 (Python 3.5 crashes)
or changed to not use it.

**Comment by uliska** [comment]
I've already noticed this in #1108. I will remove the use of `auto` which doesn't warrant the requirement of Python 3.6
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
@jpvoigt could you please test if the fix works (by nature of "works for me" I can't verify it)?
