### ISSUE TITLE
wish: general view tool for source documents

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#112]
Submitted by a user:

I often rewrite scores I've been given by friends/teachers on too-many-times photocopied sheet of paper or too-many-times scanned and printed. So I end up with some pdf files hardly readable I want to rewrite. And I find myself switching from my pdf viewer to Frescobaldi (I don't want to print something with so poor quality).

My wish is to have the preview window of Frescobaldi split horizontally. In the upper part there would still be the preview and in the lower part, a view of the pdf I want to reproduce.

I hope i will see this feature in a future release :)

**Comment by uliska** [comment]
Closing it because the *main* corpus has been implemented. Additional wishes in #923
