### ISSUE TITLE
Preview as a separate window

### ISSUE THREAD

**Issue by kastdeur** [wbsoft/frescobaldi#1128]
Would it be possible to 'externalise' the preview pane in such a way that it can behave as a separate window. (Somewhat like the toolbars of GIMP)
This way, using workspaces, the preview pane can be on a different workspace.

Reason: When copying/redacting, I like to have the original(pdf) near my code first, and afterwards check it with the 'previewed' one. 
To do the first part, I disable the preview pane.
For the second one I minimise the code pane to have the preview and original next to each other.

Implementing this would allow me to move the 'original' around the workspaces and obtain the same workflow.

**Comment by uliska** [comment]
Could you please go through the issues on this list? I am quite sure that this question has been discussed before, but I'm not sure if there were any useful comments to it. In the meantime I'll assign the "wish" label.

**Comment by fedelibre** [comment]
You can already detach a panel: just drag it "outside" the main window.

![fresco-detached-preview](https://user-images.githubusercontent.com/1644647/48790290-514ade00-ecef-11e8-9600-7f1f6414b09d.png)

**Comment by uliska** [comment]
@kastdeur Does this already fulfill your needs?

**Comment by kastdeur** [comment]
@uliska You are right! #1051 is related. And I think it's a double of #841.

@fedelibre, that's the thing I would like to be able to move to another workspace.
(At least in cinnamon 3.8.9 this is not possible). I figured this would be possible if it were a full window of some sorts.

**Comment by fedelibre** [comment]
> @fedelibre, that's the thing I would like to be able to move to another workspace.
> (At least in cinnamon 3.8.9 this is not possible). I figured this would be possible if it were a full window of some sorts.

Same on GNOME desktop. It's not a really independent window.

**Comment by uliska** [comment]
I'll close this issue, leaving a reference to #1051.
