### ISSUE TITLE
Why check for sip?

### ISSUE THREAD

**Issue by bnavigator** [wbsoft/frescobaldi#1332]
Hi,

Why exactly do you check for the sip version in debuginfo? As far as I can see, you do neither use the python package `sip` or `PyQt5.sip` nor use sip-build to compile anything.

**Comment by fedelibre** [comment]
Disclaimer: I'm not a developer.

Frescobaldi depends on [python-poppler-qt5](https://github.com/frescobaldi/python-poppler-qt5), which needs `sip`.
Perhaps checking the sip version used to build python-poppler-qt5 is useful for debugging?

**Comment by bnavigator** [comment]
The reason I am asking: This creates a runtime dependency on sip for frescobaldi while it should only create a build dependency on the sip build tools for python-poppler-qt5.
