### ISSUE TITLE
Frescobaldi 3.13 crashes with python 3.10

### ISSUE THREAD

**Issue by garpu** [wbsoft/frescobaldi#1398]
Slackware-current (linux) upgraded to python 3.10.  I recompiled python-poppler-qt5, and python-ly without incident. When I try to launch frescobaldi I get:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/lib64/python3.10/site-packages/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'
zsh: IOT instruction  frescobaldi

Is this a bug with the application, or one of the dependencies not building properly? 

in python3, "import popplerqt5" doesn't throw an error.

**Comment by KeithSBB** [comment]
Just upgraded Fedora Jam to v 35 with Python 3.10
These Float expecting int errors are popping up all over the place in Frescobaldi.  I suggest looking into a generic fix if possible. (what happen to duck typing in python 3.10?)

**Comment by wbsoft** [comment]
I'm looking into it right now. Floats should be automagically converted to ints...

**Comment by wbsoft** [comment]
Related to this change in Python 3.10.
We should fix Frescobaldi, if possible with an automated type check :-)
https://bugs.python.org/issue37999

**Comment by wbsoft** [comment]
Also in 3.2 (master) and in qpageview I have added those fixes.

**Comment by dliessi** [comment]
@wbsoft: Do you plan to release 3.1.4 soon?
If I'm not mistaken, I think that the following commits from `master` can be cherry-picked into `v3.1.x`:
- 9dafb20273dda7e62b0b8f03651bb5204fc7360f
- 0a195936b3f1be7c0e41ce9fdd7f016e6e1c7bbd
- 84b93ae241675a120e0332e02c74f04a0a48b167
- c0d68b4e1a6c8f6ed4e4f5d0147dc0d83f5c889c
- 87f87249f1ef0ab0e54490dfed47db0718f4f072
- 849f299ee97f0b2cd0bc81c9a01153f349c1d340

**Comment by dliessi** [comment]
I cherry-picked the following into `v3.1.x`.
* [9dafb20](https://github.com/frescobaldi/frescobaldi/commit/9dafb20273dda7e62b0b8f03651bb5204fc7360f)
* [0a19593](https://github.com/frescobaldi/frescobaldi/commit/0a195936b3f1be7c0e41ce9fdd7f016e6e1c7bbd)
* [c0d68b4](https://github.com/frescobaldi/frescobaldi/commit/c0d68b4e1a6c8f6ed4e4f5d0147dc0d83f5c889c)
* [87f8724](https://github.com/frescobaldi/frescobaldi/commit/87f87249f1ef0ab0e54490dfed47db0718f4f072)
* [849f299](https://github.com/frescobaldi/frescobaldi/commit/849f299ee97f0b2cd0bc81c9a01153f349c1d340)

I left [84b93ae](https://github.com/frescobaldi/frescobaldi/commit/84b93ae241675a120e0332e02c74f04a0a48b167) out since it is not important and needs to take the translation files into account.

**Comment by limburgher** [comment]
I applied the bulleted commits above, and still needed the attached.

[progressbar.patch.txt](https://github.com/frescobaldi/frescobaldi/files/7817432/progressbar.patch.txt)

**Comment by alerque** [comment]
A patch release that fixes Python 3.10 support would be very welcome. The Arch Linux package is borked since the default Python got updated to 3.10. The `frescobaldi` package was rebuilt and builds fine, but it is not functional.

**Comment by dliessi** [comment]
> I applied the bulleted commits above, and still needed the attached.

@limburgher The fix you propose is already in `master` (73cd53e7e089537aa853eea7d43f212145bd5ef5) and in `v3.1.x` (51886dba8a3cb3db6eba9a6cf1d65bd8eaf877aa).
Anyway, thanks for your effort.

If you are running from the repository, you may need to pull the latest changes.
If instead you are patching an installed version, check branch `v3.1.x` for other fixes you may have missed.

**Comment by franquemagnee** [comment]
Error still present, Frescobaldi 3.1.3 unusable with Python 3.10 (Fedora 35).
Support @alerque request, an **official patch release for Frescobaldi 3.1.3** that fixes Python 3.10 support would be more than welcome. As well as Arch Linux, Fedora now forces Python3.10 as only version.
Have a significant daily work on Frescobaldi. If a sustainable workaround exists, would be happy to hear it.

**Comment by limburgher** [comment]
Fedora package maintainer. @franquemagnee can you post the exact error you're still getting in Fedora 35 3.1.3-7?

**Comment by franquemagnee** [comment]
Here is the cli traceback
```
[franquemagnee@polarbear plugins]$ frescobaldi
QSocketNotifier: Can only be used with threads started with QThread
inotify_add_watch(/home/franquemagnee/.config/ibus/bus/9779957fc5e448c0b07a0ad940b25354-unix-wayland-0) failed: (No space left on device)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/widgets/linenumberarea.py", line 83, in paintEvent
    rect.moveTop(geom.top())
TypeError: moveTop(self, int): argument 1 has unexpected type 'float'
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QWidget::repaint: Recursive repaint detected
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
QPaintDevice: Cannot destroy paint device that is being painted
Erreur de segmentation (core dumped)
```
Here is the gui error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/widgets/linenumberarea.py", line 83, in paintEvent
    rect.moveTop(geom.top())
TypeError: moveTop(self, int): argument 1 has unexpected type 'float'
```

**Comment by limburgher** [comment]
What action had you taken that led to this?

**Comment by limburgher** [comment]
Never mind, I found it, and will ship an update with that patch.

**Comment by franquemagnee** [comment]
> What action had you taken that led to this?

Not sure I understand well the question: simply launch Frescobaldi from CLI and enjoy! ;-)

**Comment by franquemagnee** [comment]
> Never mind, I found it, and will ship an update with that patch.

Would be so great !!! \o/

**Comment by franquemagnee** [comment]
@limburgher Quick question, will this update target F35 ?

**Comment by limburgher** [comment]
Indeed! https://bodhi.fedoraproject.org/updates/FEDORA-2022-1342570ed0

**Comment by cleinias** [comment]
I am still suffering from this problem---Frescobaldi almost unusable on Archlinux. Python version is  3.10.2 (latest on Arch), Frescobaldi's version is 3.1.3-5 (from Arch's repo).

**Comment by alerque** [comment]
@cleinias I just added more patches to the ARch Linux build from the 3.1.x branch that were added since the ones mentioned above. You can try the update in the repo.

To frescobaldi maintainers, please just cut a 3.1.4 already! You are making downstream package maintainers all redo each others work packaging unreleased code because 3.1.3 is totally busted. Even if you find more things and need to cut more patch releases, a stable release that mostly works is better than one that doesn't work at all.

**Comment by cleinias** [comment]
@alerque Thanks for taking care of the issue so quickly. frescobaldi works again on my system now

**Comment by MJE10** [comment]
Hi @alerque and others, could this issue be related to the unexpected type problem with Ubuntu/Debian #1433 ?

**Comment by alerque** [comment]
Yes it is the same problem.

Upstream needs to cut a new release to get this moving towards distros so every distro doesn't have to fiddle around with how to patch what.

**Comment by srhaile** [comment]
Any update on this? I recently upgrade to the most recent LTS version of Ubuntu and frescobaldi is now complete unusable :( 

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/autocompile.py", line 113, in slotTimeout
    eng.runJob(j, doc)
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 252, in runJob
    job.manager.manager(document).start_job(j)
  File "/usr/share/frescobaldi/frescobaldi_app/job/manager.py", line 63, in start_job
    app.jobStarted(self.document(), job)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 73, in jobStarted
    self.showProgress(document)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 59, in showProgress
    self._bar.start(buildtime, j.elapsed_time())
  File "/usr/share/frescobaldi/frescobaldi_app/widgets/progressbar.py", line 74, in start
    self._timeline.setDuration(total * 1000)
TypeError: setDuration(self, int): argument 1 has unexpected type 'float'
