### ISSUE TITLE
Consider bumping Python version requirement

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1508]
I just noticed instances of `with open(filename, 'r'):`, where `encoding="utf-8"` is missing. This means that a system-dependent encoding can be used instead of UTF-8 (see https://peps.python.org/pep-0686/#motivation).

The `INSTALL` file states that Frescobaldi requires Python ≥ 3.6. However, Python 3.6 went EOL at the end of year 2021. If we bump the requirement to Python 3.7, we can use Python's UTF-8 mode, which makes UTF-8 encoding the default (and will become the default in Python 3.15, as proposed in PEP 686 linked above). Then we no longer have to care about encodings.

Judging from https://github.com/frescobaldi/frescobaldi/issues/1285, we cannot bump higher than 3.7 though.

**Comment by PeterBjuhr** [comment]
Sounds good to me if you are confident everything will hold for 3.7! :+1:

**Comment by fedelibre** [comment]
> Judging from #1285, we cannot bump higher than 3.7 though.

Are you referring to the Mac issues mentioned by @dliessi in that conversation? I wonder if they are still valid after almost 3 years with latest PyQt5.

Anyway, I think that bumping to 3.7 should be safe. Will you send a PR?

**Comment by dliessi** [comment]
Regarding my comment in #1285, I still cannot recall what the problem was, but I packaged 3.1.3 with Python 3.9, so feel free to bump the requirement up to that version.

I'm trying with Python 3.11, let's see if packaging 3.2 works this time...
