### ISSUE TITLE
Migrate from setup.py to new packaging standards and away from distutils

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1518]
Currently, Frescobaldi uses the traditional `setup.py` file to define its metadata with setuptools. However, the modern recommended way is the `pyproject.toml` file. Furthermore, if setuptools is not available, it falls back on distutils, which is deprecated and will be removed in Python 3.12. Moving to `pyproject.toml` would allow getting rid of that, since one of the initial goals of `pyproject.toml` was to enable projects to specify their build/packaging tools, allowing to specify a dependency on setuptools.

**Comment by fedelibre** [comment]
Happy to test your pyproject.toml on Windows and maybe Mac once you have a ready PR

**Comment by dliessi** [comment]
Happy to test on Mac!
