### ISSUE TITLE
Behavior when opening nonexistent file from the command line

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1552]
I would generally expect from an editor launched with `editor nonexistent-file` to accept "opening" the file, starting from a blank file, and saving to "nonexistent-file" when it's written, effectively creating a new file. For example, this is the case with `emacs`, `gedit` and `vim`.

With `frescobaldi`, it almost works, except that for some reason, it opens *two* blank files.

**Comment by PeterBjuhr** [comment]
Confirmed! But it would be easy to consider it a bug and not a wish. I guess you consider it a wish from the perspective of an untried feature that almost works!?
