### ISSUE TITLE
Bug reporting system

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1558]
Currently, when it crashes, Frescobaldi allows the user to write an email to @wbsoft with the traceback. Since @wbsoft currently has less time for Frescobaldi than he used to, this is maybe not ideal. Perhaps we should change it to let the user create a new issue on GitHub instead.

**Comment by fedelibre** [comment]
> Perhaps we should change it to let the user create a new issue on GitHub instead.

Yes, I agree.

**Comment by PeterBjuhr** [comment]
Yes, that would be a more direct way regardless.

**Comment by PeterBjuhr** [comment]
No problem, I haven't done anything. I have only been thinking about the api solution, and the issue of safely storing the api key.

**Comment by PeterBjuhr** [comment]
I'll post more thoughts in the PR.
