### ISSUE TITLE
AttributeError: module 'viewers.documents' has no attribute 'Document'

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1609]
Traceback (most recent call last):
  File "/home/jean/repos/frescobaldi/frescobaldi_app/viewers/__init__.py", line 77, in wrapper
    func(self)
  File "/home/jean/repos/frescobaldi/frescobaldi_app/viewers/manuscript/__init__.py", line 59, in reloadView
    reread = documents.Document(active_manuscript.filename())
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'viewers.documents' has no attribute 'Document'

Optionally describe below what you were doing:

I used the "reload" button in the contextual menu of the Manuscript Viewer.

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.11.3
Git branch: master
on commit: 16b6d78c
python-ly: 0.9.7
Qt: 5.15.9
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 22.8.0
python-poppler-qt: 21.3.0
OS: Linux-6.2.15-300.fc38.x86_64-x86_64-with-glibc2.37

**Comment by PeterBjuhr** [comment]
I confirm the bug! It's can be easily reproduced.
