### ISSUE TITLE
Correct default open/save path on New file tab

### ISSUE THREAD

**Issue by m0003r** [wbsoft/frescobaldi#162]
If some files are already opened (or were), default path in open/save dialog when saving newly created file must be same as for last edited file, not application folder.

(sorry for bad english)

**Comment by rpspringuel** [comment]
It would be nice if it was possible to have "last used folder" as a possible default for the home folder.  I have my default set to my documents folder (which is where I want it to be at the start of any session), but when I'm working on a project which requires me to create a bunch of files, having to navigate down through the file tree to the project every time I create a new file is some what tedious.
