### ISSUE TITLE
Clarify purpose of -e / --encoding option

### ISSUE THREAD

**Issue by jeanas** [wbsoft/frescobaldi#1651]
The `frescobaldi` command supports an `-e` / `--encoding` option to open files in an encoding other than UTF-8. I wonder why, since LilyPond supports UTF-8 encoded files exclusively, and no other encoding.

**Comment by fedelibre** [comment]
Maybe because Frescobaldi can also open .html or .tex files (mixed with lilypond code) and these files may have a different encoding? See for example #38 (well, opened in 2012). I guess that today any file should use UTF-8?
