### ISSUE TITLE
wish: better autocompletion

### ISSUE THREAD

**Issue by jan-warchol** [wbsoft/frescobaldi#299]
Here are some ideas about autocompletion that might be interesting:
- since it is very rare to have commands differ only by letter case, it would be nice to make the dropdown list with suggestions case-insensitive (i.e. when i write \sluru, it should still list \slurUp as a suggestion)
- allow partial autocompletion with TAB key, like in bash - i.e. if i write \sl and hit TAB, it will be autocompleted to \slur (because there are no commands that begin with \sl but don't begin with \slur)
- add an option for automatic autocompletion - i.e. when there is only one possibility to autocomplete it will be inserted automatically.  This should be turned off by default, but it could be very handy for advanced users.  For example, it would be awesome to be able to type just \voo for \vo(ice)O(ne).

**Comment by uliska** [comment]
I think accepting the suggestion by `Enter` is a good thing, and I wouldn't want to have it autocompleted automatically (if that's what was suggested).

The TAB suggestion is very nice. Additionally I suggest using the TAB key for iterating through the suggestion list. I think TAB is much easier to reach than the arrow keys on most keyboards.

**Comment by jamesthechamp** [comment]
hey,
i am a new contributor would love to contribute and participate for gsoc 2017.
i made a patch for this issue #918
here i implement the functionality to iterate over suggestion list as show follow
![peek 2017-03-23 03-59](https://cloud.githubusercontent.com/assets/11019397/24223846/023c43c6-0f7e-11e7-8126-a648573d33fc.gif)
please have a look on it.

**Comment by uliska** [comment]
Implemented so far (by @jamesthechamp or me):

* Partial autocompletion with TAB
* Common subsets are automatically filled (but selected so they can be killed again)
* TAB cycles through suggestions if there's nothing to be partially completed
* Accepting by ENTER is still necessary, but one doesn't have to select an item with arrow keys or mouse

**Comment by uliska** [comment]
Implemented case insensitivity.

Now matching is done case insensitive. But the document text is only updated upon acceptance

**Comment by uliska** [comment]
I will not implement automatic autocompletion. As I mentioned I prefer having to accept with ENTER.

The sequence to enter `\voiceOne` (example from the original issue) is now

`\vo` `TAB` `o` `ENTER`

The only missing feature now is the automatic selection upon partial completion (see https://github.com/wbsoft/frescobaldi/pull/918#issuecomment-288719192 for explanation and screenshot). I tried to do it but for some reason it didn't do what I thought ...

**Comment by uliska** [comment]
@wbsoft I think this is *nearly* complete and #922 can be merged. Could you please have a look into the last commit and check why it doesn't do what it should?
