### ISSUE TITLE
Idea: automatic installation/update of LilyPond

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#313]
This post http://lists.gnu.org/archive/html/lilypond-user/2013-12/msg00238.html
made me think if it wouldn't be nice to add a function to download, install and configure LilyPond.

I'd say that on startup Frescobaldi checks for LilyPond and suggests to install if none is present. Later this would be only on request (i.e. menu item).

It should be configurable if only stable or also development releases should be looked for.

I can try it if it seems worthwile.

**Comment by wbsoft** [comment]
I think 2.18 arrives quite soon. So this wish goes to a later version :-)

**Comment by fedelibre** [comment]
> In my WIP, I've moved the LilyPond version manager from the preferences to a dedicated place, because I think it's good to have it more visible, as it's something most users will need at some point, especially beginners. Do you think this is a good idea?

I'm not sure it's a good idea. I'd rather keep all the configuration options in one place: the LilyPond section within the Preferences is easily visible.
Let's see what other people think.

**Comment by fedelibre** [comment]
> What do you think about the general UI? I made the partially downloaded versions items in the version list because I thought it would be better not to have a third window for the installation process on top of the preferences window, which is already a window on top of the main window.

I like the UI! And it's a really handy feature. We'll have to check how it works in the flatpak package. NOTE: I'm going on holidays in 3 days (next Saturday) and I don't think I'll bring my laptop anywhere.

I don't understand what are the "partially downloaded versions items". I see the versions list within Other in the video:  is this what you are referring to? I was wondering how that list of versions is generated... Please explain

**Comment by fedelibre** [comment]
> Sorry, I meant the versions that are currently being downloaded.
> 
> Originally, I was planning to make the "Add" button open a dialog for selecting the version to install. But then I thought that having too many nested windows was to be avoided if possible.

Ok, I think it's a good idea.

I look forward to test it when it's ready.
