### ISSUE TITLE
Export to audio file

### ISSUE THREAD

**Issue by ryanmichaelmcclure** [wbsoft/frescobaldi#368]
I would like to add a feature to Frescobaldi that would take the MIDI output and allow one to create a WAV/MP3/Etc. file using something such as Timidity and ffmpeg. However, I know that it would require Frescobaldi to ship with extra software--what path should I take to do this?

**Comment by wbsoft** [comment]
Closing this bug. Although the feature might need some polishment, it is implemented!

**Comment by fedelibre** [comment]
this is still available only when running from the source tree only (see my previous comment)
is it intended?

**Comment by PeterBjuhr** [comment]
@fedelibre It will be available also if you enable experimental features in the general preferences. (I think this was changed after your previous comment.)

**Comment by fedelibre** [comment]
yes, I've enabled it and restarted fresco and I can see it now
