### ISSUE TITLE
Edit Window doesn't refresh properly

### ISSUE THREAD

**Issue by deep8va** [wbsoft/frescobaldi#393]
Sorry if this has already been posted; I've never posted anything before and hope I'm doing it right...

Frescobaldi 2.0.15 scrambles the edit screen when folding and unfolding. See the attached png. It is possible to "unscramble" the view by scrolling up and down, but this is bothersome.

Thanks! Feedback welcome on how to submit a bug properly.
Mark
![frescbug](https://f.cloud.github.com/assets/7023996/2485001/a071b5ac-b113-11e3-9323-8cfe6235a2de.png)

**Comment by wbsoft** [comment]
@deep8va , is this bug still there in 2.17.2 ?

**Comment by deep8va** [comment]
It appears to have been fixed. I'm not seeing a problem anymore.

Please forgive the delay in responding: I haven't been active on the
Lilypond issues for a while and just happened to log into this email
address this morning!

Thanks again for your great work!
Mark

**Comment by wbsoft** [comment]
thanks four your feedback!
