### ISSUE TITLE
New Feature: Toolbar for switching Sessions

### ISSUE THREAD

**Issue by brentboylan** [wbsoft/frescobaldi#448]
I am really enjoying the Sessions feature which lets me save a related group of files and get back to them easily. A nice feature would be to have a toolbar for switching to different saved sessions quickly, something similar to the PDF viewer tool that lets you select which output file you are viewing.

**Comment by wbsoft** [comment]
I think the Sessions menu already much behaves like a toolbar item with a popup-list. So I close this bug, because the toolbar can't become too long.
