### ISSUE TITLE
Change s into R and vice versa (rest conversions)

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#497]
I have a distinct feeling that this has been discussed before, but I couldn't find any previous wish for it.

I'm thinking about the possibility of replacing a rest with another type of rest. In particular I think it would be very useful to change between full measure rests `R` and spacer rests `s`. 

I'm thinking about something similar to the conversion between absolute and relative pitch modes. Just select a segment and do the conversion.

**Comment by PeterBjuhr** [comment]
Moving this to https://github.com/wbsoft/python-ly/issues/10

**Comment by PeterBjuhr** [comment]
Now the basic functionality is implemented in Python-ly.

I think I can settle with controlling this in Frescobaldi via snippets (perhaps an addition to the built-in snippets!?).

**Comment by wbsoft** [comment]
I think it is nice to provide a submenu in the Tools menu, just below the Pitch submenu, and implement the callers in a little module `frescobaldi_app/rests/__init__.py`, just like `frescobaldi_app/pitch/__init__.py`

**Comment by PeterBjuhr** [comment]
I'll do that!
