### ISSUE TITLE
language-specific typographical quotes

### ISSUE THREAD

**Issue by nitsnatsnok** [wbsoft/frescobaldi#529]
In the „insert“ menu there’s the feature to print double/single typographical quotes. This is very useful, but  it inserts the same marks regardless which interface language was chosen by the user. Please make it print the quotation marks that are standard in the language frescobaldi appears!
These are the following (Source de.wikipedia.org/wiki/Anf%C3%BChrungszeichen):
German: „“ / ‚‘ (U201E and U201C / U201A and U2018) 
Spanish: «» / ‹› (U00AB and U00BB / U2039 and U203A)
French: «» / ‹› (same as Spanish)
Galician: «» ‘’ (U00AB and U00BB / U2018 and U2019)
Italian: «» ‘’ (same as Galician)
Dutch: “” / ‘’ (same as English)
Polish: „” / «»  (U201E and U201D / U00AB and U00BB)
Brazilian Portuguese: «» / “” (U00AB and U00BB / U201C and U201D)
Turkish: “” / ‘’ (same as English)
Russian: «» / „“ (U201C and U201D / U201E and U201C)
Ukrainian: «» / „“ (same as Russian)

In Polish there are no „single“ marks used in the standard, therefore the menu item should better be named something like „primary“ and „secondary“ quotes. In fact it would suffice to rename the menu items in the polish translation only (they read „single“ and „double“ currently). The Polish Wikipedia calls „” „cudzysłów apostrofowy“ and «» „cudzysłów ostrokątny“ (pl.wikipedia.org/wiki/Cudzysłów).

Thank you very much for your work!

**Comment by wbsoft** [comment]
If we use the terms primary and secondary typographical quotes instead of single and double, which are the primary?

**Comment by nitsnatsnok** [comment]
IMHO:
primary = used for quoting, direct speech, irony etc., in my list above these are the first
secondary = used for quoting (etc.) within a quote, in my list the second ones

for all languages except Polish this would be
primary= double
secondary = single

**Comment by uliska** [comment]
I think in most languages double quotes are used as primary solution.

**Comment by wbsoft** [comment]
Implemented. See editor preferences.
