### ISSUE TITLE
Paths to lilypond documentation: Adding a URL not working as expected

### ISSUE THREAD

**Issue by BrentMBoylan** [wbsoft/frescobaldi#534]
When I try to add a URL as a path for lilypond documentation and then navigate to it in the Documentation Browser I get this error:
"The requested URL /website/development.html/Documentation/index was not found on this server."

I am trying to set this up so that the documentation in Frescobaldi matches the version of lilypond I have installed (current development version) instead of the default (current stable version) or to even have paths to both sets of documentation I can choose from. This appears to be what is intended but something is broken.

**Comment by sincere-music** [comment]
http://www.lilypond.org/doc/latest/ works just as well.
