### ISSUE TITLE
Transform pitches to another mode/scale

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#538]
A function that in analogy or combination with a transpose can change the pitches to adapt to an optional scale/mode. Example, change from C major to C Dorian, C Phrygian, C Lydian, C Mixolydian or C Aeolian (natural minor).

**Comment by PeterBjuhr** [comment]
I think we can close this now!

**Comment by wbsoft** [comment]
add entry to readme? (in master)

**Comment by PeterBjuhr** [comment]
I'm sorry I don't follow, which entry?

**Comment by wbsoft** [comment]
I'm sorry, I meant mentioning the mode shifter in the ChangeLog, not the Readme, but this issue is about the modal transpose.... time to go to sleep :-)

**Comment by PeterBjuhr** [comment]
No problem! Actually the issue shouldn't have been about the modal transpose at all. But I was confused about its proper use.

Do you want me to add an entry about the new mode shift in the ChangeLog?
