### ISSUE TITLE
Stringtuning gets transposed

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#539]
The `\stringTuning` command has a chord as argument. When included in a selection that is transposed by `Tools->Pitch->Transpose` also the pitches in the argument chord are transposed.

**Comment by wbsoft** [comment]
Here it can be seen that the chord argument of `\stringTuning` indeed does not influence the parsing of relative pitches.
```
\relative {
  c
  \stringTuning <e e e>
  g
}
```
This results in two low c notes.
I will try to change the current transposition routine to completely ignore the chord after `\stringTuning`.
