### ISSUE TITLE
TypeError: must be encoded string without NULL bytes, not unicode

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#541]
Frescobaldi: 2.17

Python: 2.7.6 -- Qt: 4.8.6 -- PyQt4: 4.10.4 -- sip: 4.15.5
OS: Linux-3.13.0-43-generic-x86_64-with-Ubuntu-14.04-trusty
```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/frescobaldi_app/view.py", 
line 231, in contextMenuEvent
menu = contextmenu.contextmenu(self)
File 
"/usr/local/lib/python2.7/dist-packages/frescobaldi_app/contextmenu.py", 
line 45, in contextmenu
actions.extend(open_files(cursor, menu, mainwindow))
File 
"/usr/local/lib/python2.7/dist-packages/frescobaldi_app/contextmenu.py", 
line 79, in open_files
return list(map(action, open_file_at_cursor.filenames_at_cursor(cursor)))
File 
"/usr/local/lib/python2.7/dist-packages/frescobaldi_app/open_file_at_cursor.py", 
line 65, in filenames_at_cursor
if os.access(name, os.R_OK):
TypeError: must be encoded string without NULL bytes, not unicode
```

**Comment by PeterBjuhr** [comment]
So basically this issue can't be solved with less than porting to Python3 and Qt5!?

Would a `from __future__ import ...` help at all?

**Comment by wbsoft** [comment]
Qt4 uses surrogate pairs for characters above the FFFF range. Py3 correctly takes that behaviour over, meaning the '𝄬' is two characters. We could arrange for that. But in Qt5 the issue is fully resolved inside Qt which is even better. So we can get rid of this bug in Py3/Qt4 :-) But Py3 support is already close!

**Comment by proski** [comment]
We can add code to strip trailing \x00 characters whenever Qt adds them. The users don't need to know which characters are "strange".
