### ISSUE TITLE
goto matching pair

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#563]
Is it already possible to navigate to a matching bracket? I only find functions in the Edit menu to highlight and select matching pairs. But it would be nice to also jump there, especially with a keyboard shortcut.

**Comment by wbsoft** [comment]
View→Matching Pair jumps to the matching bracket
View→Select Matching Pair selects upto the matching bracket

You can assign a shortcut in the settings.

**Comment by uliska** [comment]
Thanks
