### ISSUE TITLE
on svg view close, "Script error." is printed to the console

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#566]
When a svg view is closed (e.g. when closing a document that has a svg output document in the svg viewer), on the console
```
Script error.
```
is printed. Probably an issue in the javascript that runs inside the SVG view.

**Comment by PeterBjuhr** [comment]
I've traced the error to `svgview.view.clear` and the line:

    self.load(QtCore.QUrl())

Exactly why this triggers the error is not totally clear to me, but it seems to have to do with the browser's same origin policy (see http://en.wikipedia.org/wiki/Same-origin_policy).

If the view could be cleared in another way I think it would be preferable.

**Comment by wbsoft** [comment]
I can't find another way than `QWebView.setUrl(QUrl())` which almost acts like `load()`, but will empty the view immediately instead of keeping old content visible while loading the new content. But `setUrl()` also causes `Script error.` being printed to the console.

**Comment by PeterBjuhr** [comment]
The printout of JavaScript errors in the console is really only for debugging purposes. In the case this error can't be helped I think I should just suppress the errors. But I'll take a closer look first!

**Comment by PeterBjuhr** [comment]
Although I find it kind of ugly we could easily hide this seemingly irrelevant error message.

Another idea which I think is quite nice is to have a default svg-file that is shown when the viewer is empty. It could be the Frescobaldi logo and some text.

What do you think?

**Comment by wbsoft** [comment]
Hiding the message is not needed I think.

I would make the empty view simply grey, like the music view is. Maybe with a very dimly colored frescobaldi "watermark" at the background.

**Comment by PeterBjuhr** [comment]
I'm uncertain of how to reference the file, but I'll give it a go!

**Comment by PeterBjuhr** [comment]
Is the logo dimly enough or is it too apparent?

**Comment by PeterBjuhr** [comment]
Everything seem to be cleared.
