### ISSUE TITLE
convert-ly cannot be run from Frescobaldi under Python 3.4

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#577]
Traceback (most recent call last):
  File "/home/proskin/src/frescobaldi/frescobaldi_app/convert_ly.py", line 234, in run
    out, err = proc.communicate(self._text.encode(self._encoding))
  File "/usr/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1599, in _communicate
    self._save_input(input)
  File "/usr/lib/python3.4/subprocess.py", line 1675, in _save_input
    self._input = self._input.encode(self.stdin.encoding)
AttributeError: 'bytes' object has no attribute 'encode'

It turns out Python 3.4 blindly tries to encode input given in subprocess.communicate() if universal_newlines = True, even if the input is already encoded to bytes (definitely not "liberal in what you accept").

One of the following should be done.

If we want control over encoding, we should not be using universal_newlines = True. We should be using self._encoding to encode input and decode output. UTF-8 should not be used (convert_ly.py:240).

If we trust Python to do encoding/decoding. Then we don't encode or decode anything. But if the document encoding is not the same as locale.getdefaultlocale(False), then we are in trouble.

In any case, setting LANGUAGE=C in convert-ly environment is dubious, especially on non-Windows platforms.

**Comment by proski** [comment]
I looked at the issue again and it's absolutely clear now. We do encoding and decoding manually, so we shouldn't be using universal_newlines. That's the only issue that affects Python 3 compatibility.

The choice of encodings and the use of LANGUAGE=C are separate issues. If anybody wants good support for encodings other than UTF-8, they are welcome to address this.

As far as Python 3 compatibility is concerned, I consider the issue fixed in 5a83744f5bea19a98794f210a0c92f8a96b4a3d2

Frescobaldi should work under Python 3 just as well as it does under Python 2 (probably better due to #541). Trove categories can be updated now to include Python 3, 3.2, 3.3 and 3.4.

**Comment by wbsoft** [comment]
That's fantastic Pavel!! Many thanks for you hard and conscientious work!
