### ISSUE TITLE
[ubuntu linux version 2.16.2] tooltip formatting

### ISSUE THREAD

**Issue by jontyD** [wbsoft/frescobaldi#581]
tooltips here are pale yellow background with white text
can't read them at all
can't see anywhere to change this in the preferences either
am i missing something or does this need a code change?

**Comment by wbsoft** [comment]
Which gui theme are you using? I have seen it before. It's not a Frescobaldi bug but an issue in the Qt/Gtk gui theme integration. But we could devise a workaround...

**Comment by wbsoft** [comment]
On my system it happens when I change GUI style from Gtk to Cleanlooks. But after restarting Frescobaldi, the tooltip text is black.

**Comment by jontyD** [comment]
Dear Wilbert

Thanks for the prompt reply.

Yes I found that changing the default gui to gtk+ sorted it out, haven't retried cleanlooks again yet though.

So I am happy but maybe whoever manages the cleanlooks can look into it when they have time.

Thanks again.

jonty









Jonathan Davis
Web Developer

<http://www.transcendit.co.uk>[cid:transcendit.png]






C10 Marquis Court
Team Valley, Gateshead
NE11 0RU
0191 482 0444<calto:0191%20482%20044>
www.transcendit.co.uk<http://www.transcendit.co.uk>





IT Support & Implementation
Systems & Network Administration
Application Development
Web Design
Cloud Computing & Hosting



 [cid:partners.png]


Please help the environment: if possible do not print this email. Please note: All prices quoted exclude VAT.
The information contained within this email is confidential. It may also be legally privileged. It is intended only for the stated addressee(s) and access to it by any other person is unauthorised. If you are not an addressee, you must not disclose, copy, circulate or in any other way use or rely on the information contained in this email.
Such unauthorised use may be unlawful. If you have received this email in error, please inform us immediately at enquiries@transcendit.co.uk<mailto:enquiries@transcendit.co.uk> and delete it and all copies from your system.
Transcendit Ltd is a Limited Company registered in England and Wales No.: 4041370. VAT No.: 747 2063 34


On 18/01/15 20:36, Wilbert Berendsen wrote:

On my system it happens when I change GUI style from Gtk to Cleanlooks. But after restarting Frescobaldi, the tooltip text is black.

-

**Comment by wbsoft** [comment]
Closing because it is not a Frescobaldi bug (but a Qt issue).
