### ISSUE TITLE
cut, copy and paste menu toolbar

### ISSUE THREAD

**Issue by lukaszmb** [wbsoft/frescobaldi#584]
Hi, I use the program Autokey. But I have a problem with clipboard on Frescobaldi. The script
keyboard.send_keys("<shift>+<left>")
keyboard.send_keys("<ctrl>+c")
time.sleep(0.4)
tospacja = clipboard.get_clipboard()
does not work for me. Why?
Can be programmed mouse buttons solve the problem?
Sorry for my English... I'm from Poland.

P.S. Frescobaldi is a great tool!

**Comment by wbsoft** [comment]
I don't exactly understand what you're trying to accomplish. What should Autokey do?

**Comment by lukaszmb** [comment]
2015-01-19 23:42 GMT+01:00 Wilbert Berendsen <notifications@github.com>:

> I don't exactly understand what you're trying to accomplish. What should
> Autokey do?


​Thanks for your response!

Again sorry for my English.
So
1. I build special keyboard for lilypond, because I have a lot of writing
2. Frescobaldi is the best tool for
So
3. For example, if I press bes, I want to write "bes " - bes + space - and
it worked
4. If I press the "16", or, for example, the "ff" for \ff I want to remove
unnecessary space preceding

Python script:
keyboard.send_keys("<shift>+<left>")
time.sleep(0.05)
keyboard.send_keys("<ctrl>+c")
tospacja = clipboard.get_clipboard()

Errors:
Script name: 'usun_sp_przed'
Traceback (most recent call last):
   File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 454, in
execute
     exec script.code in scope
   File "<string>", line 14, in <module>
   File "/usr/lib/python2.7/dist-packages/autokey/scripting.py", line 856,
in get_clipboard
     raise Exception ("No text found on clipboard")
Exception: No text found on clipboard​

How to retrieve the contents of the clipboard with Frescobaldi?

**Comment by wbsoft** [comment]
Ctrl+C should do that. So I don't really understand why this fails.

**Comment by lukaszmb** [comment]
If I select text by mouse, clipboard sees this text, but I select text by
keyboard (Shift and arrow), clipboard not sees this text

2015-01-20 9:51 GMT+01:00 Wilbert Berendsen <notifications@github.com>:

**Comment by wbsoft** [comment]
It seems that this has to do with how Qt4 copies text to the clipboard. It is not changing the X11 primary selection...

**Comment by wbsoft** [comment]
You should direct Autokey to get the "clipboard" selection instead of the X11 primary selection. This might mean that you have to subclass the Clipboard class in autokey, and change the way the content of the Gtk clipboard is requested. 

I will close this bug as it is not a Frescobaldi bug.

**Comment by lukaszmb** [comment]
It's true, this is a not Frescobaldi bug.
Python script unfortunately does not work with the Frescobaldi.
Also text writing does not work, may use another script language will work?
I don't know...

**Comment by wbsoft** [comment]
Do you use autokey in Qt mode or Gtk mode? Maybe that makes a difference.
