### ISSUE TITLE
Python path problem running musicxml2ly on OS X?

### ISSUE THREAD

**Issue by Michael-F-Ellis** [wbsoft/frescobaldi#589]
Just installed 2.17.2 on OS X  10.9.5.  First experience with Frescobaldi (but lots of LilyPond experience).  Very impressed with ease of installation and ease of use.  Ran into the following error trying to import MusicXML files.  Happens with externally created xml and with xml exported from Frescobaldi.   Looks like a simple path issue but I can't find any place in the configuration to specify paths for python scripts.

**The file couldn't be converted. Error message:
musicxml2ly: Reading MusicXML from /Users/mellis/Desktop/Bwv228/Bwv228.xml ...
Traceback (most recent call last):
  File "/Applications/LilyPond.app/Contents/Resources/bin/musicxml2ly", line 2986, in <module>
    main()
  File "/Applications/LilyPond.app/Contents/Resources/bin/musicxml2ly", line 2981, in main
    voices = convert (filename, options)
  File "/Applications/LilyPond.app/Contents/Resources/bin/musicxml2ly", line 2882, in convert
    tree = read_musicxml (filename, options.compressed, options.use_lxml)
  File "/Applications/LilyPond.app/Contents/Resources/bin/musicxml2ly", line 2873, in read_musicxml
    return read_xml (io_object, use_lxml)
  File "/Applications/LilyPond.app/Contents/Resources/bin/musicxml2ly", line 2824, in read_xml
    from xml.dom import minidom, Node
ImportError: No module named dom**

I've verified that xml.dom is present by successfully importing it in iPython.  FWIW, I'm running Python 2.7.6 in a Canopy 1.4.1 virtual environment.

**Comment by Michael-F-Ellis** [comment]
Forgot to mention that musicxml2ly runs without error from a terminal.

**Comment by wbsoft** [comment]
Thanks for reporting. This looks like a path issue. How did you install Frescobaldi? Maybe @dliessi can help here, he has created the Mac OS X packages. Probably the wrong Python (the one contained in the Frescobaldi package) is called.

**Comment by dliessi** [comment]
> Probably the wrong Python (the one contained in the Frescobaldi package) is called.

You're probably right. I'll look into this later.

**Comment by Michael-F-Ellis** [comment]
I installed by dragging from the .dmg to the applications directory.

**Comment by Michael-F-Ellis** [comment]
Possibly unrelated, but when I try to start frescobaldi from a command
line, I get

*Michaels-Mac-mini:Bwv228 mellis$ frescobaldi Chor1_Soprano.ly *

*Traceback (most recent call last):*

*  File "/Users/mellis/bin/frescobaldi", line 2, in <module>*

*    import frescobaldi_app.main*

*ImportError: No module named frescobaldi_app.main*


The GUI, of course, starts without error.

Thanks very much for responding so quickly to my initial report and let me
say again how very impressed I am with the design choices and
implementation for Frescobaldi.

Cheers,
Mike

**Comment by dliessi** [comment]
As you say, it is probably unrelated.
Anyway, how did you install `/Users/mellis/bin/frescobaldi`?

**Comment by Michael-F-Ellis** [comment]
Definitely unrelated.  The file is dated 2011.  I recall now that I tried
to install Frescobaldi in its early days but gave up because of problems
installing Qt on OS X.

Thought I had long since gotten all the macports cruft out of my system ...

Cheers,
Mike

**Comment by dliessi** [comment]
Apparently neither the Python contained in Frescobaldi.app nor the one in LilyPond.app contain all the modules needed to run the Python scripts included in LilyPond.
I'll change Frescobaldi so it picks up the system Python to run those scripts.

**Comment by dliessi** [comment]
I think I fixed it.
I need a few more tests and then I'll be able to upload the fix.

**Comment by dliessi** [comment]
I believe the problem is now fixed.
@wbsoft before issuing a bugfix release, I'd like some other Mac users to test the changes.
I'll build a new disk image later: @PaulMorris, @philmassart would you be so kind to test convert-ly and the importers if I give you a link to download the DMG?

**Comment by philmassart** [comment]
Of course. I'll test it and send you comments

**Comment by wbsoft** [comment]
Yes lets make 2.18.1 in a week or so.

**Comment by PaulMorris** [comment]
That was fast!  I’d be glad to test it.  Thanks again for all your work on this!  

(BTW, I renamed and kept the previous version of Frescobaldi before installing the new one, so this hasn’t inconvenienced me.  I can just use the previous version when I need convert-ly, until the fix is out. )

**Comment by PeterBjuhr** [comment]
@PaulMorris are you saying that this issue didn't affect convert-ly in the previous version, or is it an older version?

**Comment by dliessi** [comment]
Yes, convert-ly worked also with the Python interpreter bundled with Frescobaldi (previous behaviour of the standalone application bundle).
The previous issue affected the LilyPond tools that imported modules not bundled with Frescobaldi.
The new issue was caused by the system Python interpreter looking for modules in the wrong places, not finding any compatible module, so it affected all LilyPond tools.

**Comment by PeterBjuhr** [comment]
I see, thanks for clarifying!

**Comment by dliessi** [comment]
@PaulMorris, @philmassart: [here](https://www.dropbox.com/s/0p9p6fv5fwryot9/Frescobaldi-2.18-20150309-x86_64.dmg?dl=0) you can find the updated DMG (SHA256 checksum `f0e5a5014a8e3818efc37b116ecbacafb98414124fe60bd3a746b53c5341f328`).
Please test and report about convert-ly and the importers (ABC, MIDI, MusicXML).

**Comment by PaulMorris** [comment]
I downloaded and installed, and still got errors, as follows:

IMPORT ABC:

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 143, in importAbc
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 153, in openAbcDialog
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/__init__.py", line 161, in runImport
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/file_import/abc.py", line 91, in run_command
IOError: [Errno 2] No such file or directory: u'/var/folders/x0/800486lw8xj7t90059bpdlb00000gn/T/frescobaldi-e3xQQ0/tmpmkWRMK/-'


CONVERT-LY

'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/Applications/LilyPond.app/Contents/Resources/bin/convert-ly", line 24, in <module>
    import os
ImportError: No module named os


The document has not been changed.

**Comment by philmassart** [comment]
I used the 64bits version. Imports worked for me, convert-ly too.

**Comment by PeterBjuhr** [comment]
I also did a quick test, and everything worked fine.

@PaulMorris you didn't accidentally run an older version (you got the old IOError again in the ABC import)?

**Comment by dliessi** [comment]
> @PaulMorris you didn't accidentally run an older version (you got the old IOError again in the ABC import)?

@PeterBjuhr: I was about to write the same thing: while I might not have solved the ImportError yet, I'm pretty sure the ABC IOError cannot happen after your latest commit 5edbf6493ef9bde8105e0b277def1bbe9d291878. :)

**Comment by PaulMorris** [comment]
> @PaulMorris <https://github.com/PaulMorris> you didn't accidentally run an older version (you got the old IOError again in the ABC import)?
> 
Yes, I must have… not sure how… sorry about that!

Today I deleted and reinstalled and now everything is working fine.  I checked abc, musicxml, and midi imports, and convert-ly.
