### ISSUE TITLE
proposed project restructuring

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#592]
I am very happy that now multiple codevelopers help bringing Frescobaldi forward. Also it is desired that python-ly becomes visible and is further developed on its own. To reflect this, and to make some development paths easier, I propopse some changes to how Frescobaldi is structured:

* make `python-ly` a separate package and have Frescobaldi depend on it (can be done as of 2.18)
* (later) make `qpopplerview` a separate package and have Frescobaldi depend on it
* (much later, e.g. next year, or when Frescobaldi supports Qt5 and reaches version 3.0) make a GitHub organisation (named "frescobaldi") and add python-ly and frescobaldi to that organisation.

What do co-developers think?

**Comment by uliska** [comment]
That makes very much sense to me.

While we're at it I would like to add one more thought to that (which I've already expressed earlier but which seems to be related here). I would really like to have one more entity, namely a `frescobaldi-lib` with LilyPond code. For example the code in `layoutcontrol` should be moved there but we could add more material to it.  
This would make it possible to add features to Frescobaldi that rely on LilyPond code being present - without making documents depend on being compiled with Frescobaldi (if someone wants to share documents with non-Frescobaldi users they can be directed to get that library).

I would really like to see such a thing, for example to add support for the `ScholarLY` package that I have just created (and will present on Scores of Beauty soon), in particular I'd like to have an annotation editor in Frescobaldi.

**Comment by wbsoft** [comment]
@uliska, isn't it an idea to add such lilypond code to a library in the openlilylib project. If it is LilyPond code that should also be available to users of other editors, it is not needed (I think) to call that library frescobaldi-lib, as that suggests one can't use that library outside Frescobaldi.

We should give that library of LIlyPond code a generic name and we could add features that use that library to Frescobaldi, and also add a feature to Frescobaldi to automatically install or update the library (just like I want Frescobaldi to be able to install LilyPond and its documentation transparently in multiple versions). Frescobaldi should be able to work perfectly without that library, but some features would be greyed out and an easy way to install the library should be there.

As far as I can see, openlilylib could be a good place for such a library. Please let me know what you think.

**Comment by uliska** [comment]
> @uliska <https://github.com/uliska>, isn't it an idea to add such 
> lilypond code to a library in the openlilylib project.
>

Hm, maybe. I've thought of this too, but see below.

> If it is LilyPond code that should also be available to users of other 
> editors, it is not needed (I think) to call that library 
> frescobaldi-lib, as that suggests one can't use that library outside 
> Frescobaldi.
>

OK. Maybe true but this could be dealt with through clever naming and 
proper advertisment.

> We should give that library of LIlyPond code a generic name and we 
> could add features that use that library to Frescobaldi, and also add 
> a feature to Frescobaldi to automatically install or update the 
> library (just like I want Frescobaldi to be able to install LilyPond 
> and its documentation transparently in multiple versions). Frescobaldi 
> should be able to work perfectly without that library, but some 
> features would be greyed out and an easy way to install the library 
> should be there.
>

That's exactly how I'd suggested to integrate such extensions. One could 
make a Preference that enables support for such features and where one 
can either "install" the library or specify the path to it if one 
already has it.

> As far as I can see, openlilylib could be a good place for such a 
> library. Please let me know what you think.
>

I'm not completely sure about that. In principle this should be true but 
openLilyLib has turned into a rather fluid and inconsistent mass of 
code. Basically it's as unstructured as the LSR, with the main 
differences that it is *includable* and has a better contribution 
interface. I'm not sure if we can consider this stable enough to be used 
in such a way as a library for an application.

I think when we want to have an application rely on a library we should 
be rather strict about how stable it is. Apart from that I find the idea 
quite charming to add "openLilyLib support" to Frescobaldi. This could 
also be used in Snippets, and for more tools (e.g. adding code 
completion for selected functions).
One compromise I can see would be to have a `frescobaldi` directory in 
openLilyLib and add the rule that this should not be randomly modified.

**Comment by uliska** [comment]
> One compromise I can see would be to have a `frescobaldi` directory in
openLilyLib and add the rule that this should not be randomly modified.

Or maybe we could create a "sister project" at github.com/openliyllib/editing-tools? This could be focused on tools that support editing (e.g. the edition-engraver, and maybe more. One more important aspect may be the curve shaping tools) and be developed in a somewhat more controlled manner.

**Comment by wbsoft** [comment]
That's a nice idea: making editing-tools a well-defined set.

**Comment by wbsoft** [comment]
Snippets could also integrate/interface with external snippet librar(y|ies).

**Comment by PaulMorris** [comment]
Just to weigh in with another point of view...  

Sister project idea: Do you want to fork openLilyLib so that there are two libraries that users have to install and juggle?  ("Now which library was that code in?")  Would the two libraries have duplicate code or not?

Frescobaldi directory: do you want to mix two different typologies into the directory structure: what the snippets do and whether they are integrated in Frescobaldi or not?

openLilyLib already has a mechanism for indicating the quality/robustness of the snippets, and a way to tag the snippets that would be integrated with Frescobaldi (identifying them as needing more editorial control).  What about using these (and improving or expanding on them as needed) rather than using a separate directory or library?  Would there be a way to "extract" only the snippets with a given tag or level of code quality?

Urs, this also raises the topic of the reorganization of openLilyLib that you were working on last summer.  What are the current plans for that?

In any case, it's great to see the continued development of Frescobaldi.  Thanks to everyone for all your efforts!

**Comment by uliska** [comment]
Am 23.01.2015 um 14:59 schrieb PaulMorris:
>
> Just to weigh in with another point of view...
>
> Sister project idea: Do you want to fork openLilyLib so that there are 
> two libraries that users have to install and juggle? ("Now which 
> library was that code in?") Would the two libraries have duplicate 
> code or not?
>

Definitely not. *If* we'd go that way we would *move* code from 
openLilyLib to a sister library.

> Frescobaldi directory: do you want to mix two different typologies 
> into the directory structure: what the snippets do and whether they 
> are integrated in Frescobaldi or not?
>

Well, I'd prefer having a separate library, so that would be obsolete. 
However, the directory structure in OLL is quite obscure anyway ...

> openLilyLib already has a mechanism for indicating the 
> quality/robustness of the snippets, and a way to tag the snippets that 
> would be integrated with Frescobaldi (identifying them as needing more 
> editorial control). What about using these (and improving or expanding 
> on them as needed) rather than using a separate directory or library? 
> Would there be a way to "extract" only the snippets with a given tag 
> or level of code quality?
>

This sounds like a good idea. We'd have to think through it and discuss 
that.

> Urs, this also raises the topic of the reorganization of openLilyLib 
> that you were working on last summer. What are the current plans for that?
>

Well, the "current plans" are: pick that up as soon as possible and hope 
that the work already been done can still be used. But work on the big 
Fried score prevented me continuing on the track, therefore it is 
somewhat stalled.
But it would of course make sense to restart that effort - and integrate 
this new Frescobaldi idea into the considerations.

**Comment by wbsoft** [comment]
First part of first step is done! python-ly is now a separate github project. I added all the Frescobaldi collaborators! https://github.com/wbsoft/python-ly

**Comment by uliska** [comment]
> First part of first step is done! python-ly is now a separate github 
> project. I added all the Frescobaldi collaborators! 
> https://github.com/wbsoft/python-ly
>
>

Thank you. What do we have to do to keep it running? Of course cloing 
python-ly, but more?

**Comment by wbsoft** [comment]
Now python-ly is an independent package. As soon as ly is removed from frescobaldi_app, it should be installed before Frescobaldi can be used. For the freeze packages (dmg, windows etc), the ly package should be listed in the modules to import.

We can develop python-ly further and it will probably have many releases.

**Comment by uliska** [comment]
But we can use python-ly through the Git repo, or do we have to install and always update it?

**Comment by wbsoft** [comment]
that's a good question. We should be able to run it from a cloned repo.

**Comment by proski** [comment]
No objections on my part. I think python-ly and qpopplerview can be made frescobaldi dependencies once they have a stable API, documentation and a test suite.

**Comment by PeterBjuhr** [comment]
Nice ideas here! 

One reflection on the library with Lilypond code: If that library shouldn't be a real dependency but somewhat optional, and Frescobaldi should be able to work perfectly without that library - the idea is to my mind very similar to a library included with the include paths in the Lilypond preferences. 

Maybe we could have include paths that are included by default but excluded if not present. One such example could be the lilypond code needed for the Layout control options. (By the way, it seems to me very obvious that those files shouldn't have their home inside Frescobaldi as they could be used more generically...)

**Comment by proski** [comment]
Urs,

If you don't want to install python-ly, define PYTHONPATH environment
variable to the python-ly repository (make sure "ly" in the subdirectory of
that directory).

Pavel
​

**Comment by proski** [comment]
How would installation on Windows and MacOS affected? Something to
think about and test.

Pavel

**Comment by uliska** [comment]
Am 23.01.2015 um 22:35 schrieb Peter Bjuhr:
>
> Nice ideas here!
>
> One reflection on the library with Lilypond code: If that library 
> shouldn't be a real dependency but somewhat optional, and Frescobaldi 
> should be able to work perfectly without that library - the idea is to 
> my mind very similar to a library included with the include paths in 
> the Lilypond preferences.
>

Yes, definitely. It is about making LilyPond code available to LiylPond.

> Maybe we could have include paths that are included by default but 
> excluded if not present.
>

I don't think it is a good idea to expect specific paths.
I think a better approach would be modeled after the "helper 
applications" preferences. That is: Provide a field for a library, and 
if the user fills this library is considered present.
As we are thinking about creating specifications and a general 
infrastructure for libraries we might as well consider supporting not 
only one single library in Frescobaldi.

> One such example could be the lilypond code needed for the Layout 
> control options. (By the way, it seems to me very obvious that those 
> files shouldn't have their home inside Frescobaldi as they could be 
> used more generically...)
>

Actually the files are in openLilyLib too. And I think that's a major 
problem keeping them in sync. So yes, I agree with you.

**Comment by PeterBjuhr** [comment]
>>Maybe we could have include paths that are included by default but
 excluded if not present.

>I don't think it is a good idea to expect specific paths.

Perhaps not, I just wanted to find a way to get a closer connection to includes that is somehow anticipated by Frescobaldi.

>I think a better approach would be modeled after the "helper
applications" preferences. That is: Provide a field for a library, and
if the user fills this library is considered present.

This is actually pretty close to my idea, because the helper applications settings have also defaults - albeit set by the os.

>As we are thinking about creating specifications and a general
infrastructure for libraries we might as well consider supporting not
only one single library in Frescobaldi.

If we take the example of the layout control again, you mean that Frescobaldi should be able to support different libraries doing layout control stuff!? That is of course a nice idea! But we'd need more API-like structure to achieve that...

**Comment by uliska** [comment]
>
>>As we are thinking about creating specifications and a general
>infrastructure for libraries we might as well consider supporting not
>only one single library in Frescobaldi.
>
>If we take the example of the layout control again, you mean that
>Frescobaldi should be able to support different libraries doing layout
>control stuff!? That is of course a nice idea! But we'd need more
>API-like structure to achieve that...
>

I mean: I've just set up a repository ScholarLY which contains material that I'd like Frescobaldi to use. Layout control is in (or should be moved back to) openLilyLib.  There may emerge further libraries supporting e.g. contemporary or ancient notation.
If we had a nice interface we could add support for such libraries (and if only for syntax highlighting and autocompletion*). Similar to the current "experimental" switch functionality could be enabled or not according to the presence of the libraries.

* Part of my ideas regarding a library infrastructure is developing an auto-documentation system like javadoc. Frescobaldi could use such a system to collect autocompletion data.

**Comment by PeterBjuhr** [comment]
Sorry for the misunderstanding!

I like the auto-documentation idea!

**Comment by PaulMorris** [comment]
> On Jan 23, 2015, at 9:08 AM, Urs Liska <notifications@github.com> wrote:
> 
> Well, the "current plans" are: pick that up as soon as possible and hope 
> that the work already been done can still be used. But work on the big 
> Fried score prevented me continuing on the track, therefore it is 
> somewhat stalled.
> But it would of course make sense to restart that effort - and integrate 
> this new Frescobaldi idea into the considerations.

Sounds good.  I had assumed that the Fried work had taken priority.

**Comment by PeterBjuhr** [comment]
One small idea: 

If I'm correct, instead of working with `PYTHONPATH` from the command line we could add the following to `debug.py`:

    sys.path.append(os.path.realpath('../python-ly'))

This would of course imply a certain file structure where python-ly and frescobaldi are next to each other in a directory.

**Comment by PeterBjuhr** [comment]
Did a quick test. It seems to work as expected. But if `python.ly` is already installed you can't use append. You have to put it at the start of `sys.path` (as using PYTHONPATH does).

I'm still not sure if this is a good idea though!? Should I just set up my own debug script or could this be useful for all developers/debuggers??

**Comment by dliessi** [comment]
> What do co-developers think?

I think this is all very nice.

> (much later, e.g. next year, or when Frescobaldi supports Qt5 and reaches version 3.0) make a GitHub organisation (named "frescobaldi") and add python-ly and frescobaldi to that organisation.

@wbsoft Why do you want to wait before creating the organization?

**Comment by dliessi** [comment]
I like the ideas about libraries very much:

> If we had a nice interface we could add support for such libraries (and if only for syntax highlighting and autocompletion*). Similar to the current "experimental" switch functionality could be enabled or not according to the presence of the libraries.

+1

We could add a customizable list in the preferences (something like the list of available LilyPond copies) and add the configured libraries in the specified order at the end of the include path.
There should be checkboxes to enable or disable the libraries in the sessions (no need to customize the paths in the sessions, in my opinion).

**Comment by dliessi** [comment]
> How would installation on Windows and MacOS affected?

@proski As @wbsoft said, we just need to add the `python-ly` package to the list of dependencies in the freeze scripts; actually only in the Windows freeze script: I'm fairly sure that the Mac script would pick it up automatically, as it does with all other dependencies.

**Comment by dliessi** [comment]
> I'm still not sure if this is a good idea though!?

I think it is indeed a good idea.

> But if python.ly is already installed you can't use append. You have to put it at the start of sys.path (as using PYTHONPATH does).

I did the same in `macosx/mac-app.py`: I used to append the path of the root of the repository to `sys.path`, but then I found out that I needed it in front of `sys.path`.
`sys.path.insert(0, os.path.realpath('../python-ly'))` should do what you want.

**Comment by PeterBjuhr** [comment]
>I think it is indeed a good idea.

Then I prepare a pull request!

**Comment by wbsoft** [comment]
> @wbsoft Why do you want to wait before creating the organization?

I think communicating the new github url (when we have created the organisation) is easier when we can make a lot of noise for 3.0.

**Comment by wbsoft** [comment]
Just fyi, I wrote this to the frescobaldi mailing list at google groups:

> This message is to all people that like to run Frescobaldi from a Git checkout and test or help develop new features.
> 
> The python module 'ly', which collects all the crucial LilyPond format parsing and manipulation has moved out of Frescobaldi and has become a standalone package.
>
> This package is called 'python-ly' and can be downloaded via the Python Package Index[1] or cloned using git[2].
> 
> [1] https://pypi.python.org/pypi/python-ly
> [2] https://github.com/wbsoft/python-ly
> 
> When testing, it is best to have Git checkouts for both python-ly and frescobaldi next to each other in a directory.
> 
> Then you can test Frescobaldi from git using python-ly from git using:
> ```
> $ PYTHONPATH="../python-ly" python frescobaldi
> ```
> or, when you want to test with Python 3:
> ```
> $ PYTHONPATH="../python-ly" python3 frescobaldi
> ```
> Issues that are clearly in the ly module can be reported in the python-ly issue tracker[3].
> 
> [3] https://github.com/wbsoft/python-ly/issues
> 
> Now python-ly is a separate package, it can be developed quicker and released more often, and get it's own test suite, so that it becomes more robust and powerful. Also it can be used by other applications in the future.

**Comment by uliska** [comment]
I think I will set up a new repository `edition-tools` and do the following:

- copy/move the code for `layoutcontrol` there
- copy/move the `edition-engraver` from `openlilylib` there
- add my code for partial compilation and optional line/page breaking

Then we'll see how it works out.

Just one question:  
Is it acceptable if such a library depends on another, concretely `openLilyLib` or should we require a usable library to be self-contained? Of course it can create secondary complications if we implicitly rely on secondary repositories, but OTOH this would make the libraries cleaner. 
For example: I currently have a function in my `\annotate` library that calculates properties of the rhythmic location of a grob. The same functionality will be necessary for determining the breaks in a score, and it may be a valuable function on its own. So I would like to move that to openLilyLib where it conceptually belongs.

If allowing arbitrary library dependencies seems too obscure we could make a compromise and allow libraries to require openLilyLib exclusively, which would then be no. 1 on our to-be-created list of supported libraries.

**Comment by proski** [comment]
@uliska , maybe you could start a new issue and provide more background? Separation of python-ly was a good idea, but if Frescobaldi goes to the state when it needs 4-5 obscure dependencies not carried by major distros, we could start losing users, at least those who want to try Frescobaldi from the sources.

edition-tools sounds like a bad name to me. The name gives no indication of what the code does except that it's some tools to deal with some varying code.

**Comment by PeterBjuhr** [comment]
>Separation of python-ly was a good idea, but if Frescobaldi goes to the state when it needs 4-5 obscure dependencies not carried by major distros, we could start losing users, at least those who want to try Frescobaldi from the sources.

I agree, but wasn't the idea that it shouldn't be real dependencies - the functionality should be somehow optional!? We've touched upon the idea of adding this as plugins (I think). The current Snippets API is a kind of plugin API, but I don't know if it's sufficient. If it is, the functionality could be provided as snippets.

I also agree we can discuss things further in a new issue (but I throw in this comment in the meantime :); this can be closed. The first major restructuring is done and we can discuss further separation in separate issues.

**Comment by wbsoft** [comment]
The layout control is so nice, let's keep that in Frescobaldi. It also has a very clear goal.

In the near future nice LilyPond related tools/libraries such as scholarly etc (I did not yet work with them) should first get use without special changes to Frescobaldi (apart from letting a user specify include paths). When such tools/libraries become very pervasively used then we can add support to Frescobaldi. This way we keep Frescobaldi development separate from other tools, Frescobaldi should just support the stable, documented LilyPond.

**Comment by wbsoft** [comment]
> The current Snippets API is a kind of plugin API, but I don't know if it's sufficient. If it is, the functionality could be provided as snippets.

That's a good idea. In the snippet rethinking there's room for thoughts about extension modules that are more than a snippet. Also in that area, it is possible to dedicate and document a stable part of Frescobaldi's api to use for snippets/scripts/extensions.

I'll close this issue.

**Comment by uliska** [comment]
> When such tools/libraries become very pervasively used then we can add support to Frescobaldi. This way we keep Frescobaldi development separate from other tools, Frescobaldi should just support the stable, documented LilyPond.

There is some more to that, but as @proski suggests I'll open a new issue for this discussion
