### ISSUE TITLE
Duplicate Page.image() in frescobaldi_app/qpopplerview/page.py

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#593]
Class Page in frescobaldi_app/qpopplerview/page.py has two methods called image().

The first image():
Newer - introduced 2014-04-01 by commit 376956e6, puzzlingly referring to issue 406.
Takes no arguments.
Refers to Qt.SmoothTransformation without a proper input.
Appears to be unused.

The second image():
Older - last changed 2012-04-07 by commit 35483678.
Takes four arguments.
No errors reported by pylint.
Used at frescobaldi_app/musicview/image.py:192

Should the first image() be removed?

**Comment by wbsoft** [comment]
Indeed the first one can be removed!

**Comment by proski** [comment]
Done.
