### ISSUE TITLE
Layout control opens SVG view and Midi player

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#594]
I haven't yet tried the Layout control as much as I'd want. But when I now get a quick glance I experience some oddities. When I use the engrave option with Layout control the SVG view and the Midi player pops up.

To clarify, the engraving process does create a pdf-file, but there's a previously engraved svg-file associated which gets focus. Regarding the midi player the situation is dissimilar; there isn't any midi-file associated and the player is empty.

**Comment by wbsoft** [comment]
ok, will sort this out, thanks for reporting!

**Comment by PeterBjuhr** [comment]
I was mistaken in thinking it had anything to do with the layout control. The same thing occurs when using ordinary engrave (preview). I just confirmed this on current master.

**Comment by wbsoft** [comment]
I see, I test for files that are newer than the source document, but those files are not necessarily created by the last run. I should only look for files that have mtime >= the time the job was started....

**Comment by PeterBjuhr** [comment]
Thanks, that fixed it! :)

**Comment by PeterBjuhr** [comment]
The midi player does still pop up on first compile. And I saw from the comment in the commit above that it's intended. 

I guess the behavior was introduced in this commit: dba89bbc91c57e1fe8611b73cf59dc186da16145 It's related to the setting "Open default viewer after successful compile" in the LilyPond Preferences. But should the midi player be included in this?

If I may report my preference as a user I'd say that I prefer to always open the midi player manually but to have the score viewer (pdf or svg) open automatically after a compilation.

**Comment by uliska** [comment]
To add to that, I prefer to never have the Midi player open at all, so 
I'm rather annoyed with it popping up automatically.

**Comment by PeterBjuhr** [comment]
Thanks!

**Comment by proski** [comment]
I agree that the MIDI player popping up is not a good idea. Most of the time (unless it's a trivial warmup exercise), I run Lilypond to see who the score looks, not how the music sounds. If the MIDI player and the PDF viewer were closed, it means I was working with a large score and I want to *see* the result first. Then maybe listen to it or (more likely) edit the source further.

Thanks for fixing it!
