### ISSUE TITLE
Export Audio needs improvement

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#596]
Export Audio (wav) uses os.system(). There are several problems with it.

The output from Timidity is written to stdout. That's ugly.
os.system() is considered unsafe.
It may fail for files with non-latin characters under Python 3.
The conversion takes a long time, but there is no feedback.

**Comment by wbsoft** [comment]
It should be handled using a QProcess (a little helper module `process` is there that is also used by `lilypondinfo`, to run LilyPond async and get some information).

It could (and probably should) be done using `job`.Job, a more powerful thing that runs a process and can gather different types of log output, and write that to a log. Job is used by the musicpreview in the score wizard and also by the main engraver.

**Comment by proski** [comment]
Fixed by 115f4bed05ec610bc4abf4254e8e0bde849662de
