### ISSUE TITLE
Distribution of Snippets

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#602]
Related issues: #599 #509 #6

Coming from the discussion of external libraries I like to investigate how Snippets can better handle Python extensions. I concluded that Snippets wasn't really designed for such an idea, but giving it some more thought I think the major deficiency lies in how the Snippets can be distributed. Presently snippets are imported and exported in the form of XML-files. But if real python files could be imported or perhaps a whole folder I think the idea of adding Python extensions is real close to becoming realizable.

**Comment by uliska** [comment]
Sounds goid.

BTW: are there any security considerations wrt snippts?

**Comment by PeterBjuhr** [comment]
Good and important point of course!

**Comment by wbsoft** [comment]
In issue #599, I proposed that (an architecture for) real Frescobaldi extensions is/are developed. Those can contain datafiles etc. I think the snippets architecture is too limited for that.

**Comment by PeterBjuhr** [comment]
I thought it was interesting to find out how far the current infrastructure could be extended. But I think it's a very good decision! As I've said, I fully appreciate that the Snippets architecture wasn't designed for this kind of stuff.

I close this again!
