### ISSUE TITLE
Need specify package dependencies

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#608]
Now that frescobaldi depends on python-ly it's even more important to specify dependencies of the package in setup.py. Unlike python-poppler-qt4, python-ly is a hard dependency. Frescobaldi won't run without it. As I understand, dependencies can only be specified if setup.py uses setuptools by setting `install_requires`. We may want to use setuptools if it's available and fall back to distutils.

Another benefit of setuptools is that it allows clean uninstall by pip.

Just making sure 2.18 won't be released without fixing it.

**Comment by wbsoft** [comment]
Great! I will also make a clear note about it in the release notes.

**Comment by proski** [comment]
Fixed in 727b29060e2d654c1609754879502edb06befa1a

**Comment by proski** [comment]
By the way, "python setup.py develop" is very cool! And it can be uninstalled by pip, just like a regular install. http://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install
