### ISSUE TITLE
Wish: abc import using abc2ly

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#610]
Wish by a user:

> I have been using frescobaldi for about a year now and am well impressed. 
> Bravo.
> 
> I do a little folk tune composition and arranging and for us folkies there is a huge resource of tunes in abc format.
> 
> Now abc2ly is very helpful but it would be nice not to have to drop out of the ide.
> 
> Any chance of an import function to load an abc file and convert it straight into frescobaldi?

**Comment by PeterBjuhr** [comment]
abc2ly doesn't have as many options as musicxml2ly, apart from that the import is identical (from the user's perspective) as I understand it.  We could create a dialog for an abc import in analogy with the present musicXML import. And much of the code could be reused, I think.

**Comment by wbsoft** [comment]
We could even use a generic import dialog and subclass that for musicxml, midi2ly and abc2ly.

**Comment by PeterBjuhr** [comment]
Good idea. Midi2ly import should also be added.

**Comment by wbsoft** [comment]
Great!

**Comment by PeterBjuhr** [comment]
About abc2ly, the following can be read in the latest LilyPond documentation:

>Note: This program is not supported, and may be remove[d] from future versions of LilyPond.

http://www.lilypond.org/doc/v2.19/Documentation/usage/invoking-abc2ly

**Comment by proski** [comment]
I don't think ABC support would be dropped. If it's dropped, Frescobaldi (or perhaps python-ly) could pick it up. ABC is prominent enough to have a Wikipedia page. It doesn't sound like an abandoned standard.
https://en.wikipedia.org/wiki/ABC_notation

**Comment by PeterBjuhr** [comment]
I agree, and I like to add that ABC could be a considerable path in to LilyPond because of the similarities. The similarities does also mean that if we do need to pick it up it would be comparably straight-forward, I think.

A generic import dialog including the addition of abc2ly support as mentioned above was implemented, so I'm closing this now.

**Comment by wbsoft** [comment]
Also `mup2ly` has been dropped from LilyPond. Years ago I started writing a new `mup2ly` script. I already finished the macro handling, and when I have some time, I will finish it further.

I think when LilyPond drops such tools we could add this to python-ly.
