### ISSUE TITLE
LilyPond tools: customizable or hard-coded?

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#619]
I noticed that some LilyPond tools are customizable in LilyPond Preferences (namely convert-ly and lilypond-book), while other LilyPond tools are hard-coded (namely musicxml2ly, midi2ly, abc2ly).

I think that there is no reason to treat them differently.
I'm uncertain of which solution I would prefer, though.

**Comment by wbsoft** [comment]
We could move the configuration of these tool commands to a second tab in the LilyPond instance dialog.

**Comment by PeterBjuhr** [comment]
In addition to the difference in the LilyPond preferences, in the convert-ly dialog you can set the LilyPond version to use; which of course is more relevant here. But I guess there could be odd cases where you also would like to change the version for the import tools.  

If there's any interest for it, I could add a similar LilyPond switcher to the new generic import dialog!??

**Comment by wbsoft** [comment]
> If there's any interest for it, I could add a similar LilyPond switcher to the new generic import dialog!?? 

That's a nice idea!

Thinking about import, I did not yet test the new import functions, but we could make a generic File→Import... command that just opens a filedialog. With the default file types Xml, midi, abc. You can select a file, and Frescobaldi determines what filetype it is, and opens the suitable import dialog for it. E.g. when you select a midi file, Frescobaldi displays the midi import dialog. The dialog itself is then not generic, but tailored to the MIDI import (although it could share code and GUI elements with other import dialogs).

Then we can also make dropping MIDI, MusicXML or ABC files on Frescobaldi work, i.e. that the file type is determined and the correct import dialog is displayed.

**Comment by PeterBjuhr** [comment]
Nice! It should be a complement to the specific import commands (in the menu) rather than substituting them, right?

**Comment by PeterBjuhr** [comment]
Before leaving this side-track, I should mention that my mind isn't completely set on what the generic import should look like (and what it should be called). Now it's placed on the top in the submenu and called 'import all'.

I noticed that I rather quickly tended to prefer the generic import, and the thought of removing the other menu commands did pop up. But after some more thought I think they should stay for two reasons:

1. They are clearer for the user who needs to import e. g. an abc file.
2. If for some reason the file extension is different or lacking the file can be imported anyway.

**Comment by proski** [comment]
Another reason - Frescobaldi shows the user its capabilities. Frescobaldi is full of hidden gems that are hard to discover. Let's not hide what it can import and export. I don't expect the list of supported formats to become overwhelmingly long.

`Import all...` looks bad. It's an example of UI overload. `Import...` would be better than `Import all...` Having a menu separator below it would be better. Having a list of importable extensions would make the import dialog better. But with all enhancements, I feel it would still be excessive.

**Comment by PeterBjuhr** [comment]
>Another reason - Frescobaldi shows the user its capabilities. Frescobaldi is full of hidden gems that are hard to discover. Let's not hide what it can import and export. I don't expect the list of supported formats to become overwhelmingly long.

I agree, it was somewhat implied by my first point but I didn't state it clearly.

>Import all... looks bad. It's an example of UI overload. Import... would be better than Import all... 

Yes, I'm not pleased with that label...

> Having a menu separator below it would be better. Having a list of importable extensions would make the import dialog better. But with all enhancements, I feel it would still be excessive.

That was added by @wbsoft just a short while before you commented... :) (Or does my timeline fool me?)

**Comment by wbsoft** [comment]
Indeed, I was first :-) And I was also tempted to change "Import all..." to "Import...", and will do it :-)

**Comment by PeterBjuhr** [comment]
Drag and drop import now supported.

I also enabled the (generic) import to open multiple files (of different file types), which makes it a more powerful tool and hence less redundant.

**Comment by wbsoft** [comment]
LilyPond tools are now all customizable. In normal cases this needs not to be edited, so I moved those to a secondary tab.
