### ISSUE TITLE
Status of macosx.is_osx() function

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#620]
@wbsoft If we are indeed never going to use macosx.is_osx() (see the comments in commit 4be2e30f64a80bde2bd1a1e863c9308dc59330b7), I'd like to remove that function definition.
Do you agree?

We could add the preferred way to test the OS (not only Mac) in README-development, Coding Style.

**Comment by dliessi** [comment]
We currently have at least occurences of `sys.platform == 'darwin'`, `sys.platform.startswith('darwin')`, `sys.platform.startswith('win')`, `os.name == "nt"`, `os.name != "posix"` and the use of `sys.platform` to select the name of the portmidi and porttime libraries.

**Comment by wbsoft** [comment]
> If we are indeed never going to use macosx.is_osx() I'd like to remove that function definition. Do you agree?
Agree!
> We could add the preferred way to test the OS (not only Mac) in README-development, Coding Style.
Will do.
