### ISSUE TITLE
abc2ly doesn't fit in the generic import structure hence abc import doesn't work properly

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#621]
As I haven't found any quick solution for this it's best to document it as an issue.

When you use musicxml2ly and midi2ly you can write the output to stdout by the use of this option:

    --output=-

For abc2ly this doesn't work.

That means that the method of catching the document from stdout can't be applied, unless we find a workaround.

**Comment by PeterBjuhr** [comment]
As I haven't found any quick solution for this it's best to document it as an issue.

When you use musicxml2ly and midi2ly you can write the output to stdout by this command:

    --output=-

For abc2ly this doesn't work.

That means that the method of catching the document from stdout can't be applied unless we find a workaround.

**Comment by PeterBjuhr** [comment]
The alternative as I see it is to let the document be created directly by abc2ly and catch that instead.

Any ideas?

**Comment by wbsoft** [comment]
Maybe run abc2ly in a temp folder and read the generated ly file?
