### ISSUE TITLE
Repeat chord and add articulation via Quick Insert

### ISSUE THREAD

**Issue by DAccord** [wbsoft/frescobaldi#628]
When trying to add articulations/dynamics to selected chords which are repeated with q via Tools - Quick Insert, I found that it doesn't work when no length is appended after q.
E. g.:

    \version "2.18.2"
    violin = \relative c' {
      <c e g>4 q4 q4 q4 |
      q q q q |
    }
    \score {
      \new Staff \violin
      \layout { }
    }

When selecting the first line of the melody and trying to append articulations as described above, it works. However, it doesn't work with the second line.

Frescobaldi: 2.17.2
Python: 2.7.1
Qt: 4.7.2
PyQt4: 4.8.4
sip: 4.12.2
Operating System:
Windows-post2008Server-6.2.9200

**Comment by proski** [comment]
I confirm that the problem exists in the git (2.18-dev) version as well. Thank you for your report!

**Comment by PeterBjuhr** [comment]
I think I've found the problem. @proski can you confirm? The edit was in Python-ly so you need to update that. 

(Make explicit should now also work when using `q`.)

**Comment by proski** [comment]
Yes, it's fixed now. Thank you!

**Comment by PeterBjuhr** [comment]
Thanks! Closing.

**Comment by wbsoft** [comment]
Thanks! I'm sorry that when adding support for `q` in the parser, I forgot to make it work for quick insert etc.
