### ISSUE TITLE
Add articulation via Quick Insert to tuplet

### ISSUE THREAD

**Issue by DAccord** [wbsoft/frescobaldi#631]
When adding an articulation to selected notes in a \tuplet x/y z { } construction, the number z gets the articulation appended as well:

    \version "2.18.2"
    melody = \relative c' {
      \tuplet 3/2 4 { c8 d e f g a a g f e d c }
    }
    \score {
      \new Staff \melody
    }

Select the line with tuplet and add an articulation via Quick Insert to it.
Furthermore, the number z probably gets colored wrong (?).

Frescobaldi: 2.17.2
Python: 2.7.1
Qt: 4.7.2
PyQt4: 4.8.4
sip: 4.12.2
Operating System:
Windows-post2008Server-6.2.9200

**Comment by wbsoft** [comment]
Thanks for reporting

> Furthermore, the number z probably gets colored wrong (?).

It is the duration color.

**Comment by DAccord** [comment]
Wow, very fast reaction.
Thanks for this wonderful software :+1:

**Comment by wbsoft** [comment]
You're welcome :-)
