### ISSUE TITLE
MusicXML trim durations after import and \skip4

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#635]
The MusicXML import option "Trim durations (Make implicit per line)" removes the duration from all \skip commands beside the first in a line. But the skip command (rather then s) requires a explicit duration. So removing the duration will make the resulting ly file erroneous.

**Comment by wbsoft** [comment]
This should be fixed in the `ly.rhythm` module in python-ly. Thanks for reporting!

**Comment by tobik** [comment]
Great :)
Thank you!
