### ISSUE TITLE
setup.py not working with --root directive (Packaging)

### ISSUE THREAD

**Issue by rdoursenaud** [wbsoft/frescobaldi#638]
I'm trying to make the Arch Linux package.
If I run
```python setup.py install --root="test" --optimize=1 ```
I get
```error: install_script 'windows/frescobaldi-wininst.py' not found in scripts```

The normal install without the ```--root``` option works fine.

Any idea of what's triggering this behavior?
Maybe a workaround.
Had no problems with prior versions.

**Comment by dliessi** [comment]
I was about to report the same issue on Mac: the command used in MacPorts
`python2.7 setup.py --no-user-cfg install --prefix=/path/to/prefix --root=/path/to/destroot`
fails with
`error: install_script 'windows/frescobaldi-wininst.py' not found in scripts`.
This used to work with previous versions.

**Comment by proski** [comment]
This is easily reproducible on Ubuntu. `--optimize=1` is not needed. `windows/frescobaldi-wininst.py` comes from `setup.cfg`

`setup.py` only adds `windows/frescobaldi-wininst.py` to the `scripts` list on Windows. An easy fix would be to add it unconditionally. But I hope there is a better way.

**Comment by rdoursenaud** [comment]
For now, I simply patched the setup.cfg to remove windows related lines.
I also hope there's a better way!

**Comment by dliessi** [comment]
This happens if setuptools is used instead of distutils.
I could not find a solution. @wbsoft @proski Any ideas?

> For now, I simply patched the setup.cfg to remove windows related lines.

This is what I also did in MacPorts.

**Comment by wbsoft** [comment]
In previous versions the `frescobaldi-wininst.py` was in the root directory. Now it is in `windows/`. It is added to the scripts-to-install on Windows. It does some magic such as setting shortcuts and file associations. It is not used in the Windows installer, which is made using Inno Setup and has its own setup stuff.

Where is this `--root` option documented and what can I do to fix this?

**Comment by dliessi** [comment]
I confirm that your fix solved the issue.
Indeed moving the options in `setup.py` is probably easier than finding a solution to keep `setup.cfg`.

> In previous versions the `frescobaldi-wininst.py` was in the root directory. Now it is in `windows/`.

In previous versions we were using only distutils.
Before your latest commit 567c8744efef71a553b068065035d730254fa577, installing with distutils worked correctly, installing with setuptools did not.

> Where is this `--root` option documented [...]?

See [`distutils/command/install.py`](https://github.com/python/cpython/blob/master/Lib/distutils/command/install.py), lines 92, 358, 517 and [`distutils/util.py`](https://github.com/python/cpython/blob/master/Lib/distutils/util.py), line 139.
