### ISSUE TITLE
Change/fix #! line in executable Python scripts

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#640]
See https://github.com/wbsoft/frescobaldi/issues/637#issuecomment-78126940 and https://github.com/wbsoft/frescobaldi/issues/637#issuecomment-78131722.

@proski:
> Another idea is to replace /usr/bin/python in executable python scripts with /usr/bin/python3 to make Python 3 the default. But that may be misinterpreted that Python 2 is no longer supported. So it's not a dot release material.

@dliessi:
> Why don't we change it to `/usr/bin/env python` instead?
> That's common practice and ensures that the script is run with the Python interpreter preferred by the user (or by the system administrator), i.e. the first one in the `$PATH`.
> That can still be overridden by explicitly calling the Python interpreter or by placing a symlink to the preferred Python interpreter earlier in the `$PATH`.
>
> ([Here](http://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my) you can find some interesting remarks.)

Independently from what we choose between the above solutions:
> Also, the interpreter in the `#!` line should have an absolute path, see [here](http://unix.stackexchange.com/questions/77512/why-not-use-pathless-shebangs) and [here](http://www.in-ulm.de/~mascheck/various/shebang/4.0BSD_newsys_sys1.c.html).

**Comment by proski** [comment]
I believe it has been decided that the Python 3 interpreter should never be called `python`. So using `env` would not suddenly start running Python 3 for anyone except users who made a link to Python 3 in the `$PATH` and called it `python` in violation of that convention. OK, Frescobaldi developers can do it and see what happens.

I have no objection against the change. Just don't expect too much from it.

**Comment by dliessi** [comment]
> I believe it has been decided that the Python 3 interpreter should never be called `python`.

I didn't know this (in MacPorts I can select the preferred Python version and MacPorts changes the `/opt/local/bin/python` symlink accordingly).

Ok, in that case we have three issues here, actually:
* the `#!` line should contain an absolute path,
* (in my opinion) it is better to use `/usr/bin/env python` or `/usr/bin/env python3` instead of hard-coding the interpreter,
* now that Python 3 is the recommended version to run Frescobaldi we could/should change from `python` to `python3`.

I think that the first two are harmless enough that they can be done before 2.18.1 (if nobody objects I'll do this tomorrow).
As for the third one, I would have no objections to do the change before 2.18.1, but I may have overlooked some of the implications.

@wbsoft: what do you think?

**Comment by proski** [comment]
It turns out I was wrong. PEP-394 acknowledges that python may point to Python 3:
https://www.python.org/dev/peps/pep-0394/

**Comment by wbsoft** [comment]
The shebang line is automatically changed on install (build) to point to the interpreter that is used to build/install. If you use:

```
python3 setup.py install
```

then the shebang line will point to `/usr/bin/python3`

**Comment by dliessi** [comment]
After reading PEP-394, since at the moment we keep source compatibility between Python 2.7 and Python 3, I think that we should keep `python` for the time being.
I'll change all shebang lines to `#!/usr/bin/env python` tomorrow, and I'll close the issue, unless there are objections.

> The shebang line is automatically changed on install (build) to point to the interpreter that is used to build/install.

Indeed. The shebang line is important when you run Frescobaldi from source.

**Comment by dliessi** [comment]
Solved in 0616473cec8aec3855446174c1ff8b3a5c1c6300, see https://github.com/wbsoft/frescobaldi/pull/658#issuecomment-80876449.
