### ISSUE TITLE
Wrong encoding in Score Wizard with Russian locale

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#641]
See https://github.com/wbsoft/frescobaldi/issues/637#issuecomment-78126940.

@proski:
> Some messages are shown in a wrong encoding when doing preview in Score Wizard in the Russian locale. But the problem is trivial, and the complete fix is not (in involves changing the default encoder in job.py from latin1 to utf-8). An override just for Score Wizard is probably not worth the trouble.

**Comment by proski** [comment]
Other non-ASCII locales are affected as well. Fixed in commit 671e5d403899734f73ef783fad860df60dc2ce49
