### ISSUE TITLE
Icon missing in "Close" button on some Windows systems

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#643]
Reported by @proski in https://github.com/wbsoft/frescobaldi/issues/637#issuecomment-78126940:

> The "Close" icon in the toolbar is shown as button with the text "Close" and without an icon on some Windows systems. I didn't have time to investigate. In any case, I think the "Close" button is not very useful and could be removed from the toolbar. That could be done for 2.18.1.

**Comment by proski** [comment]
The "Close" button was added by commit 62d91949b6a8675dc5c1b416c5cb1fc1663892d3 that can be reverted manually. That is, remove `t.addAction(ac.file_close)`
The icon should be preserved for the menu.

**Comment by wbsoft** [comment]
The close icon is indeed not very important in the toolbar. But first it'd be good if we could find out why the icon doesn't show up in the toolbar on some systems.

**Comment by PeterBjuhr** [comment]
On Ubuntu I can't see the icon. I normally use Tango's icons theme, but even when I switch to the default theme the icon isn't shown.

(On OS X the icon is visible.)

**Comment by PeterBjuhr** [comment]
The solution was very easy. I simply unselected 'Use System Icons' in the general preferences. And I now see all the icons extending the Tango library.

If I understand it correctly 'Use System Icons' is selected by default. Maybe that can help explaining this issue!?

**Comment by wbsoft** [comment]
Aha, thanks for investigating. Yes. I'll try to change it so that, even when system icons are preferred, when there is no system icon, and no icon directly in the icons/ dir, the TangoExt and Tango folders are searched.

**Comment by PeterBjuhr** [comment]
I confirm that I now can see the extending icons also with 'Use System Icons' enabled!

**Comment by proski** [comment]
OK, let's leave the Close button for now. Thank you for the fix!
