### ISSUE TITLE
Wrong octave in MusicXML export

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#648]
\relative {
  g' c g c
}

This should export g in octave 4, c in octave 5, g in octave 4, c in octave 5.
Actual export is g in octave 4, c in octave 3, g in octave 3, c in octave 3.

Is the \relative mode supported?

Cheers, Tobias

**Comment by PeterBjuhr** [comment]
Hi Tobias!

This works:

````lilypond
\relative g' {
  g c g c
}
````

It's the format with implicit starting that isn't supported yet.

I'll look into it relatively soon!

**Comment by tobik** [comment]
Hi Peter!

Good to know how to work around. 

Thank you!
