### ISSUE TITLE
"Last note or chord" icon is misleading

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#654]
A note with a dot means a longer duration. We need an icon to represent a repeated note. One approach would be to have two notes, perhaps on a staff line to show that they have the same pitch. Another approach would be to have a note followed by two dots. While it also means a longer duration, it would look like an ellipsis. Maybe tree dots could be used, but there is not much space in an icon.

**Comment by proski** [comment]
I think the double dot looks quite good. We need a file `note_4dd.ly`

    \version "2.18.0"
    \include "note_defaults.ily"
    
    \paper {
      left-margin = 0.1
    }
    \markup \line {
      \note #"4.." #.8
    }

![lastnote](https://cloud.githubusercontent.com/assets/1317472/6627986/5711f60a-c8d8-11e4-98b2-d0c6e40c0931.png)

**Comment by wbsoft** [comment]
nice!

**Comment by PeterBjuhr** [comment]
While I agree that the dotted icon is misleading I fail to see that a double dot is better. For the ellipsis thought to work I think we need three dots...

**Comment by PeterBjuhr** [comment]
How about something like this?

![lastnote-ellipsis](https://github.com/PeterBjuhr/auxiliary/blob/master/lastnote-ellipsis.png)

(The dots are manipulated afterwords in the svg.)

**Comment by proski** [comment]
Nice. I like that the dots are lower. But I would like to have a Lilypond implementation if possible.

**Comment by PeterBjuhr** [comment]
Did you see it? I didn't manage to get the image linking working.

**Comment by PeterBjuhr** [comment]
New try:

![image](https://cloud.githubusercontent.com/assets/355116/6637556/0694e346-c97c-11e4-89a7-7d271446635e.png)

The manipulation of the dots was done in the svg file so I don't have a LilyPond implementation.

**Comment by proski** [comment]
Yes, it worked before and it's working now. If you are going to make an ellipsis in LilyPond, I suggest using `\combine` - it suppresses collisions. Just remember that it takes exactly two arguments and doesn't like curly braces.

**Comment by PeterBjuhr** [comment]
How about this?

````lilypond
\version "2.18.0"
\include "note_defaults.ily"

\paper {
  left-margin = 0.1
}
\markup \line {
  \combine
  \note #"4" #.8
  \lower #0.5 \halign #-2.4 { ... }
}
````

![image](https://cloud.githubusercontent.com/assets/355116/6638549/86f16252-c987-11e4-9e6f-348bf4d91640.png)

**Comment by PeterBjuhr** [comment]
Or without the curly braces (sorry!):

````lilypond
\version "2.18.0"
\include "note_defaults.ily"

\paper {
  left-margin = 0.1
}
\markup \line {
  \combine
  \note #"4" #.8
  \lower #0.5 \halign #-2.4  "..." 
}
````

**Comment by proski** [comment]
Looks good to me. Let's put it to `frescobaldi_app/symbols/note_ellipsis.ly` and change `note_4d` to `note_ellipsis` in `frescobaldi_app/snippet/builtin.py`

**Comment by PeterBjuhr** [comment]
OK, I'll change it! But wait for further feedback first.

**Comment by proski** [comment]
Slightly bigger dots. Using ellipsis symbol.

```lilypond
\version "2.18.0"
\include "note_defaults.ily"

\paper {
  left-margin = #0.0
}
\markup \line {
  \combine
  \note #"4" #.8
  \lower #0.5 \halign #-2.4 \small \bold \char ##x2026
}
```

**Comment by proski** [comment]
![lastnote1](https://cloud.githubusercontent.com/assets/1317472/6640320/e83b1bc2-c96c-11e4-9441-21209226dfc6.png)

**Comment by wbsoft** [comment]
Perfectly!

**Comment by wbsoft** [comment]
> and change `note_4d` to `note_ellipsis` in `frescobaldi_app/snippet/builtin.py`

you mean probably change `note_4dd`. Let's keep the `note_4d` symbol as it is (4th note with dot), it might be used where a dotted quarter symbol is intended.

just add the `note_ellipsis` symbol. Nice.
