### ISSUE TITLE
"Close" button needs visual improvement

### ISSUE THREAD

**Issue by proski** [wbsoft/frescobaldi#655]
The "Close" button is graphically overloaded. The red square around the cross is unnecessary. The cross is too small. I suggest removing the square and making the cross bigger. The cross should also get a border to comply with Tango guidelines. That's an icon I made, but I'm not an artist, so further improvements may be needed. I cannot upload SVG here, so the source is on Google Drive.
https://drive.google.com/file/d/0Bx4CguuiXKepZWRyOElNODhwREE/view?usp=sharing
![close-menu](https://cloud.githubusercontent.com/assets/1317472/6630003/4516e840-c8ea-11e4-9c53-1e0c71b04975.png)
![close-toolbar](https://cloud.githubusercontent.com/assets/1317472/6630005/478e2688-c8ea-11e4-8e6f-79ed90bd9686.png)

**Comment by proski** [comment]
The "document" part should probably be taken from `document-new.svg`, it's much brighter there.

**Comment by proski** [comment]
The "New" button has  a brighter border because it's a PNG version. The SVG version of "New" is very similar to "Close".

**Comment by wbsoft** [comment]
I think it is already a good improvement. (Btw I also found this page with extra Tango-inspired icons http://www.softicons.com/toolbar-icons/tango-plus-plus-icons-by-insomnia)

But please, make your icons the new document-close icon, it's very nice!
