### ISSUE TITLE
Unable to use convert-ly (Frescobaldi 2.18, OSX Yosemite, Lilypond 2.16.1)

### ISSUE THREAD

**Issue by mauritslamers** [wbsoft/frescobaldi#659]
When choosing Upgrade with convert-ly from the Tools menu, it fails with the following message:

'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/Applications/LilyPond.app/Contents/Resources/bin/convert-ly", line 24, in <module>
    import os
ImportError: No module named os

I checked the commit log and found commit https://github.com/wbsoft/frescobaldi/commit/9f5e900ff95a861494f208aec7edec0d79588277, which seems to be committed more recently than the latest binary OSX release. Would this problem be solved if this would be in the binary release?

**Comment by dliessi** [comment]
Yes, this is a known problem and will be solved in Frescobaldi 2.18.1.
