### ISSUE TITLE
The document panel is resized when engraving

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#660]
This was originally reported on the mailing list: https://groups.google.com/forum/?hl=sv#!topic/frescobaldi/uMCty2-ad4k

When the document panel is set to a narrow state, an engraving resizes the panel to a wider state.

(When I replied on the mailing list a was under the impression that this was due to making room for the LilyPond icon while engraving. But on closer examination I'm not convinced.)

**Comment by wbsoft** [comment]
It is to make room for the progress bar, which is hidden normally, but created for the first time when an engraving job starts. I could change the minimum width of the progress bar, or make it simply cover the document name when engraving and the document panel is too narrow.
