### ISSUE TITLE
Drag and drop a MusicXML file into Frescobaldi

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#663]
Drag and drop a MusicXML file into Frescobaldi opens the MusicXML import dialog. But OK in the import dialog does not perform a import.

Import via File menu does work flawlessly. OS is Windows 8.1.

**Comment by PeterBjuhr** [comment]
Just to clarify, does the button say 'OK' or 'Run musicxml2ly'?

**Comment by tobik** [comment]
Yes, the button says OK in both German and English language and when opened via file menu as via drag 'n drop.

**Comment by PeterBjuhr** [comment]
Apart from the name of the button, I can confirm this error on Windows (7).

**Comment by tobik** [comment]
After restart of Frescobaldi the button name is "Run muscxml2ly". When I change the language in Frescobaldi preferences, the button name went to "OK" and remains there independent of subsequent language changes until Frescobaldi is restarted. Then it is named "Run musicxml2ly" again.

**Comment by PeterBjuhr** [comment]
I see! I'll post this as a separate issue!

**Comment by tobik** [comment]
May I tell you what a pleasure your attitude and responsiveness is. Thank you!

**Comment by PeterBjuhr** [comment]
@tobik thanks!

**Comment by wbsoft** [comment]
The MainWindow.dropEvent() function calls the import dialog but does not specify a file name to import. I propose this: iterate over the urls that were dropped, collect the "importables" and then first open the other urls in one go using MainWindow.openUrls(). After that, we can open the import dialog for the other files one by one.

**Comment by wbsoft** [comment]
I remove the Windows label, because this bug is not only present on Windows.

**Comment by PeterBjuhr** [comment]
I see, I wasn't able to reproduce it in Ubuntu.

I'll take a look at your suggestion!

**Comment by PeterBjuhr** [comment]
Hopefully the code got clearer, but it didn't solve anything.

After some more tests I think I found the source of the problem: on windows `url.path()` returns a path that is unix formatted with forward slashes instead of backslashes.

**Comment by PeterBjuhr** [comment]
`QUrl.toLocalFile()` does also format the slashes in the wrong direction (from the Windows perspective). But at least it will not stop the import.

I think `QDir.toNativeSeparators` needs to be used.
