### ISSUE TITLE
New import icon

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#671]
I think the new generic importer would fit well as an icon in the tool bar. 

Tango has one icon called document import which could perhaps be nice!? http://www.freecadweb.org/wiki/images/d/d3/Document-import.svg

![image](https://cloud.githubusercontent.com/assets/355116/6855879/4c05226c-d3fc-11e4-8581-6ea294f5bfc5.png)

**Comment by PeterBjuhr** [comment]
Thanks! Looks nice! I was also thinking about an icon in the main toolbar. Would that be a good idea?

**Comment by wbsoft** [comment]
We could also add more file types to the File—> open dialog and use that for everything, automatically calling the import dialogs where needed. I don't want to much icons in the tool bar. 

We could add some more commands to the Open toolbar action, when the user holds the button for a while, it shows the other options.
