### ISSUE TITLE
icon and desktop file should be copied within the installation prefix

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#673]
I've never realized this before because I used to have the debian package installed along with the git version: the former in /usr, the latter in /usr/local.
After removing the debian package Frescobaldi is no more "visible" to my Gnome 3 desktop (and I suppose to any desktop environment which follows the freedesktop guidelines). This is because frescobaldi.desktop and frescobaldi.svg are copied into `/usr/local/lib/python2.7/dist-packages/frescobaldi-2.18.1-py2.7.egg/share/`, which is not the proper location.

Desktop file should be copied to `/usr/local/share/applications/`.
The icon should be copied - I think - to `/usr/local/share/icons/hicolor/scalable/apps`. However it's not working here on my computer and I had to place the icon in `~/.icons`.

**Comment by wbsoft** [comment]
You are right, and this is also what it used to be. Probably the setuptools change the installation location. Thanks for reporting!

**Comment by fedelibre** [comment]
@wbsoft Are you sure that this is how it used to be?

I've searched around and I _think_ that setuptools always behaved this way. See for example [this doc page](https://github.com/pypa/setuptools/blob/52aacd5b276fedd6849c3a648a0014f5da563e93/docs/setuptools.txt#L970-L1001).
In fact Linux packagers use to deal with it and copy the relevant files to the proper installation directory (see for example the [Fedora spec file](https://src.fedoraproject.org/rpms/frescobaldi/blob/master/f/frescobaldi.spec#_75)).

OTOH, I see that files in setup.py `data_files` are copied to a separate directory (frescobaldi-VERSION.data) when building a wheel, as explained in [Generating distribution archives](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives):

```
$ unzip -l dist/frescobaldi-3.0.0-py3-none-any.whl 
Archive:  dist/frescobaldi-3.0.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      776  10-19-2015 12:34   frescobaldi-3.0.0.data/data/share/applications/frescobaldi.desktop
    15389  10-19-2015 12:34   frescobaldi-3.0.0.data/data/share/icons/hicolor/scalable/apps/frescobaldi.svg
     1542  10-19-2015 12:34   frescobaldi-3.0.0.data/data/share/man/man1/frescobaldi.1
      347  10-02-2018 07:46   frescobaldi-3.0.0.data/scripts/frescobaldi
     4400  10-02-2018 07:40   frescobaldi_app/about.py
    13075  10-02-2018 07:40   frescobaldi_app/actioncollection.py
     4422  10-02-2018 07:40   frescobaldi_app/actioncollectionmanager.py
     8224  10-02-2018 07:40   frescobaldi_app/app.py
     [...]
```

I have the feeling that we should leave the copy of these files to the system directories to Linux packagers, because:

1. setuptools cannot clean installed files automatically (while distro packages can)
2. there's no need to install Frescobaldi to run it from source. Well, if the distro package is not installed you may need some of the files in data_files to have the best desktop experience. But only a developer would run Frescobaldi exclusively from source, while users will normally install from repository and possibly run also Fresco from source seldomly.

@uliska @dliessi  what do you think? should we close this issue?

**Comment by fedelibre** [comment]
> OTOH, I see that files in setup.py `data_files` are copied to a separate directory (frescobaldi-VERSION.data) when building a wheel, as explained in [Generating distribution archives](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives):

Actually this happens also with the .egg archive file and also the linux.tar.gz file, where interestingly the install path is correct:

```
tar -ztvf frescobaldi-3.0.0.linux-x86_64.tar.gz | grep /usr/local/share
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/man/
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/man/man1/
-rw-rw-r-- fede/fede      1542 2015-10-19 14:34 ./usr/local/share/man/man1/frescobaldi.1
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/icons/
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/icons/hicolor/
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/icons/hicolor/scalable/
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/icons/hicolor/scalable/apps/
-rw-rw-r-- fede/fede     15389 2015-10-19 14:34 ./usr/local/share/icons/hicolor/scalable/apps/frescobaldi.svg
drwxrwxr-x fede/fede         0 2018-10-02 09:46 ./usr/local/share/applications/
-rw-rw-r-- fede/fede       776 2015-10-19 14:34 ./usr/local/share/applications/frescobaldi.desktop
```

This confirms that the path in data_files should not be changed, because it would break these builds.

**Comment by fedelibre** [comment]
I've [asked on Fedora developers list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/NPYPXO7F2ZXLUZ4QYPHUGAGGXDCZRIJ4/), where I had a confirmation that this stuff should be handled either by the distro packager or by a proper build tool. I think the latter is the solution we need also for other open issues. I'll open a new issue and link to all the issues that I think may benefit from a proper build tool.
