### ISSUE TITLE
go to linenumber

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#676]
reported by a user: Is there a go to line number function in the Frescobaldi editor?

I think it'd be nice to have it. It should be in the View menu, have Ctrl+G shortcut and implementation in the `mainwindow.py` file, where also methods are for search, etc.

**Comment by uliska** [comment]
Ctrl+G is already set to "Find Next". Ctrl+Alt+G would be free. Or Ctrl+Shift+L
