### ISSUE TITLE
2.18 seems to force EOL to UNIX style (LF)

### ISSUE THREAD

**Issue by RistoVaaraniemi** [wbsoft/frescobaldi#677]
Hi,

Since updating to 2.18 the line endings are forced from CR-LF to LF—I'm using Windoze as you probably guessed. I get irritating complaints from git when staging files. I had to downgrade back to 2.17.2 to get rid of them.

BR,
Risto

**Comment by RistoVaaraniemi** [comment]
You seem to have covered this in 2.18.1. Waiting for that version to come out for Windows.
Sorry for the spam.

BR,
Risto

**Comment by wbsoft** [comment]
Yes, thanks for reporting. We fixed that already, 2.18.1 will be released shortly.
