### ISSUE TITLE
Frescobaldi crashes in Ubuntu 15.04

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#679]
I've just upgraded to Ubuntu 15.04 and something doesn't go well with Frescobaldi. 

First the pdf is blank and then the whole window freezes. 

Anyone else with the same problem?

**Comment by proski** [comment]
I had access to Ubuntu 15.04 about two weeks ago and I didn't see any problems with Frescobaldi. Unfortunately, I'm in process of moving home and I don't have time and means to recheck it for now. I suggest that you avoid using PDF, use SVG and see if the freeze still happens. Try recompiling poppler-qt4.

**Comment by PeterBjuhr** [comment]
By hacking the command line version argument I was able to extract the `bugreport.versionInfoString()` although the app itself is unusable:

	Python: 2.7.9
	Qt: 4.8.6
	PyQt4: 4.11.3
	sip: 4.16.6 
	python-ly: 0.9.2 
	poppler: unknown
	python-poppler-qt4: unknown 
	OS: Linux-3.19.0-15-generic-i686-with-Ubuntu-15.04-vivid

Both poppler and python-poppler-qt4 are unknown.

**Comment by proski** [comment]
Only the latest versions of python-poppler-qt4 can report their own version and the version of poppler.

**Comment by PeterBjuhr** [comment]
I removed all dist-packages. Then I could reinstall Frescobaldi (2.17.2). 

Still can't run it from current master though (no error message from Python).

**Comment by PeterBjuhr** [comment]
I found some more bugs in the system. But now everything seem to run fine.

@proski thanks for your support.

Sorry for the noise!

**Comment by PeterBjuhr** [comment]
Another issue worth mentioning is that the Snippet menu and the Sessions menu doesn't get populated by snippets and sessions (respectively).

Probably this is not a real Frescobaldi issue either.
