### ISSUE TITLE
\relative without explicit starting pitch

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#682]
As noted in [this thread](https://lists.gnu.org/archive/html/lilypond-user/2015-04/msg01093.html) in the user list, the compact way of entering \relative blocks might be desirable. What do you think?
It's supported [since version 2.18](http://lilypond.org/doc/v2.18/Documentation/changes/index.html):

_When \relative is used without an explicit reference pitch, the reference pitch now is the middle of the first octave, making the first entered pitch indistinguishable from absolute pitch. Previously, omitting the reference pitch would have lead to a default of c'. Since that choice was somewhat arbitrary, recommended usage was to always specify the reference pitch._

IMO the compact version is better and should be used in the score wizard and in the conversion absolute to relative.

http://lilypond.org/doc/v2.19/Documentation/notation/writing-pitches.html#relative-octave-entry

**Comment by sincere-music** [comment]
I agree. In my memory, using \relative without a reference pitch was considered somewhat bad practice, but that was probably before the 2.18 change, and even before that I’ve been using the ‘implicit’ version.
And now there shouldn’t be any reason to stay with the ‘old’ way, is there?

**Comment by fedelibre** [comment]
It seems that there's some interest in changing the LilyPond documentation as well:
https://code.google.com/p/lilypond/issues/detail?id=3229#c28

**Comment by wbsoft** [comment]
This indeed should be supported by e.g. transpose and relative->absolute and vv.

The "relative->absolute" procedure should simply understand `\relative` without start pitch correctly (i.e. defaulting to `c'` or regarding the first pitch as absolute (which is in fact similar to defaulting to `f`) when the document version is >= 2.18).

The absolute->relative command should probably have two or maybe three incarnations: one writing `\relative` with a start pitch, and one writing `\relative` without start pitch, understanding the first note either as absolute, or relative from `c'`...

**Comment by wbsoft** [comment]
fixed.
