### ISSUE TITLE
popup window not on focus so keyboard shortcuts don't work

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#688]
This is a very minor issue and, I guess, also easy to be fixed.

If you close an unsaved document, a window pops up asking what to do. The focus does not change to this new popup window so using keyboard shortcuts (Alt+...) is not possible. The shortcuts work only after clicking on the popup window, making the shortcuts no more useful at all.

**Comment by PeterBjuhr** [comment]
Sorry if I'm misunderstanding something here, but I can't confirm this; when the Close Document popup appears the keyboard shortcuts do work - using `Ctrl+c` cancels and `Ctrl+s` gives the save dialog.

Could it be something related to your system? What exact shortcut was you trying (Alt+?)?

**Comment by fedelibre** [comment]
Yes, I guess that it depends on the desktop and window manager used. I'm on Debian, Gnome 3.

I did not specify the key after Alt as it depends on the language. Now I've started frescobaldi in english and the shortcut which should work are Alt+C to cancel and Alt+S to save. No shortcut provided for closing (this is another bug), as no character is underlined:

![fresco-close](https://cloud.githubusercontent.com/assets/1644647/7746973/042e3820-ffb7-11e4-9e38-f06d1fa1212c.png)


Here Ctrl+C and Ctrl+S do not work in the close document popup.

**Comment by PeterBjuhr** [comment]
>Now I've started frescobaldi in english and the shortcut which should work are Alt+C to cancel and Alt+S to save. 

So does the use of `Ctrl` or `Alt` vary between systems? On mac I guess it would be `⌘` instead of `Ctrl`.

>Here Ctrl+C and Ctrl+S do not work in the close document popup.

I don't think you mean that, but you aren't actually hitting Ctr+Shift+c to get the upper case C? I guess there's a potential misunderstanding from the button texts.

**Comment by fedelibre** [comment]
I was not precise: Ctrl+C and Ctrl+S do work but only when I click on the window and I get the focus on that window.
Does Alt work in your system? I'm used to use Ctrl+... for main window and Alt+... for pop up windows.

No, I'm not using the Shift key.

**Comment by PeterBjuhr** [comment]
>Does Alt work in your system? I'm used to use Ctrl+... for main window and Alt+... for pop up windows.

Yes, either Alt or Ctrl works. I've never heard of using Alt for popups before.

**Comment by PeterBjuhr** [comment]
>No shortcut provided for closing [without saving] (this is another bug), as no character is underlined.

Maybe that's because there is no obvious short cut for that. Any suggestion?

**Comment by PeterBjuhr** [comment]
> I've never heard of using Alt for popups before.

I guess I don't use shortcuts much on popups. @fedelibre, on popups created with `QDialog` and with a `QDialogButtonBox` your rule about using `Alt` instead of `Ctrl` seem to apply.

Could you please try a dialog of this sort - for example using anything from the import menu - and see if you're having the same problem?

(The Close Document popup uses `QMessageBox`.)

**Comment by fedelibre** [comment]
It's very common in Gnome applications, where only Alt works for popups: when you click Alt, the shortcut key becomes underlined so you know what to press.

**Comment by fedelibre** [comment]
Yes, the import menu works fine.

I have problem only with popups. The popup window stays in background while it should be the active window. Some time ago I reported a similar problem about window focus on startup (issue #314).

**Comment by PeterBjuhr** [comment]
I meant the popup dialog for the import (you have to choose file for import first). Did you try that?

If it works, maybe it would be a good idea to create a new class from `QDialog` instead of using `QMessageBox` which apparently have problems in some systems. We would also have more consistent behavior for all popup dialogs.

**Comment by PeterBjuhr** [comment]
Maybe a bad choice of example, take the custom engrave dialog instead if you like...

**Comment by fedelibre** [comment]
That works fine: I use Shift+Ctrl+M and Alt+C.
BTW, the popup does not have a shortcut to run lilypond, only to cancel.

**Comment by PeterBjuhr** [comment]
>Maybe it would be a good idea to create a new class from QDialog instead of using QMessageBox which apparently have problems in some systems. We would also have more consistent behavior for all popup dialogs.

@wbsoft could [`widgets.dialog`](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/widgets/dialog.py) be used?

**Comment by wbsoft** [comment]
I see more hits on "QMessageBox fails to gain focus" on Linux. I propose we should try to fix this, rather than circumvent QMessageBox altogether. Maybe creating an instance (with parent) helps, instead of using the static `QMessageBox.critical()` etc functions.

**Comment by PeterBjuhr** [comment]
I agree that could make a difference! I set up a test...

**Comment by PeterBjuhr** [comment]
I think we can close this now. It turned out to be a non-frescobaldi issue, I would say.
