### ISSUE TITLE
Enable Ctrl-Enter in Custom Compile dialog

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#691]
Is there a way that I've missed to run LilyPond from the Custom Compile dialog using *only* the keyboard *after* editing the command line?

IISC I have to click the button with the mouse after that. But I'd expect for example to have Ctrl-Enter to run LilyPond when I'm inside the command line editor (as do the editing windows on Github for example).

**Comment by PeterBjuhr** [comment]
This was recently stated in #688. :) But perhaps it is good to have this in an own issue!

**Comment by uliska** [comment]
i don't think it's exactly the same in the other issue.
I'm on Debian/Gnome 3 too, and can use `Ctrl-Shift-M`, `Tab`, `Enter` to run it. But once I've entered the command line editing widget I can't get out of it again.

**Comment by PeterBjuhr** [comment]
Sorry, I see the difference now!

Adding a shortcut would have solved it - you can use the shortcut to cancel the dialog. But I like the idea of using Ctrl+enter from the editor.

**Comment by uliska** [comment]
Yes, *I* now see that the shortcut would be a reasonable way. But 
Ctrl-Enter would be consistent with many other applications, like the 
mentioned Github (and presumably other web) editors, or the way to send 
emails (at least on my Thunderbird).
