### ISSUE TITLE
Snippets and sessions don't get populated in their menus

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#696]
This was already mentioned in #679. But I have confirmed it on another computer so I think it deserves the status of an issue.

The problem is that `(QMenu.)aboutToShow` doesn't get triggered.

Happens in Ubuntu 15.04. Didn't happen in previous versions.

**Comment by wbsoft** [comment]
Probably same type Qt/Unity bug as the old one #46 that the menus grew everytime (i.e. `QMenu.aboutToHide` didn't trigger)...

I really should rework those menus so that they don't depend on `aboutToShow` and `aboutToHide`... (but find a way to keep the lazy loading).

**Comment by PeterBjuhr** [comment]
With lazy loading do you mean something else except that the menus doesn't get populated directly?

I noticed that if you populate the session menu when it's initiated then the current session doesn't get correctly set.

**Comment by PeterBjuhr** [comment]
>>I really should rework those menus so that they don't depend on aboutToShow and aboutToHide... (but find a way to keep the lazy loading).

>With lazy loading do you mean something else except that the menus doesn't get populated directly?

I guess that you also mean that you don't have to worry about changes to the snippets and sessions when the menus get populated dynamically!? But wouldn't it be possible to repopulate when something change instead?

**Comment by PeterBjuhr** [comment]
The issue is now solved - presumably by some of the latest updates to Ubuntu 15.04.

>I really should rework those menus so that they don't depend on aboutToShow and aboutToHide... (but find a way to keep the lazy loading).

As far as I know there is no immediate need for that now and this issue can be closed. But the functionality do seems to be unreliable.
