### ISSUE TITLE
Support for Double-Click + Drag

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#699]
This request originates from the [Frescobaldi mailinglist](https://groups.google.com/forum/#!topic/frescobaldi/5IKmUEi4fCw).

In several editors you can double-click to select a word, hold and then expand the selection (word by word) by dragging/sweeping with the mouse before the button is released.

Could this be added in Frescobaldi?

**Comment by wbsoft** [comment]
Yes it used to work, but then I added the wordboundary improvements and this nicety ceased to work...it's on the todo list!

**Comment by wbsoft** [comment]
The trouble is that what defines a word boundary is not configurable in `QPlainTextEdit`. So I override all kinds of events to implement the desired behaviour (i.e. to regard a `\` as boundary (even without space) and `-` not). I need to add support for double and triple click, and drag after select-by-word becomes active. This is all quite complicated but is probably possible to do in `frescobaldi_app/widgets/wordboundary.py`.
