### ISSUE TITLE
python-ly issue

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#700]
I still have a problem getting `python-ly` to work properly with Frescobaldi.

I have python-ly in its Git repository and added that to `PYTHONPATH`. So firing up `python` and issuing `import ly` in the Python shell works. However, starting Frescobaldi gives me the popup of python-ly being missing or too old.

I can fix this by inserting `import ly` after the `import sys` clause in the `frescobaldi` starter script. However, this is of course not a permanent solution.
So, is there something wrong with my installation, or is that a subtle bug in Frescobaldi's setup?

**Comment by PeterBjuhr** [comment]
Removing all instances of the `ly` folder inside both source code and installed versions of Frescobaldi is usely the problem in my experience.

**Comment by uliska** [comment]
Thank you, that was the problem. Maybe I should have thought of this myself. But: Why haven't these files been removed at some point by Git?

**Comment by wbsoft** [comment]
They have, but not the compiled *.pyc files.

**Comment by uliska** [comment]
Hm, for some reason I still had the .py files there ...

**Comment by wbsoft** [comment]
Installing python-ly simply overwrites older installations, it does not remove old files first, iirc.

**Comment by uliska** [comment]
You may safely ignore this comment as the issue has been resolved. But for some reason I had `python-ly`'s `.py` files left in the `ly` directory of my *Frescobaldi* repository. 
But I assume this must be something I managed to mess up with switching branches. Interestingly these `.py` files didn't show up as untracked, nor do they now show up as missing from Git's perspective.

**Comment by PeterBjuhr** [comment]
If I recall it correctly I had the same experience (having to remove the local folder manually). You can remove a (sub)folder from git without deleting it locally so I guess that is what happened.

**Comment by uliska** [comment]
1f29c83f526e901dcbff222bef140d01e1f77629 seems to have removed the files properly, so it seems to be a "local" issue. I sort-of know that you can bring Git to leave files checked out that aren't tracked anymore by the repository, although I don't really know what happens then.

For example something like this:
When the above commit was pulled the local repository was on a different branch. When then checking out `master` the `.py` files are not removed because they are not tracked. However, I'd expect them to be listed as "untracked" then. Maybe we have reacted wrongly to that message the next time ...
Anyway, it's solved for me, it's been a long time that anyone complained, and it only affects people running Frescobaldi from Git. So we can safely let this discussion rest in peace ...
