### ISSUE TITLE
manuscript viewer should forget file position (or save per-file)

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#702]
When I open a file in the manuscript viewer, then navigate in it (scroll/browse) and then open another file this is opened at the position of the first document. That is, when I open manuscript A, move to page 5, then a manuscript B will also open on page 5. (If B has only 3 pages it will open at the end).

I don't think this is a good idea, and I see two acceptable behaviours:

* "forget" the position in file A and always open a new file on page 1
* store the position per file in the settings, so file A will be reopened properly when it is opened again.  
  However, this would have to provide some "garbage collection" because I don't think we want to keep information about all manuscripts ever viewed.

Actually the third behaviour is what I'd suggest:

* for now let the viewer forget about the position and always open at the top of the file (and zoomed to page width?)
* in a later stage we will want to add meta information about the manuscript(s) anyway, so that's where we should store information on the viewing position.

**Comment by PeterBjuhr** [comment]
@uliska You already solved this, but it will not get closed until the branch is merged. I close it manually.
