### ISSUE TITLE
Manuscript viewer architecture (again)

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#704]
I just started looking at the code in `musicview/widget.py` in order to add more features to the manuscript viewer.

But I have the impression that there are so many correspondences that we should really consider switching architecture *now* instead of continuing too much with developing an interim solution. I think the music view and the manuscript viewer should be two sibling subclasses, sharing a considerable amount of code.

For example, we'd need the pager, and the UI, and a good deal of the signal handlers as well.

What do you think?

**Comment by PeterBjuhr** [comment]
I've come to a similar conclusion.

But a temporary solution could be to just use the classes without subclassing.

**Comment by uliska** [comment]
I also tend to a kind of "hacky" solution because we will have to do a
rewrite anyway if Wilbert (or we together) should one day manage to
update the infrastructure.

So what do we actually need?

- Open/close document (implented)
- scrolling/zooming
  can already be achieved by the mouse, but should actually have UI elements
  (I think they should be in the HBox where currently the File dialog
buttons are)


Do we need all the interface elements like the music view? Probably yes.

I think (first impression) that implementing the pager stuff would be
most complex and mixed with the music view code. Zooming is probably
much easier as it can directly access the PyQt functions.

**Comment by PeterBjuhr** [comment]
>Do we need all the interface elements like the music view?

I don't think we need the point-and-click functionality. Even if an use-case with a LilyPond pdf is thinkable it's too obscure to my mind. In that situation it would probably be better to actually use an instance of the Music viewer instead.

**Comment by uliska** [comment]
Ah, no, I'm not talking about this. Of course we don't need the
point-and-click, at least for a considerable time. We also agreed upon
deferring any attempt to track positions in the score and getting the
positions of input, manuscript and music view in sync. Of course that's
a major goal of that tool, but only for the future.

For now I though about the navigational UI elements that the music view
has in the toolbar: page numbers, previous/next page, separate +/-
controls and the zoom combo box.

**Comment by uliska** [comment]
I am thinking of not *copying* but *using* the navigation toolbar, either "in-place" in the top toolbar, or by making a copy at the top of the manuscript viewer.

**Comment by PeterBjuhr** [comment]
It would be consistent if the manuscript viewer has similar controls as the music viewer. But if you are talking about both widgets using the same toolbar, I'm having trouble seeing how this could be achieved.

**Comment by uliska** [comment]
It was just an idea, but I'm starting to like it.

The approach would be to have an action (e.g. triggered by one of the viewers getting focus or by an explicit UI interaction) that reconnects all the signals from the toolbar to the respective viewer. I mean that's one of the use cases for the signal/slot mechanism, isn't it?
And we should consider adding the SVG viewer to that group. It would add consistency to the UI - *and* it would save space on the manuscript and SVG viewers.

With regard to the infrastructure I think we should at least have a look if we could *start* with an subclassing approach. The first step would be to try modifying the current Music View so it becomes a subclass of a new base class. Initially the base class would be identical to the current music viewer, but in the second step we could sort out what is specific about the music view from the generic functionality. Once that is in place (without any change in overall functionality) we could recreate the manuscript viewer as a subclass of that base class. And maybe also the SVG viewer.

**Comment by fedelibre** [comment]
@uliska I've just checked out the manuscript-viewer branch and it's already useful as it is.
I have a question: I'd like to have preview and manuscript panels side by side, **not tabbed** but both visible. This cannot be achieved right now, correct?

**Comment by fedelibre** [comment]
forget my previous comment: I managed (by accident) to have the two panels side by side
wonderful!

**Comment by PeterBjuhr** [comment]
Great! The manuscript panel (like the other panels) can be replaced by the user to a suitable setup. I don't think we have set a good default placement yet. Suggestions are welcome!

**Comment by fedelibre** [comment]
It would be great if the Preview was kept on the right when not using manuscript and then moved to the up right (or up left) when the manuscript is activated, as in [this screenshot](http://postimg.org/image/gs4lgw80v/).

**Comment by PeterBjuhr** [comment]
Thanks for the screenshot! I'm not sure about moving around the music viewer but maybe they could be top left and top right by default. It seems suitable to keep the music viewer close to its toolpanel.

**Comment by PeterBjuhr** [comment]
>Of course we don't need the point-and-click, at least for a considerable time. 

Now the point-and-click works so I guess the question if we really want/need it has to be addressed more seriously. 

At the moment I don't see any point in being able to do point-and-click on LilyPond files, but somebody may find this useful...

**Comment by uliska** [comment]
Regarding the screenshot I'm not sure if we can reliably make a guess what a user might want. For example I wouldn't lay it out like you do @fedelibre but keep the input left at full height and place the music view and manuscript viewer stacked top/bottom on the right side. Apart from that it will be changed by the QSettings after first use.

**Comment by fedelibre** [comment]
>
> Regarding the screenshot I'm not sure if we can reliably make a guess what a user might want. For example I wouldn't lay it out like you do @fedelibre but keep the input left at full height and place the music view and manuscript viewer stacked top/bottom on the right side. Apart from that it will be changed by the QSettings after first use.
>
I think that what you write is better. There's enough space to compare by system; vertical comparison is even better. And it doesn't change much the usual setup: when you close the manuscript you get back to default.

**Comment by uliska** [comment]
I have (deliberately) not looked at the code yet but only tested in Frescobaldi itself. From this I'm very happy with how it behaves. I have added a number of issues with the "Manuscript" milestone, and I think these are the only missing parts before we can consider merging in the new tool.

**Comment by uliska** [comment]
I think everything discussed in this issue has been either resolved or moved elsewhere. If someone agrees we may reopen it, but for now I'll close.
