### ISSUE TITLE
Disable musicview functionality in the manuscript viewer?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#708]
As already raised by @PeterBjuhr it has to be discussed how the manuscript viewer should behave when the opened file is a LilyPond-generated PDF with point-and-click links.

Currently this allows the user to jump to the input file, and it allows to edit the current line in the "Edit in place" dialog.

This may come in handy, but it can also be confusing. For example when editing a file that way and recompiling it the PDF won't be updated automatically in the manuscript viewer but in the music view.

Generally it is not "natural" to have a file open in the manuscript viewer that has been generated by LilyPond on the current machine (but only in this case the point-and-click does work). But is it desirable to block this functionality then? Maybe there *are* workflows that might be useful?

I'd tend to try removing that functionality, but please share your opinions on the matter.

**Comment by PeterBjuhr** [comment]
With the current design we can now offer basically the same functionality in the manuscript viewer as in the music viewer although the purpose of course not is for opening LilyPond pdf:s. First of all if some functionality works you would expect all to work; so I see no reason why we should discuss different functions separately. I therefore propose we close #707, and keep the discussion here. @uliska ?

**Comment by uliska** [comment]
OK, now we're back at the inheritance design questions, isn't it?

I'm not sure about the actual coding, but this looks like we should remove the specific functionality from the base class.

Am I right that `AbstractViewPanel` is now a copy of the old `MusicViewPanel` and that the music viewer is for now completely independent from the new structure?

If that's the case we could go forward with trimming the abstract base class and deal with that when we do the next step and make the music viewer inherit from that too.

**Comment by PeterBjuhr** [comment]
>Am I right that `AbstractViewPanel` is now a copy of the old `MusicViewPanel` and that the music viewer is for now completely independent from the new structure?

Yes. `AbstractViewPanel` is basically a copy of `MusicViewPanel` and `AbstractPopplerView` is a copy of `MusicView`. You can confirm in the history that the existing files are not changed.

So the question remains if this functionality should belong to the base class or be specific to the the music viewer!?

**Comment by uliska** [comment]
* Synchronize with cursor  
The interface belongs to the base class, but the manuscript viewer doesn't implement it so far (and won't do so before the necessary logic has been added to python-ly (properly determine measure position of the cursor) and the manuscript viewer (mark up manuscripts with information on their measure positions).  
So this suggests greying out the menu item in the manuscript viewer's context menu.
* point-and-click  
I think some of the *implementation* should be moved from the base class to the children. The manuscript viewer will support the same functionality one day, only that it isn't tied to the point-and-click links but to another mechanism that we'll have to invent.  
So maybe the best approach for now would be to simply *suppress* point-and-click in the manuscript viewer.
* edit in place  
This is definitely something that should *not* be part of the manuscript viewer IMO.  However, if one day we should also be able to integrate the SVG viewer in that viewer system it would be different again.

**Comment by PeterBjuhr** [comment]
First a general comment: It's presumably thinkable with a workflow that makes use of two LilyPond viewers. On the other hand it would be more logical then to be able to create a second instance of the music viewer (you can now create a new window but not really the same thing).

I think the general question should be: is there any disadvantages of keeping the LilyPond functionality in the manuscript viewer? Another interesting question - would the user expect these things to work when opening a LilyPond pdf?

**Comment by PeterBjuhr** [comment]
>**Synchronize with cursor**
>The interface belongs to the base class, but the manuscript viewer doesn't implement it so far (and won't do so before the necessary logic has been added to python-ly (properly determine measure position of the cursor) and the manuscript viewer (mark up manuscripts with information on their measure positions).
So this suggests greying out the menu item in the manuscript viewer's context menu.

It is implemented the same way as in the music viewer. But it doesn't work for a non-lilypond pdf. And perhaps the user expects that. So I agree that should be greyed out - at least for non-lilypond-pdf:s.

**Comment by uliska** [comment]
>     *Synchronize with cursor*
>     The interface belongs to the base class, but the manuscript viewer
>     doesn't implement it so far (and won't do so before the necessary
>     logic has been added to python-ly (properly determine measure
>     position of the cursor) and the manuscript viewer (mark up
>     manuscripts with information on their measure positions).
>     So this suggests greying out the menu item in the manuscript
>     viewer's context menu.
> 
> It is implemented the same way as in the music viewer. But it doesn't
> work for a non-lilypond pdf. And perhaps the user expects that. So I
> agree that should be greyed out - at least for non-lilypond-pdf:s.

OK. I hadn't thought this works with lilypond-pdf-s.
Is there a way to determine whether an opened PDF is a lilypond
generated one?

**Comment by PeterBjuhr** [comment]
We should probably be able to use `viewers.pointandclick.Links`  - set in the variable `self._links` when a document is opened - to determine when to disable the menu item.

**Comment by uliska** [comment]
Actually this is what I'm trying out exactly in this minute ;-)

**Comment by uliska** [comment]
OK, after having had the discussion in https://github.com/wbsoft/frescobaldi/commit/abd054e73406e483676e9141e4843b1b6f82b185 I'll close this and drop the other branch.
