### ISSUE TITLE
Add navigation buttons to the manuscript viewer

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#709]
The manuscript viewer needs the prev/next buttons and the page number display/selector just like the music view. I think this is necessary for the initial release.

It would be nice to also have the zoom controls, but this is less important because zooming can quite conveniently be controlled with mouse wheel and context menu.

They should at least *look* exactly the same as with the music view's controls. And actually I'd prefer them to also share the *code*. But it is probably acceptable to simply copy the code for an initial release.

**Comment by PeterBjuhr** [comment]
I have to double-check this but I think we do have all the code in place. The only thing remaining is to actually create the buttons for the controls.

I agree this should be done before the release.

**Comment by uliska** [comment]
I'm right now writing another, more general issue on that matter.
