### ISSUE TITLE
Should the manuscript viewer save the currently opened document?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#711]
So far the manuscript viewer simply forgets about the opened file and its state (layout).

Would it be more consistent (and thus desirable) that reopening Frescobaldi would reopen the file, at the last known position and zoom? I think, yes.

Additionally: 
Should this apply to switching sessions also?

Additionally: 
The File open dialog doesn't care about starting with a useful directory. On my computer it always starts at the home directory. I think the starting directory should be kept at least during the Frescobaldi working session, so when opening the dialog the second time it starts with the directory of the previous (= the current) document.
The question is where it should originally start. It might start in the directory of the current document in in the editor. But I'd say that more often than not people store their manuscripts *outside* of the LilyPond project.

PS: This discussion may partially become obsolete when the manuscript(s) can be tied to input documents.

**Comment by PeterBjuhr** [comment]
When you are in a session a file open dialog starts with the base directory of that session.

I think the opened manuscript documents should be saved in the session.

**Comment by uliska** [comment]
OK, just tried it, and it does so.

But it doesn't behave properly when no session is active. I think the dialog should then start either in the directory the currently displayed manuscript is in or in the directory of the current document in the editor. If both are empty it's OK to start in the home directory.

**Comment by uliska** [comment]
I've done an implementation, but I'm not completely sure if the behaviour is really desirable. It is quite "smart" but this could also be perceived as inconsistent.

This is the behaviour of the manuscript viewer's "Open file" dialog with regard to initial directory:

* If nothing is opened at all the dialog will start with either the app's base directory or the base directory of an opened session
* If there's an input file opened in the editor the dialog will start at that file's directory
* If there's already a manuscript opened in the viewer the dialog will start at the manuscript file's directory, overriding the current editor document.

The first two steps are clear, but I'm not sure about the third one. This might "feel" inconsistent or inexpected. And if I'm changing input files I might also intend to open a different manuscript. But OTOH I would suspect that manuscripts usually are not in the same directories as the input files anyway, so it might make sense that way: If we already have a manuscript open keep looking at that place, only if not start looking at the input file's location because that's better than always starting at the root directory.

What do you think?
Would it make sense to make that a preference ("manuscript location supersedes input file")?

**Comment by uliska** [comment]
The open manuscript isn't stored in the current session so far, but I don't have an idea where that actually happens, so I won't tackle that now. I'm not completely sure if we really need that, though.

**Comment by uliska** [comment]
I think the new #715 is all that is left from this issue, so I close it.
