### ISSUE TITLE
Support arbitrary links in manuscript viewer

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#712]
When loading a text document in the manuscript viewer arbitrary links are at least recognized (mouse pointer and highlighter show that).

It would be cool if these links would (partially?) work, at least for internal navigation in the viewer. This might open up interesting options for navigating manuscripts.

But this is more an idea for later.

**Comment by PeterBjuhr** [comment]
I haven't tried internal links, but external links (to a web page in my test case) seem to work!

**Comment by uliska** [comment]
interesting. i don't know what it was but it didn't work. being able to display arbitraty text documents (e.g. with editorial notes) may open up cool possibilities. for example we could tune the output of annotations in a way so you can view a beautiful list that is linked to the input. 

but as daid this is not for the initial release.

**Comment by uliska** [comment]
OK, I've verified too that external links work out-of-the-box, while internal ones, e.g. to footnotes or in a TOC (of a LaTeX-generated PDF) do *not*.

Probably it would be possible to make that work too in some way, but we can definitely ignore that suggestion for now. I will keep it in mind for the annotation viewer/editor, but that will probably be done more easily with HTML: It will be possible to create an annotation editor in that case, it will be equally possible to produce nicely formatted display (maybe even nicer, and responsive), and of course it will be possible to produce the HTML files directly from within LilyPond (i.e. in the `ScholarLY` package), without having to rely on LaTeX being present and configured.

So I'm closing this now.
