### ISSUE TITLE
Default placement of the manuscript viewer?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#714]
Should we define a default placement of the manuscript viewer?

If so I suggest two alternatives:

* Open manuscript and music viewer on top of each other, at the right side (where currently the music view is by default)
* Add the manuscript viewer as a tab alternative to the music view.

The former is maybe more in line with the main intention of the manuscript viewer, but the latter is much less intrusive in terms of screen estate.

**Comment by PeterBjuhr** [comment]
I think it can be assumed that the user wants to have both viewers visible for easy comparison.

At first I placed the manuscript viewer above the music viewer. But considering the placement of the toolbar for the music viewer I changed this to a placement below.

**Comment by uliska** [comment]
Yes, that's reasonable.
I don't know why I too automatically placed the manuscript viewer at the top. Maybe this *is* more natural in the end?

Anyway, I think it is not a good idea if the manuscript and the music viewer have (nearly) identical toolbars in different places so this should be harmonized somehow (as Wilbert suggested we might move the music view toolbar from the main toolbar into the panel, but at some later point.)

**Comment by uliska** [comment]
So, is there an agreement that the default should be to place the music view in the right half of the window and the manuscript viewer below it, so that if both are open they share the right part of the window?

My impression is that's the agreement, but I don't know where to set the default.

**Comment by dliessi** [comment]
I have not tried the manuscript viewer yet (I'll do it tonight), but my impression is that I would prefer having the manuscript on top because then the music entry and the manuscript are aligned.

I think that in most cases one would copy the music from the manuscript viewer to the music entry window and then check the entered music by comparing the manuscript viewer and the music viewer.
For the latter task it is indifferent which one is on top, but for the former I think it is easier with the manuscript on top.

**Comment by PeterBjuhr** [comment]
The default placement is set by [this line](https://github.com/wbsoft/frescobaldi/blob/manuscript-viewer/frescobaldi_app/viewers/manuscript/__init__.py#L50)

**Comment by uliska** [comment]
Good point.
However, the main reason for us to do it that way is that (so far) the
manuscript viewer has its toolbar inside the panel while the music
view's is in the toolbar of the main window. We consider changing this
some day although it would take up some space.

**Comment by uliska** [comment]
So setting this to `Qt.RightDockWidgetArea` would be the command of choice? But it still doesn't take care of placing it to the top of the music view, isn't it?

**Comment by PeterBjuhr** [comment]
Yes, I just changed this: 0e33cbae0de05a0b467e6537a1f063db49df6b90

When I tried it, it was placed below the music view. 

Although I agree with @dliessi that above would be preferred, I think we should go with this for now considering the music view toolbar. It can easily and permanently changed by anyone preferring something else.

**Comment by uliska** [comment]
Well, on my machine the music view was placed at the bottom on my
machine. So a) it's probably somewhat random what happens and b) this
randomness depends on what the user already has done before.
But probably it's right to keep it at that. When both are on the right
side it's OK, anything else can be done by the user.

**Comment by PeterBjuhr** [comment]
@uliska how did you override the settings? I tested by commenting this [line](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/mainwindow.py#L353).

**Comment by uliska** [comment]
Well, I simply didn't because I don't know how to ...

**Comment by PeterBjuhr** [comment]
Then it would depend on what you done before. But perhaps you are right that there are some randomness in what gets on top.
