### ISSUE TITLE
Horizontal scroll position of open document tab bar changes on engrave

### ISSUE THREAD

**Issue by PaulMorris** [wbsoft/frescobaldi#716]
When you have a lot of documents open so that they overflow the width of the horizontal "tab bar" where the titles of all the open documents appear, and the left and right arrows appear that let you scroll left and right...  And then you engrave one of the documents...  The horizontal scrolling position of the tab bar changes, so that different document tabs are visible, and you have to manually click the arrows to move it back where you want it, every time you engrave a document.

It would be better if the horizontal "scroll position" stayed the same when you engrave a document, so that the same documents stayed in view, before and after engraving.

**Comment by uliska** [comment]
Does this depend on the "Engrave this document" setting?

**Comment by PaulMorris** [comment]
Do you mean LilyPond menu --> "Always engrave this document" ? 
That setting doesn't affect it.

**Comment by uliska** [comment]
Yes, that's what I meant. I recall this having something to do with the
tabbing behaviour. But obviously we can forget that.

**Comment by PaulMorris** [comment]
More details:  It seems that on engrave it always returns the scroll position all the way to the left, unless that would cause the engraved document to go out of view, so in that case it scrolls left until the engraved document is all the way at the right side of the visible tabs, which pushes any tabs to its left out of view.

**Comment by PaulMorris** [comment]
So if the digits are open tabs and the [ ] shows currently visible tabs:
  1 2 3 4 [5 6 7 8] 9 

And I engrave tab 5, then this is the new scroll position:
  1 [2 3 4 5] 6 7 8 9

**Comment by wbsoft** [comment]
Yes this is annoying, but caused by QTabBar. An engrave job causes the icon of a document to change, and this icon change triggers a redraw of the tab bar, which QTabBar does not handle nicely.
