### ISSUE TITLE
Should manuscript auto-update if it's a LilyPond-generated one?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#717]
There is a slight inconsistency when the manuscript viewer holds the same document as the music view: Point-and-click works, edit-in-place works, so it might be assumed identical. But when the document is recompiled the music view updates the PDF while the manuscript does not.

Is this something that should be handled? Or can we consider this a more or less "invalid" use case?

**Comment by PeterBjuhr** [comment]
When I edit a document I sometimes save a copy or do a printout for reference of the original state before the edits. One interesting thought is that the manuscript viewer actually can be helpful in such cases.

That said, I think the user should be able to easily update the document so I propose a reload button (similar to what we have in the SVG viewer).

**Comment by uliska** [comment]
Good idea. Actually that button should only be active when the file has
changed, though. But that would require implementing some logic to
monitor file changes (or rather take the existing functionality for that).

But I think we can settle with a simple reload button for the initial
release and open a new "wish" issue once that has been added.

**Comment by PeterBjuhr** [comment]
I'm not sure we need to monitor changes just to disable the button. Compare the situation with the reload option in the file menu - that is always enabled. 

You can also compare it with the reload functionality in a web browser.

**Comment by PeterBjuhr** [comment]
I self-assigned to add the button...

**Comment by uliska** [comment]
And I implemented the session handling in 1db340c1 (and previous)

**Comment by uliska** [comment]
Oops, closed the wrong issue

**Comment by PeterBjuhr** [comment]
Although I like the reload icon in the toolbar I think its usecase may be rare, and therefore I propose I move to the contextmenu!?

**Comment by uliska** [comment]
I've moved it to the context menu.

One question: you have defined the `music_reload` action on the `viewers` level, but there is no implementation for the musicview. I think this is "dangerous" because someone could see that action and add it to the music view, which would presumably fail.

I suggest either adding something to the music view (if that makes any sense at all) or defining the action in `viewers.manuscript.Actions`

**Comment by PeterBjuhr** [comment]
The reload method the manuscript viewer uses is defined in `ManuscriptViewPanel`. But there is a reload method also in `MusicViewPanel`. And also a corresponding action. All I did was adding an icon, see cf8423952585f3f4e1d09c661b062c4051138277.

**Comment by uliska** [comment]
OK
