### ISSUE TITLE
Switching to "no session" creates a nameless new session

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#721]
This is probably related to my commits saving and loading the current manuscript to the session.

**Comment by PeterBjuhr** [comment]
I was just about to report this (so I can confirm this issue).

**Comment by uliska** [comment]
I found the issue. However, I'd like to have your opinion on this:

If switching to "no session" or if the switched-to session doesn't have a manuscript, should a currently opened manuscript be kept open or closed?

**Comment by PeterBjuhr** [comment]
>If switching to "no session" or if the switched-to session doesn't have a manuscript, should a currently opened manuscript be kept open or closed?

When switching to "no session" the other documents are closed so I think it's consistent to also close the manuscript.

And I don't see why a new session should retain a previous manuscript especially if no manuscript was set in past *session* of the session.

**Comment by uliska** [comment]
I implemented this and fixed the current issue (0b666b0f), but I now see that switching to "no session" does *not* close documents. So I have made the manuscript behaviour consistent with the documents' behaviour. We may discuss this independently.

**Comment by PeterBjuhr** [comment]
>I implemented this and fixed the current issue (0b666b0), but I now see that switching to "no session" does not close documents. 

Yes, it's how I remember it as well. But when I tried it the documents was closed. It should be mentioned that I currently have an issue with the sessions menu (see #696). I didn't think that would influence anything but perhaps it does.

>So I have made the manuscript behaviour consistent with the documents' behaviour. We may discuss this independently.

I think it should be consistent with what happen with other open documents, but maybe I cannot judge what actually happen at the moment. :)

**Comment by uliska** [comment]
I just confirmed on Windows with the installer release. Switching to "no
session" doesn't affect the opened documents in the editor or the music
view.

I think this makes sense because one might want to create a new session
from that current state. That means we can leave it at our current state.
