### ISSUE TITLE
Manage multiple manuscripts with the session

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#723]
Followup to #710, requires #722 to be completed.

When the document chooser is in place for the manuscript viewer we need to update the session logic accordingly. Probably one can have a look at how the music view handles that.

**Comment by uliska** [comment]
I've now implemented the session logic in 8aa6e8e4.

However, I'm not 100% sure that it's completely clean what we're doing with the document chooser. I'm somehow worried that we're mixing up things with filenames and documents, and the way the original document chooser navigates between editor documents and generated PDFs, weakrefs etc.

While everything works I'm feeling slightly uneasy about it.
So please @PeterBjuhr think about this before closing the issue.

**Comment by PeterBjuhr** [comment]
I think the current implementation is in line with our approach of extending the existing logic. But I agree in this case it's complex and confusing especially in the way document refers to different things. 

I think we do need to look into this some more. And maybe a better approach is found.

Nevertheless here is the basics:

`self._document` is the LilyPond document (`document.Document`). We don't use this variable at the moment. But we may want a connection to the document in the future.
`self._documents` is a list of `documents.Document` so this we can use. But originally they are grouped by the LilyPond document (`documents.group(self._document).documents()`), and without a connection to the editor document we have to handle the list differently.
`self._indices` a `weakref.WeakKeyDictionary` (a special form of dictionary), this may be our biggest problem at the moment. Originally this uses the LilyPond document as keys, but we can't do that for now.

**Comment by uliska** [comment]
Yes, that's about what I thought too.

What would you think about closing this issue now and opening a new one to be taken care of when we have finished doing everything else?

I think we really have to sort out things, now that we intend to support more than one viewer. The relation between editor documents and viewer documents is somewhat blurred currently (not our fault, but our functionality extensions make it necessary to deal with it in a new way).

**Comment by PeterBjuhr** [comment]
If it is helpful to rename certain variables I think we can do that right away. But overall I think we shall continue our basic idea of inheriting from what basically is a copy of the existing Music viewer and at a later step deal with the optimal structure. I think it's better to keep those steps apart. Important insights can be documented of course.

**Comment by uliska** [comment]
Yes. Closing for now
