### ISSUE TITLE
Clear manuscript chooser when closing manuscript

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#725]
When closing documents in any way the document chooser isn't emptied

**Comment by uliska** [comment]
The list is stored during the app's lifetime, so after restarting Frescobaldi everything's fine again.

**Comment by uliska** [comment]
Now documents are closed one by one, and the list is properly updated.
Session management has to be done, though
(manuscripts are not saved to a session anymore)

**Comment by uliska** [comment]
I reopen it that @PeterBjuhr can comment on the functionality. I think that it is good to close manuscripts one by one, but one could also think that the button should close all manuscripts at once. Or one could want to have additional actions "close all" and "close other" (although I'd prefer to have all these bundled in one dropdown button like the global Save/Save all button.

And: Should this action/these actions be added to the context menu or is that superfluous?

**Comment by uliska** [comment]
Update:
Added `manuscript_close_other` and `manuscript_close_all` actions but didn't add them to the toolbar (or integrate them in the current "close" button.

**Comment by PeterBjuhr** [comment]
Especially close all can be useful I think.

I think that the toolbar is pretty crowded by now, and that we should carefully what is most important to have there. More stuff can still be added to the context menu I think.

**Comment by uliska** [comment]
I will have a look at how the "Save all" dropdown button is implemented. This would be a consistent and space-saving solution.

**Comment by uliska** [comment]
No, this wouldn't be consistent. The global toolbar also only presents the single "close" button and provides the alternatives in the (context) menus only.

I'll open a (general) feature request to add the actions to the close button, though. We can then copy the functionality, but I wouldn't want to make our initial release depend on that.

**Comment by uliska** [comment]
I've now implemented the "close" actions in the context menu.
I've changed the viewer's context menu to be a (lightweight) object instead of global functions.
This makes it possible to implement the [template method pattern](https://en.wikipedia.org/wiki/Template_method_pattern), which modularizes the context menu and allows subclasses to override only parts of the generation.

@PeterBjuhr please have a look at it and close the issue if you are happy with it.

**Comment by PeterBjuhr** [comment]
Yes, I think this can now be closed.
