### ISSUE TITLE
Should manuscripts be sorted (and labelled) in the combobox?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#727]
Currently the manuscript chooser combobox is arbitrarily sorted.

Should this be somehow sorted alphabetically?
Or, as a compromise, should files be sorted alphabetically when they are opened in batch mode (i.e. multiple files from the file open dialog?

And: Should there be a way to display the full file path? Currently there's no way to distinguish different PDFs with the same name from different directories.

**Comment by uliska** [comment]
I think I'll change `openManuscripts()` so the files are sorted by their basename.
When saving/loading sessions the sorting is kept (AFAICS), so that's the place.

Is there a way to add tooltips to items in a combobox? If so, then I'd suggest adding the full path as a tooltip (although I don't know yet how).

**Comment by uliska** [comment]
Manuscripts are now sorted by their file basename. Was harder than expected due to handling duplicate file names from different folders.

I didn't find a solution to assign the full file names to the combobox items, though.
If you see a solution please add it, otherwise we can close the issue, as it isn't a requirement.

**Comment by PeterBjuhr** [comment]
I must say that I'm not totally convinced that the we should sort alphabetically. Do we have that kind of thing anywhere else? As I see it gives the user less control. But haven't had time to familiarize myself with your ideas here so maybe there's something I'm not seeing!?

**Comment by uliska** [comment]
I think this is due to the fact that the combobox is somewhat alien to what we do. The musicview's combobox is always populated automatically, and there is no combobox for the editor documents.
However, while the `Documents` menu is sorted according to the order of the open tabs the `documents` tool *is* sorted alphabetically.

As I found the list of manuscripts in the combobox quite confusing and as it seems overkill to implement a hierarchical display I think the alphabetical sorting is the most consistent thing we can design.
Actually I would probably prefer a tabbed interface because that gives access to a different manuscript by one instead of two clicks, and one always sees what is open. However, that would take yet another "row" of screen estate.

**Comment by PeterBjuhr** [comment]
I agree tabs is better to handle multiple documents. We could ask the users how many documents they would typically work with.

**Comment by uliska** [comment]
Maybe then (if we should use tabs instead of the combobox) it might turn
out that we'd be better of to implement this from scratch instead of
inheriting the DocumentChooser action. Maybe this would even sort out
the naming issues we ran into.

**Comment by PeterBjuhr** [comment]
As you said before the vertical space is valuable, so I kind of hope the answer will be "not many".

**Comment by uliska** [comment]
I think the initial question has been answered (yes: sort) and the tabs issue is a separate one and dealt with in #732.
