### ISSUE TITLE
Alternative access to manuscript actions

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#728]
Is it acceptable to have some actions of the manuscript viewer only accessible through their tool buttons?
It's possible to assign keyboard shortcuts but this is quite hidden in the "other commands" part of the Preferences page.

Shouldn't everything be accessible through keyboard navigation, i.e. through a proper menu? Although it's surely inacceptable to add a top-level menu for this tool

**Comment by PeterBjuhr** [comment]
Keyboard navigation is not necessary for all UI-elements, I think. But it should of course be easy to set up keyboard shortcuts for the things that is often used.

**Comment by uliska** [comment]
The Preferences are organized around the mainwindow's menu structure. Everything else is stuffed in an "other commands" section where it's difficult to find them because you see only the basic action text.

We should check if it's possible to add action groups to that, so that maybe the "other commands" are grouped by their parenting actionCollection.

**Comment by PeterBjuhr** [comment]
That's a good idea (not strictly related to the manuscript viewer though).

**Comment by uliska** [comment]
Not *strictly* related, yes. But it would make configuration of our new tool much easier for the user.

So I suggest we keep it open and consider it as related to our release, but not blocking. So we can decide at any point to simply remove the milestone from the issue.

**Comment by uliska** [comment]
I looked at the code in `preferences.shortcuts`, and I must admit it's too complicated right now, I just don't feel like jumping in yet another cold water ATM.

**Comment by PeterBjuhr** [comment]
I think the main issue with the shortcuts is #729, but admittingly it would also be nice to improve things further.

**Comment by uliska** [comment]
I think this is implemented in the shortcut preferences by now, and everything else is either resolved or discussed elsewhere. So @PeterBjuhr I think we can close this.

**Comment by PeterBjuhr** [comment]
Yes, I have nothing further to add.
