### ISSUE TITLE
Possible conflict in shortcuts

### ISSUE THREAD

**Issue by PeterBjuhr** [wbsoft/frescobaldi#729]
First of all we shouldn't set the shortcuts in the parent class because that would give the same shortcut to all childs. 

We should also make sure there is no conflict by naming.

**Comment by uliska** [comment]
Reload -> F5 doesn't work

**Comment by PeterBjuhr** [comment]
No, that is likely an example of a conflict because this shortcut is also set in the [musicview](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/musicview/__init__.py#L335).

**Comment by PeterBjuhr** [comment]
The list of shortcuts in the preferences uses the Action's set text. Then perhaps this shouldn't be set in the base class either. Although it wouldn't be a problem with all the childs having the same text (e.g. "Zoom In") it potentially very confusing when trying to set a shortcut.

**Comment by uliska** [comment]
The problem is that in, say, the manuscript viewer's context menu I very much prefer reading "Zoom In" and not "Manuscript: Zoom In".

**Comment by PeterBjuhr** [comment]
With 1c4a2afb43be881c018ccd5628e5e2ffae5f3a3f I think the naming problem may be solved. But we still need to avoid conflicting default shortcuts.

**Comment by PeterBjuhr** [comment]
Now I think we're avoiding conflicts.
