### ISSUE TITLE
Should manuscripts be chosen by the combo box or by tabs

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#732]
This is a question for the reviewers.

Currently multiple manuscripts are managed by a combo box that is derived from the document chooser for the general music viewer. However, it might also be useful to have them displayed in tabs, like the documents in the text editor. This would make it more apparent which manuscripts are opened, and it would reduce switching to one click instead of two. OTOH tabs would take one "row" of screen estate, so we are not sure what's the best approach.

Reviewers please comment.

**Comment by fedelibre** [comment]
Screen estate is more important IMO. I'd prefer being able to hide the manuscript toolbar, for example. Once I've loaded the PDF manuscript I don't really need all those buttons (I can scroll pages, zoom in and out with mouse and keyboard).

**Comment by uliska** [comment]
Good idea. @pbjuhr do you have an idea how that could be accomplished? My first suggestion would be an action to toggle the toolbar that is triggered with a keyboard shortcut or through the context menu.

In that context could we extend the contextmenu with a submenu giving access to the other opened manuscripts. This should be in the base class as it will also be useful for the music view.

Actually the toggle should also be defined in the base class because we will pull the music view's toolbar into the panel too.

**Comment by PeterBjuhr** [comment]
Yes, spacing is definitely a factor here. @fedelibre I also interpret your comment such that you will mostly be using a single manuscript!?

The toolbar can easily be hidden by `setVisible(False)`. But we have to carefully consider the user experience aspect here. (The discussion in #470 also comes to mind.)

**Comment by fedelibre** [comment]
@PeterBjuhr yes, most of the times I'll use a single manuscript.

Perhaps you may add Viewers Preferences? (as there are the Editor preferences) It may be useful to manage other related stuff? Issue #728 contains some ideas on this subject.

**Comment by uliska** [comment]
I will create an action that toggles the toolbar's visibility.
To achieve that I will change the (somewhat quirky) "use_layout" implementation of `AbstractPopplerView` and make that base class always have a toolbar.

**Comment by PeterBjuhr** [comment]
>Perhaps you may add Viewers Preferences? (as there are the Editor preferences) It may be useful to manage other related stuff? Issue #728 contains some ideas on this subject.

I think preferences could be a good idea. But the choice between tabs and the current UI would require very different implementation so here I think the demands of the majority have to rule.

@fedelibre were you thinking also more specifically about the hiding of the toolbar, e.g. on a preference to always hide the toolbar?

**Comment by uliska** [comment]
I agree that tabs/combobox is too complex to be put in the preferences.
Anyway, I have now implemented an action to toggle the visibility of a viewer's toolbar. This can be accessed through the context menu and also assigned a shortcut. I think that doesn't need a preferences page (for now). But I think the current state should be saved and retrieved from preferences (this is a case for application preferences and not for sessions, I think).
See #735.

**Comment by uliska** [comment]
See also #736 for an idea to access the other manuscripts when the toolbar is hidden

**Comment by fedelibre** [comment]
I'm not sure what would be best.. Personally, I'd probably be happy with a preference to always hide the toolbar (especially once issue #734 is fixed). Otherwise, a small button besides Manuscript to toggle the toolbar might be a good compromise.

**Comment by uliska** [comment]
I think when the current visibility state is stored automatically you don't need an explicit preference anymore.

**Comment by fedelibre** [comment]
I agree.

I've checked-out this commit 7c0d6d8a48bbe49bb102b4aa19239ae6ac98499b
What should I expect from it? (I can't see any way to toggle any toolbar)
Still work in progress?

**Comment by uliska** [comment]
You should have an entry near the bottom of the manuscript viewer's context menu. And there should be an entry in the Manuscript section of the Keyboard Shortcuts preferences.

**Comment by fedelibre** [comment]
If I right-click on Manuscript, I have only:

- "Main toolbar" and "Music View toolbar", which toggle the main toolbar on top
- "Tab bar", which toggles the tabs in the code editor

**Comment by uliska** [comment]
You should click somehwere *inside* the manuscript viewer, i.e. where the manuscript is displayed. This is where you can access all the functionality of the tool.
What you clicked on is some context menu of the global application window. I think we will remove the "Music view toolbar" entry from that because later we will have the music view's toolbar inside too, just like now with the manuscript viewer.

**Comment by fedelibre** [comment]
Ok, got it.
Great, I feel just 2 features away from perfection (remember manuscript page and toggle toolbar preference).

**Comment by uliska** [comment]
Would you mind doing some "stress tests"?
What happens for example when you open a session that contains
manuscript(s) that are not present on disk anymore? When that's the
active one? When *no* manuscript is there anymore?
Or anything else that might crash the viewer (or otherwise lead to
unexpected behaviour).

**Comment by fedelibre** [comment]
I've tried these tests with two manuscripts loaded:

1. moving one manuscript in a different directory does not affect the current session, i.e. I can browse the pages without any problem. When I restart the session, the file name is remembered but no PDF is displayed. Perhaps instead of a grey area a message could be helpful: "Hey, the manuscript file has changed location. Please open it again.".

2. Same happens if I move the other manuscript.

At any rate, no crashes at all.

**Comment by uliska** [comment]
Thanks, this isn't desirable behaviour (and when I last checked it it didn't behave like that. Obviously the session handling code did some changes to that.
See #738

**Comment by PeterBjuhr** [comment]
>moving one manuscript in a different directory does not affect the current session, i.e. I can browse the pages without any problem. 

Changes to the manuscript will not be viewed unless 'reload' (in the contextmenu) is triggered.

(The easiest way to test this is to open the same pdf as in the music viewer and make some changes to the LilyPond document.)

**Comment by PeterBjuhr** [comment]
>Anyway, I have now implemented an action to toggle the visibility of a viewer's toolbar. This can be accessed through the context menu and also assigned a shortcut

I think this is somewhat consistent - you can also hide the toolbar for the music viewer if you like. 

Two minor details though:

1. It can be a little counter-intuitive that you need to right-click on the actual manuscript viewer and not on the toolbar itself or close to it.

2. In analogy with the other toolbars, the action should be checkable (if you compare with the other toolbars, or with e. g. `Synchronize with Cursor Position`, I think you'll see what I mean.

1. I don't know if we should try to do something about.

2. I'd like to change right away! @uliska ?

**Comment by uliska** [comment]
Am 19. Juli 2015 15:36:13 MESZ, schrieb Peter Bjuhr <notifications@github.com>:
>>Anyway, I have now implemented an action to toggle the visibility of a
>viewer's toolbar. This can be accessed through the context menu and
>also assigned a shortcut
>
>I think this is somewhat consistent - you can also hide the toolbar for
>the music viewer if you like. 

Yes. Abd we will nake it even more identical later.

>
>Two minor details though:
>
>1. It can be a little counter-intuitive that you need to right-click on
>the actual manuscript viewer and not on the toolbar itself or close to
>it.

Maybe. But that way you can show it again from the same place where you hide it.

>
>2. In analogy with the other toolbars, the action should be checkable
>(if you compare with the other toolbars, or with e. g. `Synchronize
>with Cursor Position`, I think you'll see what I mean.

Yes. I realized that too but didn't have an opportunity to to something.
I would also rename it to "Show toolbar" which would make it more consistent with checking.

>
>1. I don't know if we should try to do something about.
>
>2. I'd like to change right away! @uliska ?
>

Go ahead. I'll be off today.

**Comment by PeterBjuhr** [comment]
Done.

**Comment by uliska** [comment]
Thanks.

Do I see it right that this state isn't saved permanently?
Should be in the QSettings (but without an explicit Preference entry), not in the session.

**Comment by PeterBjuhr** [comment]
Yes, I'll fix this aswell.

**Comment by uliska** [comment]
For the record: The visibility of the toolbar is now automatically remembered. See Peter's d197aa9d

**Comment by uliska** [comment]
I think everything in this issue has been discussed/implemented except the original question. And this has been moved over to #739.
So @PeterBjuhr if you come to the same conclusion you should close this issue.

**Comment by PeterBjuhr** [comment]
My interpretation of your conclusion is that we take the idea with us for future development but that we don't consider it more at this point.

After some use hopefully we have a better overview of what is already good and what needs improvement.

**Comment by uliska** [comment]
Nearly. I think I find this idea good already, but similar to the integration with the manuscript viewer it's just too make it a requirement for the initial release.

**Comment by PeterBjuhr** [comment]
Still, I think we agree we can close this.

**Comment by uliska** [comment]
Yes, that was the intention.
