### ISSUE TITLE
save manuscript position in session

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#734]

**Comment by uliska** [comment]
OK. This is a good idea. But since the manuscript view doesn't do this either we will postpone that and take care of it when we start integrating the tools (i.e. let the manuscript viewer also inherit from our new base class).

**Comment by PeterBjuhr** [comment]
A related question which I'm not sure if it deserves an own issue: should the position be remembered when the document is reloaded?

**Comment by uliska** [comment]
I think so. That would be more consistent. When you switch back and forth between manuscripts (and music previews) the positions are restored too (well, I think not "restored" but the documents are simply kept in memory).

If we implement the functionality to save the positions in the session it should be quite easy to take ues that when reloading.

**Comment by uliska** [comment]
This is a duplicate (or rather has been merged into) #735
