### ISSUE TITLE
Viewers should get a contextmenu submenu giving access to the alternative documents

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#736]
Now that we can hide the viewer's toolbar the main thing that would probably be needed to be accessible is the list of open documents/manuscripts.

I suggest implementing a contextmenu subment that opens up to the list of open manuscripts and switches to the selected doc.

**Comment by PeterBjuhr** [comment]
The contextmenu is quite crowded already so I'm not sure this is a good idea. Also following the reasoning behind why the toolbar could be hidden in #732 it had much to do with working with a singular manuscript. Perhaps it is no problem that while the toolbar is hidden some commands are in fact not accessible.

**Comment by uliska** [comment]
> The contextmenu is quite crowded already so I'm not sure this is a good idea. 
You're right about the contextmenu. However, I think it *is* a good idea (now more than before).

The fundamental reason for hiding the toolbar is not in using a single manuscript but in saving screen estate when everything important (especially (and explicitly) zooming and scrolling) are available through other means (mouse, contextmenu). This is equally true when working with one or multiple manuscripts. 

I think when we allow hiding the toolbar we should make sure all important functionality can be accessed without having to show the toolbar first. The print button may be an exception because that's (probably) not a regular task. But switching between documents should definitely be accessible through the contextmenu and/or keyboard shortcuts.

I would rather suggest combining things further. The zoom actions could definitely be grouped in a submenu (as you'll probably do that with the mouse wheel most of the time), probably also the three close actions.

I will first implement that grouping and then come back to the original question.

**Comment by uliska** [comment]
OK, I've implemented it and completely reviewed the context menu. It is now grouped by meaningful parameters:

- actions affecting the current link/selection  
*Note:* The "edit in place" item doesn't show up anymore (#740)
- actions affecting the opened documents  
(I will add the "Show" submenu above the "Close" submenu)
- actions affecting the viewer's global state.

When checking make sure to also open it on a link and on a selection.

**Comment by uliska** [comment]
*Edit:* The "edit in place" issue was a false alarm.

**Comment by uliska** [comment]
The main issue has been merged with the #742 pull request. Everything else has been solved.
