### ISSUE TITLE
Proper handling of missing manuscripts

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#738]
When reopening a manuscript (from a session) that doesn't exist anymore the manuscript viewer is empty, but the filename remains in the session and the document chooser (on my system the file icon disappears, which is an indicator).

However, this isn't really consistent. The file should either be also removed from the session or - better - we should provide a) a stronger indication of the missing file and b) an interface to reopen it.

For b) it isn't sufficient to open the file open dialog because its result would only replace the missing file if it has the same file name (and maybe if it also has the same absolute path, I'm not sure). So what we need is an action "searchForMissingFile" that will return just one file and in any case remove the missing file from the list.

**Comment by PeterBjuhr** [comment]
>However, this isn't really consistent. The file should either be also removed from the session or - better - we should provide a) a stronger indication of the missing file and b) an interface to reopen it.

Now the manuscript is silently removed from the chooser if it can't be found. I don't think we need a special session handling. But the user should be better informed that the file couldn't be found. (I don't think we need to guide the user which action to take, the information should be enough.)

**Comment by uliska** [comment]
Thanks, that's better.

Do you think a pop-up information is OK, or is that too intrusive?
Where could the information be put otherwise?

We have to take into account that it can be more than one missing document.

**Comment by PeterBjuhr** [comment]
I don't know if we have any option besides a pop-up. But you're right - let's say a whole folder with opened manuscripts have been moved then it wouldn't be nice with a pop-up for each document.

**Comment by uliska** [comment]
A pop-up can be closed with [Enter] or [Esc] so the intrusiveness is
somewhat alleviated.

And of course this should be only one pop-up with a report of missing
files (as I've outlined in the initial post).

**Comment by uliska** [comment]
I've done an implementation. Please check

a) if it behaves like it should and
b) if the dialog should be more polished.

**Comment by uliska** [comment]
@fedelibre you were the one who noticed this issue. Would you mind checking if everything works properly now?

**Comment by fedelibre** [comment]
I think it's working properly:

- the popup warning about deleted/moved file works fine
- the manuscript is remembered within a session

But the page opened in the manuscript is not remembered. This is issue #735? (sorry, no time to read all the comments)

**Comment by fedelibre** [comment]
Wait, I've just realized that only a single manuscript can be remembered.
If you open more than one manuscript, only one will be remembered (the first you opened).

**Comment by uliska** [comment]
I don't fully understand what you mean.
There is one known limitation:
If you have more than one manuscript open each manuscript's position (page and page position) is kept *during the session*. That means you should be able to switch back and forth between the opened manuscripts and have each re-show at the previous position.

If you switch sessions or restart Frescobaldi only the position of the manuscript is remembered that was visible at that moment.

If this is what you mean then yes, this is the "loose end" in #735 where I suggest to settle with and implement it at a later point after changing some infrastructure.
If this is *not* what you mean could you then please explain more concretely what is happening?

**Comment by fedelibre** [comment]
Ok, I understand.
Everything works fine during the session. But when I restart Frescobaldi and reopen the session, only one manuscript is loaded.

**Comment by uliska** [comment]
What are your session settings?

In the session itself (automatically save files)?
Preference to open session on startup?

**Comment by fedelibre** [comment]
> In the session itself (automatically save files)?

"Always save list of documents in this session" was unchecked and if I 
check it it works correctly.

**Comment by uliska** [comment]
Then behaviour is correct :-)

**Comment by uliska** [comment]
Then I consider this fixed until someone complains again.
