### ISSUE TITLE
Edit in place menu item has vanished

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#740]
For some reason the "Edit in place" item in the context menu of the manuscript viewer isn't there anymore.

In `viewers.contextmenu.ViewerContextMenu.addCursorLinksActions()` the `cursor` argument seems always `None`. So the issue must be in the stage when calling the context menu is prepared.

**Comment by PeterBjuhr** [comment]
The item is still there, but it will not show up unless you click on a link.

**Comment by uliska** [comment]
Hm, yes. But when I click on a link it only shows the two link entries
but not the "edit in place" one.
printing shows that cursor == None then.

**Comment by PeterBjuhr** [comment]
Maybe there's something strange with the link!? I confirmed it with your latest commits. If there is an issue it's not that the menu item is completely gone.

**Comment by PeterBjuhr** [comment]
If you open the same document in both the music viewer and the manuscript viewer can you confirm the result is different?

**Comment by uliska** [comment]
OK, you're right. There must have been something wrong with my concrete documents.
