### ISSUE TITLE
When creating new session, manuscripts are cleared

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#741]

**Comment by PeterBjuhr** [comment]
This I can confirm! :)

**Comment by uliska** [comment]
Should  be fixed now. But it would be good to test it with other situation.

**Comment by uliska** [comment]
Well, I didn't do *very* thorough specific tests, but I think any issue should have come up by now. If I missed anything someone could simply open a new issue.

**Comment by uliska** [comment]
No, unfortunately this hasn't been fixed (see reverted commit)

**Comment by uliska** [comment]
Seems fixed

**Comment by PeterBjuhr** [comment]
@uliska can you confirm that this is now resolved?

I have considered both that new sessions should retain current manuscripts and that existing sessions (both old and new) should not.

**Comment by uliska** [comment]
Yes, it works as expected now. When creating a new session both the editor documents and the manuscripts are kept and automatically form the basis of the new session.
