### ISSUE TITLE
Sorting out the "Document" naming issue

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#748]
We have a name clash with `document` in all its variants. This stems from the fact that Frescobaldi calls the *input files* in LilyPond input language "documents" but also the PDF files displayed in the music view. When working on the manuscript viewer we added to the confusion by partially keeping this "document" naming scheme and partially adding "manuscript" elements.

I think we should keep "document" for the input documents but find a new name for the entity that is displayed in a viewer. This doesn't necessarily have to be a PDF but will eventually also include other file formats or even "files" compiled from a set of individual images.

What we're looking for is a generic name that can can refer to a LilyPond generated score, a manuscript file but also arbitrary display files, for example a list of annotations. Probably it would be good if the name somehow refers to "display", but I admit I haven't had a good idea so far.

I would prefer (but not insist on) doing such a renaming operation within the first release so we have a cleaner starting position for future integration of the different viewers. But OTOH one could equally say that this *is* part of the integration discussion and should be postponed - as it doesn't amek anything unusable in the current state.

**Comment by PeterBjuhr** [comment]
I guess what I would call them would be 'editor documents' and 'viewer documents'. So the most straightforward would be to call them `editdocs` and `viewdocs` or something like that!??

**Comment by uliska** [comment]
Just to note: I'm working on this on a feature branch.

**Comment by uliska** [comment]
Just merged this with 70524e43.

The branch should cover everything in the panel, widget and contextmenu classes but not (at least not comprehensively) in the document chooser classes.
However, I wanted to merge this in order to reduce the risk of conflicts.

I'm quite sure that all *methods* are now renamed appropriately, and this *should* make the coding itself consistent. However, I did *not* go through the whole code to make sure this really is the case. Maybe local code inside methods still uses the old "document" naming scheme.

**Comment by uliska** [comment]
@PeterBjuhr I think this can be closed now.

**Comment by PeterBjuhr** [comment]
Yes, now hopefully the naming is clear(er)!

**Comment by uliska** [comment]
There's one more thing I was stumbling over: There are two methods
openViewdocs(), one in AbstractViewPanel, the other in the viedocChooser
base class. Maybe one of them could/should be renamed?

**Comment by PeterBjuhr** [comment]
It might be by habit but a liked the 'load...' name better (`ViewdocChooser`). I think it is more descriptive.

**Comment by uliska** [comment]
Sounds good. Would restore the difference between load and open.
