### ISSUE TITLE
Manuscript viewer (and others) should only be created when necessary

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#752]
Follow-up to #751 and comments to dd8891f58b4c4ac73b959378d4db3a8b4cc59319

The manuscript viewer is currently created regardless of whether the tool is open or not. This adds to the application startup time and isn't in line with the concept of creating stuff only when needed.

As the manuscript viewer will become the base code for other viewers this is quite important to fix properly.

**Comment by uliska** [comment]
It seems that *all* panels are instantiated on application startup. @wbsoft is this really your intention? If so, adding new panels would significantly add to application startup time.

Wouldn't it be possible for the panelmanager to only instantiate a lightweight "wrapper object" providing not more than the `toggleViewAction` with its text and a caching factory method that instantiates the panel upon the first request?

**Comment by uliska** [comment]
Re-added the initial release milestone

**Comment by uliska** [comment]
I*ve identified part of the problem. When creating the panel `slotShowToolbar()` was called that creates the widget. 

I have removed that problem and could confirm that the whole `__init__()` of the panel completes, but still the widget is created *after that* upon application start.

**Comment by uliska** [comment]
Could verify that `panelmanager.loadPanel()` doesn't trigger the creation of the widget. The panel is created in the queue of panels, then all other panels are loaded, and only after that the manuscript viewer's widget is created

**Comment by uliska** [comment]
Found it. Loading the session upon startup caused `widget()` to create the widget.

I've suppressed this by connecting the session slots in the `__init__` of the widget. This works, but I'm not 100% sure if that's really correct because it feels slightly awkward to connect from `Widget` to a method in `Panel`.

@PeterBjuhr please comment on that and decide whether the issue can be closed.

**Comment by uliska** [comment]
No it can't be closed. The toolbar fix (8485d215) caused #735 to reappear in a different incarnation.

**Comment by PeterBjuhr** [comment]
As mentioned in #760 I think this is now fixed.
