### ISSUE TITLE
Don’t auto-compile after using ‘New from Template’

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#765]
After creating a new document through ‘New from Template…’, Frescobaldi immediately does a first run of LilyPond. This is fine if the file contains only variable definitions, but if the file is not supposed to be compiled on its own and uses variables not defined within itself, this is pointless and results in numerous markings.
Certainly there is a reason for this design, but to accomodate different workflows and different kinds of templates, it would be nice if this were at least configurable.
Example template:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<snippets>

<!--
  Created by Frescobaldi 2.18.
  
  Every snippet is represented by:
    title:      title text
    shortcuts:  list of shortcut elements, every shortcut is a key sequence
    body:       the snippet text
  
  The snippet id attribute can be the name of a builtin snippet or a random
  name like 'n123456'. In the latter case, the title is used to determine
  whether a snippet is new or updated.
-->

<snippet id="n030982">
<title>Dummy test template</title>
<shortcuts />
<body>-*- template; indent: no;
\score {
  \music
  \layout { ${CURSOR}}
}</body>
</snippet>

</snippets>
```

**Comment by PeterBjuhr** [comment]
There has been discussion before about the auto-compiler running on files not supposed to be compiled.

One workaround at least for templates could be to leave something open, e.g:

````lilypond
music = { 
  \global
````

Then the auto-compiler doesn't run before the brackets are closed. 

@sincere-music but what you're suggesting is a setting of some sort to exclude newly created files from templates from auto-engraving!?

**Comment by sincere-music** [comment]
I don’t have auto-engraving enabled. The described behaviour is in spite of this.

**Comment by PeterBjuhr** [comment]
Sorry for the misunderstanding!

Remove `template-run` from the first line of the template snippet and you will not get the first run you describe.

**Comment by sincere-music** [comment]
On 21.09.2015 21:10, Peter Bjuhr wrote:
> Remove |template-run| from the first line of the template snippet and 
> you will not get the first run you describe.

OK, I see! But should this be the default, then? I created the template 
snippets using ‘Save as Template’. Maybe a checkbox could be included in 
this dialogue, like ‘Run lilypond when applying this template’? That 
might save some confusion and irritation.
--
Yours, Simon

**Comment by PeterBjuhr** [comment]
>Maybe a checkbox could be included in this dialogue, like ‘Run lilypond when applying this template’? 

Sounds like a good idea to me.

**Comment by wbsoft** [comment]
Indeed the autocompiler should better not run on New from template. A template that should run the engraver can be marked with 'template-run'.

**Comment by sincere-music** [comment]
I don’t know python, so I can’t review the fix, but did you read the discussion above? My problem was not with the actual auto-compiling feature, but that using ‘File/Save as Template…’ includes `template-run` in the first line of the snippet created.

**Comment by wbsoft** [comment]
Ah, yes I see the are actually multiple issues at hand. Your solution, adding a check box in the save as template dialog (which is checked by default when the file looks complete and has output (e.g. toplevel music or markup), the situation where the 'template-run' line would be added) is very good, I will implement that!

**Comment by sincere-music** [comment]
Thank you!
