### ISSUE TITLE
Support more than 10 available LilyPond versions

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#767]
Yesterday I added LilyPond 2.19.28 to the ‘Versions to use’ in the LilyPond preferences tab. This didn’t work, 2.19.28 wasn’t automatically launched with `\version "2.19.28"`, and when I reopened the Preferences dialogue, it had disappeared from the list. It seems like there is a limit of 10, since this was the eleventh version of LilyPond that I had installed. Could this limit be raised, or do we need a limit at all?

**Comment by uliska** [comment]
I can't actually see any explicit limit in the code. Saving simply iterates over the items in the list box and saves them as an array (in `lilypondinfo.py`).

Maybe there's such a limit in PyQt's `QSettings`? Sounds improbable.

Would you mind do some more checks, maybe also with some combinations of default versions?

**Comment by sincere-music** [comment]
On 05.10.2015 11:26, Urs Liska wrote:
>
> I can't actually see any explicit limit in the code. Saving simply 
> iterates over the items in the list box and saves them as an array (in 
> |lilypondinfo.py|).
>
> Maybe there's such a limit in PyQt's |QSettings|? Sounds improbable.
>
> Would you mind do some more checks, maybe also with some combinations 
> of default versions?
>

Sorry, but I couldn’t reproduce it. Which is bad, since obviously there 
was some problem, but either it’s very particular or coincidential.

Yours, Simon

**Comment by uliska** [comment]
OK, I close it for now. If it comes up again (in a reproducible manner) feel free to re-open or add a new one.
