### ISSUE TITLE
Score wizard: distinguish ‘proper’ and ‘rotated’ landscape formats

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#768]
There has been a small discussion on page orientation in the thread starting from
http://www.mail-archive.com/bug-lilypond@gnu.org/msg40138.html.
I’m quite sure that I learned about the
   `#(set-paper-size "a6" 'landscape)`
syntax through the Frescobaldi score wizard, and it turns out that the more reliable way to invoke landscape formats, especially WRT output formats other than .pdf, is
   `#(set-paper-size "a6landscape")`

I can’t completely wrap my head around the essence of this distinction, but I think it would be better to use the latter in the score wizard, or provide more sophisticated support allowing a choice between both. Documentation is in [NR 4.1.2](http://lilypond.org/doc/v2.19/Documentation/notation/paper-size-and-automatic-scaling).

**Comment by sincere-music** [comment]
The `"a6landscape"` syntax has been introduced with [Issue 2737](http://sourceforge.net/p/testlilyissues/issues/2737/).

**Comment by wbsoft** [comment]
Thanks for adding this issue. It is a good point, and we can always use the old flag when an old Lily is used.

**Comment by fedelibre** [comment]
I would add a priority label, because since version 2.19.60 the 'landscape syntax will return a rotated PDF. See:

- http://lists.gnu.org/archive/html/lilypond-devel/2017-05/msg00021.html
- http://lists.gnu.org/archive/html/lilypond-devel/2017-05/msg00024.html

**Comment by uliska** [comment]
I've fixed the wrong code generation. Checking `landscape` will now properly append to the paper size instead of adding the extra argument. This is backward compatible at least to 2.18.

It does *not* add the functionality to distinguish between landscape and rotated, though.

**Comment by uliska** [comment]
The "new" syntax is valid since LilyPond 2.16.1, so I don't think we should actually support the "old" syntax anymore. Keep in mind that this isn't something that might affect existing old scores but only the generation of new scores.

**Comment by uliska** [comment]
I've added https://github.com/wbsoft/frescobaldi/pull/943 that should implement this feature in a satisfying manner. Please test.
