### ISSUE TITLE
git support from within frescobaldi

### ISSUE THREAD

**Issue by bastl** [wbsoft/frescobaldi#777]
Please support version control in frescobaldi (esp. git) as in other IDEs.

**Comment by uliska** [comment]
See #102 - this is a quite long-standing wish from within the developer community. I'm more than sorry that we haven't been able to work on that feature more successfully. *Some* steps have already been taken, but they so far only affect the repository of Frescobaldi itself (that is: not any LilyPond documents) and are only available when you run Frescobaldi from Git.

**Comment by uliska** [comment]
I'll close this. Regardless of the success of this year's GSoC project this issue doesn't add anything new to the discussion
