### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by wbsoft** [wbsoft/frescobaldi#781]
Frescobaldi: 2.18.1 -- Python: 2.7.10 -- python-ly: 0.9.2 -- Qt: 4.8.7 -- PyQt: 4.11.4 -- sip: 4.17 -- poppler: 0.32.0 -- python-poppler-qt: 0.24.0 -- OS: Darwin-14.5.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frescobaldi_app/mainwindow.py", line 494, in openDocument
    ext = os.path.splitext(self.currentDocument().url().path())[1]
AttributeError: 'NoneType' object has no attribute 'url'

Optionally describe below what you were doing:

**Comment by wbsoft** [comment]
please test on a real mac. I still don't have one ;(

**Comment by dliessi** [comment]
I would, if I could understand what the problem is/was and how to trigger it.
Opening a file both with and without this commit works on my machine.

**Comment by wbsoft** [comment]
Maybe this bug triggers when a file is opened without a mainwindow open (i.e. when only the menu bar is there)
