### ISSUE TITLE
Let the transposing tool update octave checks

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#782]
Currently, using Tools->Pitch->Transpose… leaves octave checks unchanged, so they have to be updated manually.

**Comment by wbsoft** [comment]
will fix together with fixing relative without start pitch

**Comment by wbsoft** [comment]
(btw is in fact python-ly bug)

**Comment by wbsoft** [comment]
Can you provide an example? See wbsoft/python-ly#68

**Comment by sincere-music** [comment]
On 19.04.2016 15:32, Wilbert Berendsen wrote:
>
> Can you provide an example? See wbsoft/python-ly#68 
> <https://github.com/wbsoft/python-ly/issues/68>
>

Indeed I can’t. I wonder why… probably I’ve overlooked something when 
reporting the issue.

**Comment by wbsoft** [comment]
With python-ly-0.9.4 and Frescobaldi-2.18.3, both ways of `\relative {...}` (LilyPond <2.18 and 2.18+) are now understood.
