### ISSUE TITLE
‘Replace all’ only works when run twice

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#786]
When I use the Search & Replace feature (Ctrl+F, Ctrl+H) I always need to hit ‘[Replace] All’ (Alt+A) twice: the first time it will only change one of the instances, the second time all of them.
In case it is important: This is on Ubuntu.

**Comment by igneus** [comment]
I have a similar experience, but I should check how exactly it behaves now. I've simply got used to the fact that "Replace all behaves in a bit annoying way."

**Comment by wbsoft** [comment]
Problem is that it only replaces all occurrences in a selection, when there is text selected. When searching for text, the first match is selected; that's why only one occurrence is replaced. Search/Replace should be redone :-) (already on todo list)

**Comment by wbsoft** [comment]
related to #807
