### ISSUE TITLE
"Python[24277:613] unlockFocus called too many time."

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#791]
Sometimes when I scroll a long file, the editor window does not completely refresh and some lines of the previous text stay on the screen.
In these cases I get this warning on the console: "Python[24277:613] unlockFocus called too many time."

This happened to me many times (let's say at least 20?), but when I try to reproduce it I'm not able to trigger it.

It has just happened with the latest version run from command line.

**Comment by PeterBjuhr** [comment]
After a quick search it seems this is a Qt bug i OS X...

**Comment by wbsoft** [comment]
closing, please reopen if it is a Frescobaldi bug
