### ISSUE TITLE
wish: Snippet which "unfolds" music-functions 

### ISSUE THREAD

**Issue by infranator** [wbsoft/frescobaldi#796]
Would it be possible to write a python-snippet, which substitutes a music-function call with it's output of \displayLilyMusic?

Here's a small example:

\version "2.19.33"
example =
#(define-music-function (p1 p2 p3)
   (ly:pitch? ly:pitch? ly:pitch?)
   #{
     $p1 2 $p2 4 $p3
   #})

\example c' d' e'

% When the call of "example" is selected, the snippet should replace it with:
{ c'2 d'4 e'4 }

**Comment by PeterBjuhr** [comment]
I have some difficulty understanding exactly what you are after. The reasonable explanation to me is that you want a Python snippet that does what the Scheme function is doing, i. e. performs a similar substitution. In such a case - yes it is possible.

In Frescobaldi we have some built-in snippets the rest is up to the user to contribute. This may not be a good candidate for a built-in snippet. Perhaps I may mention instead https://github.com/PeterBjuhr/frescobaldi-snippets, a repo where I gather a few snippets. You can also make similar requests there! :)

**Comment by infranator** [comment]
Yes that's exactly what I want :)
I already had a feeling this was not the right place to ask.
Thank you for the link!

**Comment by PeterBjuhr** [comment]
Great, I close this then!
