### ISSUE TITLE
MIDI input doesn't work on Windows 8.1

### ISSUE THREAD

**Issue by unmostro** [wbsoft/frescobaldi#797]
MIDI input from external synthesizer (Yamaha) doesn't work on Windows 8.1 both with MIDI--USB and native MIDI-MIDI interface. At the same time MIDI output works well.
MIDI input interface itself is OK since the other application (MIDI-OX)  displays all input MIDI events correctly.

**Comment by unmostro** [comment]
Denemo version 2.0.0 with the same MIDI settings handles MIDI input perfectly.

**Comment by unmostro** [comment]
Denemo version 2.0.0 with the same MIDI settings handles MIDI input perfectly.

**Comment by HeyItsJustMe** [comment]
FYI same on Windows 10. So frustrating. Here: https://github.com/wbsoft/frescobaldi/issues/853
