### ISSUE TITLE
Wish: Zoom to more than 400%

### ISSUE THREAD

**Issue by PeteCrighton** [wbsoft/frescobaldi#800]
I don’t know if the way in which Frescobaldi currently displays PDF files limits the zoom to a maximum of 400%, but sometimes I find myself needing even more detail. Okular can display PDFs zoomed in to 1,600%, but even 800% (which was its maximum a few years ago) would be a nice improvement to Frescobaldi.

**Comment by wbsoft** [comment]
Indeed  that's desirable. It uses lots of memory, as one page is always generated as bitmap. But I'll change the limits!

**Comment by PeteCrighton** [comment]
Terrific, thanks!
