### ISSUE TITLE
Update layout control options to LilyPond 2.19.21 syntax

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#801]
Many of the layout control options are affected by a fundamental syntax change about using the `parser` argument in music-etc-functions.

The task is to wrap the offending calls in version predicate conditionals because Frescobaldi has to support older _and_ newer LilyPonds.

**Comment by ssmus** [comment]
In the meantime, users running from git can run convert-ly on frescobaldi_app/layoutcontrol/debug-layout-options.ly

**Comment by uliska** [comment]
But this will only work if they exclusively use lilypond-devel. That syntax change is breaking, so I need to install a LilyPond version switch.

(Sorry that I didn't have time to fix this yet).

**Comment by uliska** [comment]
Fixed in 80fed97e
