### ISSUE TITLE
include file name lookup on Windows

### ISSUE THREAD

**Issue by tobik** [wbsoft/frescobaldi#804]
Hello,

1. When I type `\include "..\` a listbox will pop up with all files and directories in the parent directory.  
2. The resulting text is something like `\include "..\globals.ily"`. But then Lilypond throws a error message: `Programmierfehler: file name not normalized: ..\globals.ily`
4. If the include is written with slash rather then backslash (`\include "../globals.ily"`), Lilypond will not throw a error message. 
5. But when I type `\include "../` Frescobaldi will not show the pop up listbox with files and directories.

Could Frescobaldi show this pop up even when I use slash as path seperator on Windows?

Regards, Tobias

**Comment by PeterBjuhr** [comment]
> If the include is written with slash rather then backslash (\include "..\globals.ily"), Lilypond will not throw a error message.

I think your report is clear enough, but did you mean: `\include "../globals.ily"`?

**Comment by tobik** [comment]
Oh yes, you are right.

**Comment by PeterBjuhr** [comment]
Thanks!

**Comment by wbsoft** [comment]
I see, that in Windows, also the forward slash is the normal separator used by LilyPond users? Then I should fix the include file complete data.

**Comment by wbsoft** [comment]
please test

**Comment by uliska** [comment]
This is something that is annoyingly ambiguous with LilyPond (see for example http://lists.gnu.org/archive/html/lilypond-devel/2016-01/msg00163.html and the following discussion).

It seems Guile more or less always uses the forward slash in its input. And of course this is crucial because otherwise documents would be incompatible across OSes.

**Comment by wbsoft** [comment]
That's a valid point. Let's educate the user and always present forward slashes in the UI and include autocomplete.

**Comment by tobik** [comment]
I suspect, the missing trigger that do autocomplete on slashes is not addressed by the patch?

**Comment by wbsoft** [comment]
Please test again (I do not have Windows available)

**Comment by tobik** [comment]
This works fine with the slash. Thank you!

What should happen if the user types a backslash? Is the autocomplete supposed to pop up but with slashes in the path? 

I tried both seperators in your second patch, but the autocomplete only pop up when the seperator coincide with the content of the autocomplete list (your first patch). To tell the truth, I don't know why but would like to know.

**Comment by tobik** [comment]
May I point out another issue? When I select a path from the autocompletion list it will put in the editor with a trailing slash. To get another autocompletion, I have to delete the slash and type a new one. 

Could the autocomplete popup again without any interaction? Or else remove the trailing slash from the autocomplete list?

**Comment by uliska** [comment]
> Could the autocomplete popup again without any interaction? Or else remove the trailing slash from the autocomplete list?

I think this might be a good idea: Initially do not add a trailing slash, and when the user types this after accepting the autocompletion present all the next suggestions

**Comment by wbsoft** [comment]
> What should happen if the user types a backslash? Is the autocomplete supposed to pop up but with slashes in the path? Or should it open with backslashes? Or should just no autocompletion pop up as it is now?

The Lily docs say that LilyPond requires the use of forward slashes in include statements. So I think it is good to not support the backslash. I don't know if it is easy to implement popup on backslash and replace that with a forward slash.

**Comment by wbsoft** [comment]
> Could the autocomplete popup again without any interaction? Or else remove the trailing slash from the autocomplete list?

Will look into it!

**Comment by uliska** [comment]
Am 04.03.2016 um 12:01 schrieb Wilbert Berendsen:
>
>     What should happen if the user types a backslash? Is the
>     autocomplete supposed to pop up but with slashes in the path? Or
>     should it open with backslashes? Or should just no autocompletion
>     pop up as it is now?
>
> The Lily docs say that LilyPond requires the use of forward slashes in
> include statements. So I think it is good to not support the
> backslash. I don't know if it is easy to implement popup on backslash
> and replace that with a forward slash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbsoft/frescobaldi/issues/804#issuecomment-192233953>.
>

Hm. I think if LilyPond requires forward slashes (and it makes sense it
does) then backslashes are simply wrong. In that case I don't think
Frescobaldi should make efforts supporting/fixing that. In a way that
would be trying to guess and fix user errors.

**Comment by tobik** [comment]
That make sense.

**Comment by wbsoft** [comment]
please test again, now the trialing slash is not added anymore to directories. I am not sure if this is really desirable, because dirs are less recognizable.

I think it is better to press Ctrl+Space to get the popup again.

**Comment by tobik** [comment]
It works as proposed. But you are right. A path is easier recognizable with the trailing slash. And if one know the Ctrl+Space shortkey (I didn't) this is not a issue. But if not, it is. 

All in all a matter of personal preferences. Myself would probably go with the trailing slash even if I know I will struggle with the shortcut next time.

**Comment by wbsoft** [comment]
I will revert the behaviour and add the trailing slash.

**Comment by PeterBjuhr** [comment]
Sorry for jumping in so late! (I have now recreated my testing setup on windows 7 and tried this out.)

I also get the Lilypond error message reported by @tobik when using backslashes:

`programming error: file name not normalized`

But it's important, I think, to note that the included file is compiled - so the backslashes do work despite the error message!

> This is something that is annoyingly ambiguous with LilyPond

To my mind we have here a case where if the official versions were true we would have a serious problem. But Windows does support forward-slashes "contrary to popular belief" [wikipedia](https://en.wikipedia.org/wiki/Path_(computing)#MS-DOS.2FMicrosoft_Windows_style), and Lilypond does support backslashes contrary to the documentation and the error message.

> What should happen if the user types a backslash? Is the autocomplete supposed to pop up but with slashes in the path? Or should it open with backslashes? Or should just no autocompletion pop up as it is now?

I think this is a very valid question - the typical Windows user would expect backslashes to work as this is the official way to write paths on Windows. And given that it actually works albeit with an error message I think it might be a good idea for the autocomplete to support it. (But perhaps should backslashes be autocorrected to forward-slashes to obey LilyPond standards...)

**Comment by tobik** [comment]
Most helpful for the user would be iIf Frescobaldi could accept backslahes and autocorrect this to slashes. This would teach the correct way to write paths for LilyPond.
