### ISSUE TITLE
search does not realize that content is changed

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#807]
I'm using current master. Steps to reproduce the bug:

- make a search (Ctrl + F) and find some keyword which is present in the opened file
- then change the content so that the keyword is no more present

You'll see that:

1. the count in the search bar will still show the number of hits of the keyword
2. if you use Ctrl+G to go to the next occurence, the cursor goes where the keyword used to be

So it seems that the search is still looking at an old document, even if the document is changed (and even saved to disk).

**Comment by wbsoft** [comment]
Search remembers only positions and indeed those are not updated to reflect changed document contents

**Comment by uliska** [comment]
That means there should be a slot to redo the search connecting to
changes of the editor
