### ISSUE TITLE
C-Melody saxophone AWOL under "setup new score" wizard.

### ISSUE THREAD

**Issue by globetrotterdk** [wbsoft/frescobaldi#810]
The subject says it all. I am lacking the ability to include a C-Melody saxophone, when I want to create a new score.

**Comment by wbsoft** [comment]
Please say what the long and abbreviated instrument name (`instrumentName` and `shortInstrumentName`) should be. And, IIUC, the instrument should not transpose?

**Comment by globetrotterdk** [comment]
Thanks for the quick response.

I would suggest using "C-Melody Sax" as the instrumentName and "c-mel sax" as the shortInstrumentName. No, there is no transposition, as the C-Melody saxophone is designed to play in the key of "C". That being said, you should of course be aware that the octave range is the same as other saxophones.

Wikipedia:
https://en.m.wikipedia.org/wiki/C_melody_saxophone

Thank you,

Brian

**Comment by wbsoft** [comment]
thanks for your request
