### ISSUE TITLE
Move lines to extra include file

### ISSUE THREAD

**Issue by sincere-music** [wbsoft/frescobaldi#815]
Splitting up a single large document into smaller .ily files and referencing them in the base document is a somewhat tedious task: you have to cut them, open a new file, write a version statement, paste the lines, save, and write an \include.
It would be great if one could just select some code, right-click, select ‘Move to extra file…’, enter a file name (as relative path) and have Frescobaldi do the rest, i.e. create the new file with the selected lines and a \version statement (inherited from the main file), and replace the lines by an \include in the main file.

**Comment by wbsoft** [comment]
Good idea. The command "Move selection to include file..." should also appear in the Edit menu, right below "Cut & Assign"
