### ISSUE TITLE
line numbers and fold/unfold not working in Frescobaldi 3

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#829]
I'm using Frescobaldi from master and I see two regressions:

1. The expand/collapse symbols in the editor view are not visible (this should be enabled by default, right?).
2. Line numbers are not visible even if the option is checked in the preferences.

**Comment by wbsoft** [comment]
No problem here. Which versions of Qt and PyQt are you using? (frescobaldi -V)

**Comment by fedelibre** [comment]
```
$ python3 src/frescobaldi/frescobaldi -V
Frescobaldi: 3.0.0
Python: 3.4.3
python-ly: 0.9.4
Qt: 5.6.0
PyQt: 5.5.1
sip: 4.17
poppler: 0.34.0
python-poppler-qt: 0.24.2
OS: Linux-4.4.9-300.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three
```

**Comment by wbsoft** [comment]
Same as my systems, only I use Python 3.5.1. Works ok here. Did you clean install? Some logic moved to another folder (from widgets to gadgets :-)

**Comment by fedelibre** [comment]
Sorry, brain fart :)
I was looking in the wrong place. I've just enabled line numbers and expand/collapse using the View menu.
