### ISSUE TITLE
Good default font setting on Windows needed (was: Text editor and antialias)

### ISSUE THREAD

**Issue by ivan66ud** [wbsoft/frescobaldi#83]
Hi! Frescobaldi works very well in my windows XP. Anyway the text editor is very ugly!!! The characters have a lot of alias: they are almost difficult to read; I've tried various combinations font/resolution without significative results.
This issue doesn't affect the Ubuntu/Linux version that I usually use instead of Windows version.
Thanks and regards

**Comment by fedelibre** [comment]
If you don't have Lucida Console installed, the result is quite ugly (no bold font):

![Schermata del 2023-04-05 15-28-01](https://user-images.githubusercontent.com/1644647/230097166-37d09d54-30c1-4afc-8194-f5b49f216aab.png)

If we don't want to bundle it, we may find another way to improve the first experience.

**Comment by fedelibre** [comment]
Actually the Lucida Console font seems to be installed, but it doesn't look good for some reason. Maybe there's no bold version available...

The problem is that I do not know Windows os much.
