### ISSUE TITLE
Wrong lilypond code for \partial when doing "Rhythm->Make implicit (per line)" 

### ISSUE THREAD

**Issue by dc7kr** [wbsoft/frescobaldi#832]
When converting a line like \partial 2 r2  to implicit rhythm (Tools->Rhythm->Make implicit (per line)) Frescobaldi 2.19.0 converts it to "\partial 2 r" which is wrong. Seen in 2.18.2 too. 

I agree, that it is not very meaningful to convert that line at all but when converting the entire music to implicit rhythm (per line) by selecting the entire file, it is helpful to not have to remove the line from the selection.

**Comment by wbsoft** [comment]
thanks for reporting!

**Comment by wbsoft** [comment]
the duration after `\partial` is also removed erroneously when the same as a preceding duration...
