### ISSUE TITLE
Request: New Window without displaying the code

### ISSUE THREAD

**Issue by dtsmarin** [wbsoft/frescobaldi#841]
Hi,
I want to have my music view in a second monitor  and in a different window but I can't hide the script in the new window.. The default option of maximizing the music view doesn't work for me because I want to have Frescobaldi's main window in the background while working in a D.A.W.  
When I click on the Music view two navigate in the score  Windows bring up Frescobaldi window  on top of the other program but I want it to stay in the background, **this only works with two separate windows.**.
Please could you fix this? Having the script editor twice makes sense with different projects but when you have one project it should be possible to remove the script editor from the second window. 
Best,
Dimitris

**Comment by wbsoft** [comment]
The music view (as the other tools) is a Tool window, it may be possible to alter the behaviour though. Although I don't know how Qt internally handles tool windows on Windows.

**Comment by wbsoft** [comment]
A workaround might be to display the PDF in an external viewer (via LilyPond→Generated files menu)

**Comment by fedelibre** [comment]
> A workaround might be to display the PDF in an external viewer (via LilyPond→Generated files menu)

And in order to have point and click from external viewer to Frescobaldi, you can create this environment variable:

```
export LYEDITOR="frescobaldi --line %(line)s --column %(column)s %(file)s"
```

This currently works on Linux only.
I have a blog post draft on lilypondblog.org which explains how to set this up on Windows (completed) and Mac (almost completed).

**Comment by uliska** [comment]
I'll close this issue, leaving a reference to #1051.
