### ISSUE TITLE
First release with Qt5?

### ISSUE THREAD

**Issue by ilovezfs** [wbsoft/frescobaldi#842]
Any idea when the first release/tag with the new Qt5 requirement will be out?

Thanks!

**Comment by wbsoft** [comment]
will be 3.0.0, but some people are experiencing stability problems. On my systems it already works well. (git master)

**Comment by ilovezfs** [comment]
@wbsoft thanks for the response! I'm asking because we're planning to phase out Qt 4 for Homebrew when macOS Sierra ships, so we're trying to transition formulae over to Qt 5 where possible in advance.

**Comment by juliangilbey** [comment]
Hi there,
Is there any progress on this transition?  It has dropped out of Debian testing now, and won't make it into the next Debian stable release unless it is updated by October :-(
Thanks!

**Comment by anthonyfok** [comment]
Hi @juliangilbey,

Thank you for the heads-up about the impending freeze for Debian "stretch".  I just noticed today that the master branch of Frescobaldi is already transitioned to Qt5, so I will try to get pre-3.0.0 (e.g. Debian version 3.0.0~git20161001-1) packaged once I can get it to work.  (I am currently experiencing some Python errors during document preview...)

**Comment by anthonyfok** [comment]
For Debian stretch/sid (the future Debian 9.0): Blocked by Issues #838 and #861.

**Comment by anthonyfok** [comment]
It turns out that neither #838 nor #861 are bugs in Frescobaldi, but rather, an ABI incompatibility when SIP was upgraded but python-poppler-qt5 was not rebuilt.  See https://www.riverbankcomputing.com/pipermail/pyqt/2016-September/038136.html for more info.

So, no more blockers, at least not on my Debian machine: Score Preview works perfectly again in Frescobaldi, yay!

**Comment by ilovezfs** [comment]
@wbsoft maybe time for a new release? Or at least a beta or release candidate to get the ball rolling …

**Comment by anthonyfok** [comment]
I see a "segmentation fault" upon exit after running "python3 /work/git/frescobaldi/frescobaldi"  (that's where I put Frescobaldi that I downloaded from GitHub, haha), but it is harmless.  I wonder where that comes from.

**Comment by ilovezfs** [comment]
Just a heads up that frescobaldi was moved to the Homebrew "boneyard" :skull: tap in https://github.com/Homebrew/homebrew-core/pull/5715 due to the lack of Qt 5 support in a released version.

**Comment by uliska** [comment]
I think this is obsolete now
