### ISSUE TITLE
print button: title not printed plus cut off text

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#847]
Today I tried for the first time the print button and it didn't work correctly:
- title and tagline are not printed
- some rehearsal text on the first system of the second page is cut off

The same score prints correctly when I use `lpr` command.

Here's a minimal example for title&tagline problem:

```
\version "2.19.46"
\header {
  title = "test"
}
{
  c1
}
```

**Comment by wbsoft** [comment]
Thanks for reporting. Internally Frecobaldi also simply calls `lpr`. Are there any special settings or paper formats that you set in the print dialog?

**Comment by fedelibre** [comment]
I cannot reproduce the problem, at least on my desktop computer. I cannot remember where I made the tests in August.. probably on my laptop and a different printer, but I vaguely remember that i tried also on my desktop before.

Anyway, I'll close it. If it happens again, I'll reopen it.

By the way, this is the printer dialog:

![frescobaldi-printer-dialog](https://cloud.githubusercontent.com/assets/1644647/23165448/6c594d34-f83c-11e6-8924-3a4a290d0c6d.png)
