### ISSUE TITLE
intermediate files renamed by Frescobaldi

### ISSUE THREAD

**Issue by fedelibre** [wbsoft/frescobaldi#854]
As I needed  a PS file, I unchecked the option "Let LilyPond delete intermediate output files". The PS file then is kept but the name of the file is something like lilypond-HASH.

Feature request: can Frescobaldi keep the same name as the (saved) input .ly file and add the .ps extension?

**Comment by pl-gauthier** [comment]
@fedelibre, you can use the `Engrave (custom)` function found in the `LilyPond` menu. It is assigned _(by default)_ to `Ctrl+Shift+M`. In this contextual menu, you can set LilyPond to render your files in the `PostScript` format.

Hope that helps.

**Comment by fedelibre** [comment]
Sure, this should be the way to go. Thanks
