### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by jcsalomon** [wbsoft/frescobaldi#857]
Frescobald version 2.19.0, LilyPond 2.19.47, under Windows 10 64-bit

Minimal code (UTF-8-encoded file):

``` lilypond
\version "2.19"
\score {
  {
    \displayScheme
    \mark "“Quoted Text”"
  }
  \layout {}
}
```

yields

> Frescobaldi: 2.19.0 -- Python: 2.7.1 -- python-ly: 0.9.4 -- Qt: 4.7.2 -- PyQt: 4.8.4 -- sip: 4.12.2 -- poppler: unknown -- python-poppler-qt: unknown -- OS: Windows-post2008Server-6.2.9200
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\job.py", line 265, in _readstdout self.message(self.decoder_stdout(output, self.decode_errors)[0], STDOUT)
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\job.py", line 213, in message self.output(text, type)
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\signals.py", line 191, in emit
> l.call(args, kwargs)
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\signals.py", line 308, in call
> return self.func(obj, _args[self.argslice], *_kwargs)
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\log.py", line 85, in write
> self.writeMessage(message, type)
> File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\logtool\logwidget.py", line 130, in writeMessage
> message = message.encode('latin1').decode('utf-8')
> File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 70: invalid continuation byte

**Comment by uliska** [comment]
I can confirm that with Frescobaldi 2.19 on Linux.

But it's not with all special characters. I tried quite a number of
others, and they worked fine except for these English quotation marks.

Urs


Am 09.09.2016 um 16:15 schrieb Joel C. Salomon:
>
> Frescobald version 2.19.0, LilyPond 2.19.47, under Windows 10 64-bit
>

**Comment by anthonyfok** [comment]
Ditto with Frescobaldi v2.18.2 on Debian stretch/sid (testing/unstable),
and with the master branch for v3.0.0.

**Comment by wbsoft** [comment]
It has to do with the LilyPond output from commands like `\displayScheme`, `\displayMusic` etc. It seems that it prints invalid utf-8 to standard output.
When run on the terminal the above example yields:
```scheme
(make-music
  'MarkEvent
  'label
  "�\x80�Quoted Text�\x80�")
```
While a simple
```lilypond
#(begin
  (display "“Quoted Text”")
  (newline))
```
correctly yields
```
“Quoted Text”
```
I must circumvent the problem by simply ignoring errors when decoding the LilyPond standard output to utf-8.
