### ISSUE TITLE
Can not run frescobaldi 2.19.0

### ISSUE THREAD

**Issue by snyoung** [wbsoft/frescobaldi#859]
I use fedora 24, frescobaldi 2.19.0 is provided by the distro.
I get this message when trying to run:

$ frescobaldi
Traceback (most recent call last):
  File "/usr/bin/frescobaldi", line 11, in <module>
    main.main()                     # Parse command line, create windows etc
  File "/usr/lib/python2.7/site-packages/frescobaldi_app/main.py", line 185, in main
    args = parse_commandline()
  File "/usr/lib/python2.7/site-packages/frescobaldi_app/main.py", line 53, in parse_commandline
    argparse._ = _ # let argparse use our translations
NameError: global name '_' is not defined

And I get the same message (except the path of the file) using the 2.19.0 source package provided here.

Is that a bug?

**Comment by dliessi** [comment]
This is probably the same as #843, i.e., an incompatibility between Frescobaldi on Python 2 and the `future` package.
Try uninstalling the `future` package or moving to Python 3.

**Comment by mojca** [comment]
I added a potential solution/patch to #843. I didn't make a pull request as I'm not sure to which branch and which files one should add the patch.

**Comment by wbsoft** [comment]
fixed in the `v2.x` branch (where this is relevant)
