### ISSUE TITLE
V3: Preview in "Score Setup Wizard" gives "TypeError: Document.load(): argument 1 has unexpected type 'str'" error

### ISSUE THREAD

**Issue by anthonyfok** [wbsoft/frescobaldi#861]
Might be related to #838, but this happens when I click on the [Preview] button in the Score Setup Wizard dialog window:

Frescobaldi: 3.0.0 -- Python: 3.5.2+ -- python-ly: 0.9.4 -- Qt: 5.6.1 -- PyQt: 5.7 -- sip: 4.18.1 -- poppler: 0.38.0 -- python-poppler-qt: 0.24.2 -- OS: Linux-4.7.0-1-amd64-x86_64-with-debian-stretch-sid

```
Traceback (most recent call last):
  File "/work/git/frescobaldi/frescobaldi_app/job.py", line 238, in _finished
    self._bye(success)
  File "/work/git/frescobaldi/frescobaldi_app/job.py", line 254, in _bye
    self.done(success)
  File "/work/git/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/work/git/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/work/git/frescobaldi/frescobaldi_app/musicpreview.py", line 131, in _done
    self.setDocuments(pdfs)
  File "/work/git/frescobaldi/frescobaldi_app/musicpreview.py", line 150, in setDocuments
    self.selectDocument(0)
  File "/work/git/frescobaldi/frescobaldi_app/musicpreview.py", line 155, in selectDocument
    doc = self._documents[index].document()
  File "/work/git/frescobaldi/frescobaldi_app/popplertools.py", line 58, in document
    self._document = self.load()
  File "/work/git/frescobaldi/frescobaldi_app/popplertools.py", line 68, in load
    return popplerqt5.Poppler.Document.load(self._filename)
TypeError: Document.load(): argument 1 has unexpected type 'str'
```

Many thanks!

**Comment by anthonyfok** [comment]
It might have to do with a breaking ABI change in SIP that, at the moment, requires a rebuild of python3-poppler-qt5, according to these Debian bug report:

* https://bugs.debian.org/839870
* https://bugs.debian.org/839875

I will report back once I have more information, i.e. to see if this bug goes away after a rebuild of python3-poppler-qt5.

**Comment by anthonyfok** [comment]
Sorry, false alarm indeed.

This bug is specific to Debian stretch/sid (testing/unstable) as of early October 2016 (and perhaps earlier) and has nothing to do with Frescobaldi itself.  Rather, it is the aforementioned ABI incompatibility between python-poppler-qt5 and the sip-dev/python3-sip-dev library that is the culprit.  Rebuilding the python-poppler-qt5 package solves the problem.

Upgrading to `python3-poppler-qt5` version 0.24.2-2 should fix the problem.

```
python-poppler-qt5 (0.24.2-2) unstable; urgency=high

  [ Ondřej Nový ]
  * Fixed VCS URL (https)

  [ Anthony Fok ]
  * Cherry upstream fixes since the 0.24.2 release
  * Refresh debian/control
    - Bump Standards-Version to 3.9.8
    - Tweak Vcs-Browser according to https://wiki.debian.org/Python/GitPackaging
  * This new build incidentally solves an ABI incompatibility with the
    recently updated SIP library: was sip-py3api-11.2, now sip-py3api-11.3.
    (Closes: #839875, #839870)

 -- Anthony Fok <foka@debian.org>  Wed, 05 Oct 2016 22:25:56 -0600
```

Closing this issue.  :-)

**Comment by uliska** [comment]
Do you think this could also be the reason/solution for https://github.com/wbsoft/frescobaldi/issues/818 ?

**Comment by anthonyfok** [comment]
Hi @uliska,

Unfortunately, I have never experienced the error that you saw in #818, so I doubt it is the same issue.  I will try and see if I can reproduce the error that you saw on Linux Mint 2 "betsy" when I have time.  Downloading the ISO now.  :-)
