### ISSUE TITLE
First run of "Open Recent" (from Untitled) no longer loads existing MIDI file since v2.19.0 (and 3.0.0-in-development)

### ISSUE THREAD

**Issue by anthonyfok** [wbsoft/frescobaldi#862]
It appears the fix for #806, i.e. commit 49fc181 / 222f12b dated 2016-04-16, created a minor regression which affects the v2.19.0 release and the current v3.0.0 branch in development.
### Steps to reproduce:
1. Start Frescobaldi.
2. Navigate to "File » Open Recent" to open an existing `.ly` file where the corresponding `.midi` and `.pdf` were previously generated.
3. With the MIDI Player visible, click on the Play button therein.
### Expected behaviour (as found in v2.18.2 and before)
- The filename of the MIDI file should appear briefly (for about 2 seconds?) before switching back to "Time 0:00  Beat 0.0" upon Step 2.
- The MIDI file should start playing upon Step 3.
### Actual behaviour (as found in v2.19.0 and the v3 master branch as of 2016-10-06)
- The filename of the MIDI file never appears, showing "Time 0:00  Beat 0.0" before and after Step 2.
- The MIDI file does not play upon Step 3.
- Now, opening a _second_ recent `.ly` file does load the corresponding `.midi` file, which would play correctly.  Upon switching back to the first tab, the first `.midi` file now also loads correctly and is ready to play.
- Alternatively, after pressing Ctrl+M or equivalent to "Engrave (preview)", the newly generated `.midi` file is loaded correctly and is ready to play.
### Diagnosis

With the help of `git bisect`, I found that the behaviour change happened at commit 49fc181 / 222f12b:

```
commit 222f12bc14d3bb26b10e483b21bc9ce749126b64
Author: Wilbert Berendsen <wbsoft@xs4all.nl>
Date:   Sat Apr 16 22:46:06 2016 +0200

    hopefully fix #806 MIDI file not updated in MIDI Player when using "master" variable

commit 49fc181e28aa34f38f4a8bb6f9d44e33b5204413
Author: Wilbert Berendsen <wbsoft@xs4all.nl>
Date:   Sat Apr 16 22:46:06 2016 +0200

    hopefully fix #806 MIDI file not updated in MIDI Player when using "master" variable
```

It is a relatively minor issue, but it would be nice if it could be fixed for the future v2.19.1 and v3.0.0 releases.

Many thanks!

Anthony

**Comment by gstalnaker** [comment]
Confirm this behavior, if it needs confirmation, on my Win7/FBv19.0 computer.

**Comment by wbsoft** [comment]
I also see this when simply opening a LilyPond score as first document (not per se using recent files). Also when closing the last document, a filename still is displayed in the midi player, although it is not playable it seems.
