### ISSUE TITLE
Frescobaldi on GSoC

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#868]
Having just attended the [GSoC Mentors Summit](https://sites.google.com/site/2016gsocmentorsummit/) I would like to raise the question of whether Frescobaldi should apply for becoming a mentoring organization in the next Google Summer of Code.

I am sure that Frescobaldi would greatly benefit from that and that there would be numerous perfectly suitable students projects available in Frescobaldi. Technically Frescobaldi would match the requirements to become a GSoC mentoring organization, although they might reject the application finding the active developer community being too small. But this would have to be seen upon an actual application which would be due in Jan/Feb 2017.

The main obligation we would have to sort out in advance is that two persons have to be willing to act as "org admins" during the whole project period, i.e. from the application in January to the mentors summit in October. I think this is a non-neglectable responsibility and task, so it should be discussed. However, I'd be willing to be one of these two persons.

Additionally we'd need potential mentors available as well, as it wouldn't make sense if we should successfully apply and even receive one or two slots (this is the usual maximum for first-year orgs) and then fail to provide mentors. The org admins may as well be mentors, and I'd volunteer for that as well

If we'd become a GSoC organization and should get one or more students to work for Frescobaldi that would also mean that the mentor(s) would be invited to the GSoC mentors summit, which is a cool thing.

Thoughts?

**Comment by GeekyShiva** [comment]
Hi @uliska , I am a gsoc2017 aspirant and willing to work for the project Add Support for Version Control (Git), the project looks very exciting to me and i am willing to know how do i begin to understand and know more about the project and start contributing?

Please specify the best way to connect with you ?

**Comment by uliska** [comment]
@GeekyShiva You may write to me to ul @ openlilylib.org, so we can continue this by email (I'll remove this comment soon). Otherwise you could write to the [mailing list](https://groups.google.com/forum/#!forum/frescobaldi) specified on our GSoC page

**Comment by uliska** [comment]
Well, this is obviously obsolete now
