### ISSUE TITLE
Follow \include-s for MusicXML export

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#873]
Currently MusicXML export only works for the open document and doesn't respect \includes. Which can be seen in https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/file_export/__init__.py#L53, specifically in [this line](https://github.com/wbsoft/frescobaldi/blob/master/frescobaldi_app/file_export/__init__.py#L65).

This is  major annoyance because it simply doesn't export *anything* in files that make use of any modularization. I think Frescobaldi is able to follow includes, as it does for example with autocompletion. So it should be rather painless to do.

I'd like to look into this but ask here because someone might be faster telling me where to look that I can find myself. @PeterBjuhr @wbsoft ?

**Comment by PeterBjuhr** [comment]
Are you referring to this comment: 

> If you specify a filename, it can be used to resolve \\include commands correctly.

https://github.com/wbsoft/python-ly/blob/master/ly/musicxml/lymus2musxml.py#L96

And the fact that no filename seems to be specified in the line you are linking to?

There's support for following includes in python-ly.ly.musicxml and I was under the impression that Frescobaldi was using this. But perhaps you're right!?

**Comment by uliska** [comment]
As linked in the description Frescobaldi calls it with `writer.parse_text(doc.toPlainText())`, so only the current tab's content is parsed.

So what should I actually pass to python-ly? It seems to me the filename should be sufficient, but obviously the function requires the text string.

Thank you for pointing this out anyway, I think I'll be able to continue on that track

**Comment by uliska** [comment]
> It seems to me the filename should be sufficient, but obviously the function requires the text string.

Or does that mean I could pass a *different* file name (e.g. a "master" file) in addition to the current tab's content?
