### ISSUE TITLE
Frescobaldi 2.19, Python 2.7, Fedora 25, and builtins

### ISSUE THREAD

**Issue by fhbartlett** [wbsoft/frescobaldi#875]
When I ran Frescobaldi for the first time after upgrading from F24 to F25, I got the error message
<code>NameError: global name '_' is not defined</code>
Note that Frescobaldi worked perfectly well before the upgrade

So this is a copy of #843 and #859. The solution proposed in the former by @mojca seems to be the answer -- at least, it worked for me. I downloaded the source and applied mojca's patch to every file in which I found
<pre><code>try:
    import builtins # py3
except ImportError:
    import __builtin__ as builtins # py2</code></pre>

That's <code>build/lib/frescobaldi_app/menu.py</code> and 3 files in the snippets subdirectory: <code>builtin.py</code>, <code>expand.py</code>, and <code>highlight.py</code>. After than, running <code>setup.py</code> produced a fully functional Frescobaldi, all the necessary prerequisites already being present.

To repeat mojca's info, the replacement is
<pre><code>import sys
if sys.version_info >= (3, 0):
    import builtins # py3
else:
    import __builtin__ as builtins # py2</code></pre>

 It would seem to me to be sensible to move mojca's fix into the current code.

**Comment by hurzl** [comment]
I had this problem too and the solution above works.

**Comment by wbsoft** [comment]
fixed in the `v2.x` branch (where this is relevant)

**Comment by hurzl** [comment]
So why do I get the same problem in 3.0.0?

**Comment by wbsoft** [comment]
Does plain `import builtins` work for you in python3? (Note: you must use Python 3 with Frescobaldi 3.0.0)
