### ISSUE TITLE
Suggestion: Lyric syllabifier

### ISSUE THREAD

**Issue by rpspringuel** [wbsoft/frescobaldi#876]
It would be convenient if one could enter lyrics as straight text, highlight them, and then select a tool which would automatically insert ` -- ` in between syllables in polysyllabic words.  Obviously this requires knowing the language of the text (perhaps a setting or a dialog) and the hyphenation patterns for that language (perhaps stored in a directory where the user can add whichever ones they want).  Said patterns are already available on the web in a variety of formats for many languages, so it's just a matter of picking the format and then writing a script that works with that pattern.

Off hand, I know of the gregorio-project/hyphen-la project which has a python script syllabifier designed to syllabify a text file containing latin text.  The limit to Latin, however, is relatively easy to overcome by removing the hardcoding to a latin hyphenation pattern and changing it to use an arbitrary hyphenation pattern file (in the libhyphen format).

**Comment by uliska** [comment]
This has always (?) been available through `Tools=>Lyrics=>Hyphenate lyrics text ...`.
I think it relies on LibreOffice/OpenOffice dictionaries.

**Comment by rpspringuel** [comment]
Oops.  Missed that.  Sorry for the noise.
