### ISSUE TITLE
Frescobaldi - Mac Sierra

### ISSUE THREAD

**Issue by rik321** [wbsoft/frescobaldi#878]
Hello

Frescobaldi-2.19.0-x86_64.dmg - wanting to install on mac osx sierra.

Has Apple made it more difficult to install the Frescobaldi dmg please?
If so, any easy work round suggestions would be much appreciated. tia

**Comment by dliessi** [comment]
Could you please explain what is the problem you are facing?
Your description is too vague...
Thanks.

**Comment by rik321** [comment]
hello

Thank you for getting back on this. I have tried a number of times to install the application using the .dmg disk image. It refuses to install in the usual manner of adding the app icon to the applications folder (directory). As there were some changes with installing applications under Yosemite I wondered if this was a similar problem with apple protecting areas of the OS?

**Comment by rik321** [comment]
hello, again

Sorry to have bothered you, problem solved. I had to switch to an Admin account to get the app loaded in osx sierra. Once the app opened I can now run it normally from my user account.
