### ISSUE TITLE
Wish: Extract to file

### ISSUE THREAD

**Issue by CJBrew** [wbsoft/frescobaldi#881]
Extracting code to a new file is a common feature of IDEs such as Eclipse and Visual Studio, and helps in keeping code clean.

This would be particularly useful in Frescobaldi when dealing with, say, MusicXML created by Musescore, or more generally as a project gets bigger. 

Proposed behaviour:

1) Select a block of code
1) Apply "Extract to file". 
1) User is prompted for a filename ( ".ily" as a default extension )
1) Code is removed from the current source file, and added into the new file
1) `/include` declaration added to the current source file at the point of extraction

**Comment by wbsoft** [comment]
This feature is already available: #815

**Comment by CJBrew** [comment]
Thanks -- It looks like I'll need a bleeding-edge build to see it though?

**Comment by wbsoft** [comment]
Indeed! I now added it to the 2.x branch, meaning it will appear in 2.20
