### ISSUE TITLE
[Wish] Keyboard shortcut to switch between tabs

### ISSUE THREAD

**Issue by ghost** [wbsoft/frescobaldi#884]
In browsers (such as Google Chrome) and some other text editors, we use Ctrl+PageUp or Ctrl+PageDown to switch between tabs. Can this feature be added to Frescobaldi? It would make typing/editing much faster. :-) #

**Comment by andrewbernard** [comment]
Alt-arrow key does it for me in the present version.

Andrew

**Comment by Csega** [comment]
For me too (2.19.0).

**Comment by wbsoft** [comment]
Indeed this feature is already available (View→Next or Previous document), you can assign your own keyboard shortcut to it in the preferences (default: Alt+Arrow keys)
