### ISSUE TITLE
inability to enter double (") or single (') quotes

### ISSUE THREAD

**Issue by fwiep** [wbsoft/frescobaldi#886]
Hello,

Frescobaldi: 2.18.1 -- Python: 3.5.2 -- python-ly: 0.9.3 -- Qt: 4.8.7 -- PyQt: 4.11.4 -- sip: 4.17 -- poppler: 0.38.0 -- python-poppler-qt: 0.24.0 -- OS: Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial

I seem to be unable to enter double (") or single (') quotes in the editor and dialog-windows.
When I push the keys on my keyboard, instead the following characters appear: ¨ and ´

I use the United Stated International with Dead Keys layout. This works outside Frescobaldi.

My workaround is to switch back and forth to a Run-dialog and enter the quote I need, then cut-paste it into the editor window.

Could you please tell me if I'm doing something wrong, how to fix this myself, or if you will fix it in the near future?

Thank you very much, 
FWieP

**Comment by uliska** [comment]
Am 30.01.2017 um 09:55 schrieb fwiep:
>
> Hello,
>
> Frescobaldi: 2.18.1 -- Python: 3.5.2 -- python-ly: 0.9.3 -- Qt: 4.8.7
> -- PyQt: 4.11.4 -- sip: 4.17 -- poppler: 0.38.0 -- python-poppler-qt:
> 0.24.0 -- OS: Linux-4.4.0-59-generic-x86_64-with-Ubuntu-16.04-xenial
>
> I seem to be unable to enter double (") or single (') quotes in the
> editor and dialog-windows.
> When I push the keys on my keyboard, instead the following characters
> appear: ¨ and ´
>

Did you check Preferences->Editor Preferences->Typographical quotes?

**Comment by fwiep** [comment]
Yes, I checked the Quotes-settings.

With all variants I tried, the editor and dialogue windows still produce the ¨ character when entering a double quote ".

Is there another option I can try?

**Comment by andrewbernard** [comment]
This brings up the basic question - how do you enter typohgraphic quotes
anyway? Like the OP, when I make changes in preferences to Typographicla
Quotes, even after restarting, nothing happens. This is on Linux Mint.

Andrew

**Comment by wbsoft** [comment]
I myself also have problems with the compose key not working inside Frescobaldi, making it impossible to enter characters like ë, etc.

**Comment by wbsoft** [comment]
> This brings up the basic question - how do you enter typohgraphic quotes anyway?

Using the Ctrl+quote keys (see the Snippets menu). The typographical quotes feature is unrelated to the keyboard problem reported in this issue.

**Comment by fwiep** [comment]
Clicking the Snippets menu entry (Typographical Quotes), the typographical quotes for my language are indeed inserted.

> Using the Ctrl+quote keys (see the Snippets menu)

This does point me in the right direction, though:

- when I use <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>'</kbd>, I actually get a normal apostrophe. 
- when I use <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>'</kbd>, I do get a normal double quote.

Is this normal behaviour, for regular single and double quotes to be inserted through Ctrl + Alt and Ctrl + Shift combinations? If so, this issue can be closed.
