### ISSUE TITLE
Will there be a Windows installer for Frescobaldi 3.0.0?

### ISSUE THREAD

**Issue by Csega** [wbsoft/frescobaldi#892]
Hi Guys!

I'm very excited about the new, 3.0.0 release. I saw, that for the 2.20.0 there is already a Windows installer. My question is, that will there be one for the 3.0.0 as well?

Thanks for your help!

**Comment by wbsoft** [comment]
A 3.0.0 windows installer is in the works....

**Comment by Csega** [comment]
Cool, thanks, I cannot wait for it! :)

**Comment by fedelibre** [comment]
I see a Windows installer in the release page.
Should we close this?

**Comment by uliska** [comment]
Do we have any proof/confirmation that it works properly?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fedelibre** [comment]
I installed it on Windows 7 at work, but I never used it.
If there are problems, we'll get reports from Windows users.
Let's close this.

**Comment by Csega** [comment]
Hi Guys!

The installer works for me (I tried the 40 MB 3.0.0 installer and not the 3.0.0-2) on Windows 10 Pro 64 bit. I think we can close this.
