### ISSUE TITLE
Frescobaldi 3 doesn't run on Windows

### ISSUE THREAD

**Issue by przemoc** [wbsoft/frescobaldi#898]
Hi and thanks for your work on Frescobaldi.
I grabbed [setup](https://github.com/wbsoft/frescobaldi/releases/download/v3.0.0/Frescobaldi.Setup.3.0.0.exe) file, installed it on my W7 x64 (I had Frescobaldi 2.19 before), but running fails.

I get message box titled:
~~~
cx_Freeze: Python error in main script
~~~
The content is:
~~~
Traceback (most recent call last):
 File "C:\Python35\lib\site-packages\cx_freeze_win-5.0-py3.5-win32.egg\cx_Freeze\initscripts\Console.py", line 21 in <module>
 File "../frescobaldi", line 7 in <module>
 File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\main.py", line 33 in <module>
  from PyQt5.QtCore import QSettings, QTimer, QUrl
 File "ExtensionLoader_PyQt5_QtCore.py", line 22, in <module>
 File "ExtensionLoader_PyQt5_QtCore.py", line 14, in __bootstrap__
 File "C:\Python35\lib\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: Nie można odnaleźć określonego modułu.
~~~

The last message is non-English, because I have Polish version of Windows. It means:
`The specified module could not be found.`

**Comment by Csega** [comment]
Hi!

I have Windows 10 x64 and I did not experience such problem so far. However, Avast Antivirus reports, that there is a suspicious file, when I try to install using the official installer and it do not let me install it. I had to turn off AA and then install Frescobaldi 3 and then turn it on again. This way the installation works.

Maybe you have similar problem, just your antivirus does not let you know directly, that it deleted or quaranteened a file?

**Comment by uliska** [comment]
Did AA tell you *which* file it didn't trust?

**Comment by wenxin-bupt** [comment]
I met the same problem while trying to run it on windows through python prompt with PyQt5.4.

**Comment by Csega** [comment]
It is called Frescobaldi.Setup.3.0.0.tmp and the full path is: C:\Users\[User Name]\AppData\Local\Temp\is-Ne7OR.tmp\Frescobaldi.Setup.3.0.0.tmp.

I guess, that the folder after Temp is a generated name, so it is always changing.

**Comment by snyoung** [comment]
Hi przemoc,
The missing DLL might be the run-time library of Microsoft Visual C++ 2015, for the Windows version of Python 3.5 is built by it.
I met the same problem as yours on Windows 7 x64, and solved it on my machine by installing BOTH the x86 and x64 versions of Visual C++ Redistributable for Visual Studio 2015

**Comment by 19joho66** [comment]
Hi,
I've had the same problem on a win7 x64 machine, and so far installing the Visual Studio 2015 Redistribution pack x86 solved it, but I'll have another look into this issue. I plan to built an installer which either downloads the necessary pack by itself or has all dependencies included. It might take a little while, because I can't spare much time for this at the moment but I will keep you updated.

**Comment by 19joho66** [comment]
Please try the new Frescobaldi.Setup.3.0.0-2.exe from the download section. This version now includes all libraries needed by Frescobaldi.
It would be cool if you could post if this setup fixes your issues.

**Comment by przemoc** [comment]
Since my last comment I had installed some stuff on my Windows 7, also coming with some other programs. I list all MSVC redistributables that I have in my Windows atm, many of them were already present before installing Frescobaldi (I put installation date in parentheses):
- Microsoft Visual C++ 2005 Redistributable -- 8.0.61001 (2016-05-13 23:31:54)
- Microsoft Visual C++ 2005 Redistributable (x64) -- 8.0.56336 (2013-03-06 20:48:25)
- Microsoft Visual C++ 2005 Redistributable (x64) -- 8.0.61000 (2016-05-13 23:31:36)
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17 -- 9.0.30729 (2013-03-06 20:56:30)
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148 -- 9.0.30729.4148 (2013-03-06 20:53:09)
- Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161 -- 9.0.30729.6161 (2016-05-14 19:50:20)
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17 -- 9.0.30729 (2013-03-06 20:53:53)
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148 -- 9.0.30729.4148 (2013-03-06 20:53:02)
- Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161 -- 9.0.30729.6161 (2013-03-06 20:49:07)
- Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219 -- 10.0.40219 (2017-02-12 21:19:37)
- Microsoft Visual C++ 2010 x86 Redistributable - 10.0.40219 -- 10.0.40219 (2017-02-12 21:19:33)
- Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030 -- 11.0.61030.0 (2017-02-12 18:18:48)
- Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030 -- 11.0.61030 (2017-02-12 18:18:47)
- Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030 -- 11.0.61030 (2017-02-12 18:18:39)
- Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40649 -- 12.0.40649.5 (2017-04-29 01:50:59)
- Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.40649 -- 12.0.40649 (2017-04-29 01:50:59)
- Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.40649 -- 12.0.40649 (2017-04-29 01:50:55)
- Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026 -- 14.0.23026.0 (2017-04-19 14:36:55)
- Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026 -- 14.0.23026.0 (2017-03-05 00:56:43)
- Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.23026 -- 14.0.23026 (2017-04-19 14:36:55)
- Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0.23026 -- 14.0.23026 (2017-04-19 14:36:51)
- Microsoft Visual C++ 2015 x86 Additional Runtime - 14.0.23026 -- 14.0.23026 (2017-03-05 00:56:43)
- Microsoft Visual C++ 2015 x86 Minimum Runtime - 14.0.23026 -- 14.0.23026 (2017-03-05 00:56:40)

Currently I get message box titled:

    Microsoft Visual C++ Runtime Library

with content

~~~
Runtime Error!

Program: C:\Program Files (x86)\Frescobaldi\frescobaldi.exe

R3064
An application has made an attempt to load the C runtime library incorrectly.
Please contact the application's support team for more information.
~~~

but Frescobaldi at least starts afterward and following text is shown in Music View:

    Could not load the popplerqt5 module.

I just wanted to update current status w/o trying new installer yet. I'll try it in a moment and see if the error goes away.

**Comment by przemoc** [comment]
I installed Frescobaldi using [Frescobaldi.Setup.3.0.0-2.exe](https://github.com/wbsoft/frescobaldi/releases/download/v3.0.0/Frescobaldi.Setup.3.0.0-2.exe) and now it's even worse.

I get immediately `frescobaldi.exe has stopped working` message box. I have Polish version of Windows, but you should be able to understand problem details anyway:

~~~
Podpis problemu:
  Nazwa zdarzenia problemu:	APPCRASH
  Nazwa aplikacji:	frescobaldi.exe
  Wersja aplikacji:	0.0.0.0
  Sygnatura czasowa aplikacji:	5707f8ed
  Nazwa modułu z błędem:	ucrtbase.DLL
  Wersja modułu z błędem:	10.0.10586.788
  Sygnatura czasowa modułu z błędem:	5879aa7b
  Kod wyjątku:	40000015
  Przesunięcie wyjątku:	0008469a
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
  Dodatkowe informacje 1:	c008
  Dodatkowe informacje 2:	c008d2294613001535c75a7493497bc7
  Dodatkowe informacje 3:	d545
  Dodatkowe informacje 4:	d545569586757f604ed3a1b28ebd8356
~~~

**Comment by jurafejfar** [comment]
Hi przemoc, I solved the problem with steps bellow:

1) install Frescobaldi.Setup.3.0.0.exe from https://github.com/wbsoft/frescobaldi/releases 

and as it is stated there you might need Visual Studio **2015** x86 

2) https://www.microsoft.com/en-us/download/details.aspx?id=48145 select **vc_redist.x86.exe**

------------------------

documentation here http://www.frescobaldi.org/download with link to MSVC 2008 should be updated to link to MSVC 2015...

J.

**Comment by przemoc** [comment]
I'm honestly baffled, because I tried running Frescobaldi 3 now, and it seems it's working without any problems (I wish I knew it earlier!). I had many Windows Update and what not installed since then (14 months ago), so I cannot tell what fixed the problem.

One thing is sure, it was not jurafejfar's suggestion, because he mentioned stuff that I already had installed (Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.23026, as mentioned in one of my comments) when I was hitting the error.

**Comment by fedelibre** [comment]
@przemoc Thanks for checking.
If everything is working correctly now, you can close this issue. You can always open a new one if problem comes back.
