### ISSUE TITLE
frescobaldi throws errors in opening ly file

### ISSUE THREAD

**Issue by seanincali** [wbsoft/frescobaldi#907]
I'm having problems opening a ly file in frescobaldi 2.20 running on windows vista 64 bit home edition

I downloaded the following. 

http://www.mutopiaproject.org/ftp/CarcassiM/O1/carcassi-op1n02/carcassi-op1n02.ly

And if I try to open it frescobaldi, then the following appears in the lilypond log window.

--------

Starting lilypond-windows.exe 2.18.2 [carcassi-op1n02.ly]...
Processing `J:/=Backup Files/carcassi-op1n02.ly'
Parsing...
error: program too old: 2.18.2 (file requires: 2.19.51)
J:/=Backup Files/carcassi-op1n02.ly:43:19: error: unknown escaped string: `\fixed'
larghettoTreble = 
                  \fixed c {
J:/=Backup Files/carcassi-op1n02.ly:43:26: error: syntax error, unexpected NOTENAME_PITCH
larghettoTreble = \fixed 
                         c {
J:/=Backup Files/carcassi-op1n02.ly:88:3: error: unknown escaped string: `\fixed'
  
  \fixed c' {<a cis'>16 e'( d') cis' b a g b a g fis e |
J:/=Backup Files/carcassi-op1n02.ly:88:3: error: unrecognized string, not in text script or \lyricmode
  
  \fixed c' {<a cis'>16 e'( d') cis' b a g b a g fis e |
J:/=Backup Files/carcassi-op1n02.ly:110:17: error: unknown escaped string: `\fixed'
larghettoBass = 
                \fixed c {
J:/=Backup Files/carcassi-op1n02.ly:110:24: error: syntax error, unexpected NOTENAME_PITCH
larghettoBass = \fixed 
                       c {
J:/=Backup Files/carcassi-op1n02.ly:174:35: error: syntax error, unexpected SCM_IDENTIFIER
    \context Voice = "upperVoice" 
                                  \larghettoTreble
J:/=Backup Files/carcassi-op1n02.ly:174:35: warning: Ignoring non-music expression
    \context Voice = "upperVoice" 
                                  \larghettoTreble
J:/=Backup Files/carcassi-op1n02.ly:175:35: error: syntax error, unexpected SCM_IDENTIFIER
    \context Voice = "lowerVoice" 
                                  \larghettoBass
J:/=Backup Files/carcassi-op1n02.ly:175:35: warning: Ignoring non-music expression
    \context Voice = "lowerVoice" 
                                  \larghettoBass
J:/=Backup Files/carcassi-op1n02.ly:183:15: error: unknown escaped string: `\fixed'
rondoTreble = 
              \fixed c {
J:/=Backup Files/carcassi-op1n02.ly:183:22: error: syntax error, unexpected NOTENAME_PITCH
rondoTreble = \fixed 
                     c {
J:/=Backup Files/carcassi-op1n02.ly:296:13: error: unknown escaped string: `\fixed'
rondoBass = 
            \fixed c {
J:/=Backup Files/carcassi-op1n02.ly:296:20: error: syntax error, unexpected NOTENAME_PITCH
rondoBass = \fixed 
                   c {
J:/=Backup Files/carcassi-op1n02.ly:401:35: error: syntax error, unexpected SCM_IDENTIFIER
    \context Voice = "upperVoice" 
                                  \rondoTreble
J:/=Backup Files/carcassi-op1n02.ly:401:35: warning: Ignoring non-music expression
    \context Voice = "upperVoice" 
                                  \rondoTreble
J:/=Backup Files/carcassi-op1n02.ly:402:35: error: syntax error, unexpected SCM_IDENTIFIER
    \context Voice = "lowerVoice" 
                                  \rondoBass
J:/=Backup Files/carcassi-op1n02.ly:402:35: warning: Ignoring non-music expression
    \context Voice = "lowerVoice" 
                                  \rondoBass
J:/=Backup Files/carcassi-op1n02.ly:409:3: error: errors found, ignoring music expression
  
  << \larghettoScore >>
J:/=Backup Files/carcassi-op1n02.ly:414:3: error: errors found, ignoring music expression
  
  << \rondoScore >>
J:/=Backup Files/carcassi-op1n02.ly:425:36: warning: Ignoring non-music expression
    \context Voice = "upperVoice" {
                                   \larghettoTreble \rondoTreble}
J:/=Backup Files/carcassi-op1n02.ly:425:53: warning: Ignoring non-music expression
    \context Voice = "upperVoice" {\larghettoTreble 
                                                    \rondoTreble}
J:/=Backup Files/carcassi-op1n02.ly:426:36: warning: Ignoring non-music expression
    \context Voice = "lowerVoice" {
                                   \larghettoBass \rondoBass}
J:/=Backup Files/carcassi-op1n02.ly:426:51: warning: Ignoring non-music expression
    \context Voice = "lowerVoice" {\larghettoBass 
                                                  \rondoBass}
fatal error: failed files: "J:/=Backup Files/carcassi-op1n02.ly"
Exited with return code 1.

---------

If I try to export to music xml, the following error occurs. 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\file_export\__init__.py", line 65, in exportMusicXML
    writer.parse_text(doc.toPlainText())
  File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 102, in parse_text
  File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 119, in parse_document
  File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 126, in parse_tree
  File "c:\Python27\lib\site-packages\ly\musicxml\lymus2musxml.py", line 148, in parse_nodes
IOError: [Errno 9] Bad file descriptor

--------

if I try to send the bug report it brings up 

"Cannot start Office outlook,. The command line argument is not valid. Verify the switch you're using. "

I could really use some help here. I need to save the file as a midi or musicxml If i try to export as a midi it says 

The audio file couldn't be created. Please create midi file first.

**Comment by snyoung** [comment]
The problem is in the file, it seems to have employed some new features in the developing LilyPond 2.19 branch.
You can try below:
1. Download the LilyPond Unstable version from lilypond.org, install it with the Destination Folder in the second step of installation changed, do not use the default.
in my case, I changed the Destination Folder into D:\\lilypond-unstable\
2. Launch Frescobaldi and go to Edit -> Preferences... -> LilyPond Preferences
3. Make sure the "Automatic choose LilyPond version from document" is checked, and click "Add..."
4. Fill in the LilyPond Command as THE_FOLDER_SPECIFIED_IN_1\usr\bin\lilypond-windows.exe
in my case, I entered D:\\lilypond-unstable\usr\bin\lilypond-windows.exe
5. Make sure the "Include in automatic version selection" is checked and click OK, then click OK to leave the setting.
Then open the file and engrave it.

**Comment by uliska** [comment]
> The problem is in the file

This is correct but only addresses the *first* issue brought up here. I'm pretty sure using current LilyPond will make the score compile, producing a score and (if specified in the file) a MIDI file.

The traceback upon exporting to MusicXML shouldn't be related to that and looks like an issue within [python-ly](https://github.com/wbsoft/python-ly/issues) (whose MusicXML export is explicitly declared to be experimental). You should open an issue there.

The problem with sending the bug report from within Frescobaldi may actually be an environment-related bug. Please create a separate issue for this, giving more details about your set-up, for example the output of invoking `frescobaldi -V` (note the capital V).

**Comment by fedelibre** [comment]
@uliska IMO this issue should be closed.

The file compiles fine. The export to MusicXML works well, at least using latest python-ly and Frescobaldi 3.
