### ISSUE TITLE
[Frescobaldi 3.0.1] can not launch the program on Windows 10

### ISSUE THREAD

**Issue by jszhao** [wbsoft/frescobaldi#937]
Frescobaldi: 3.0.1 -- Python: 3.5.2 -- python-ly: 0.9.4 -- Qt: 5.8.0 -- PyQt: 5.8.1 -- sip: 4.19.1 -- poppler: 0.52.0 -- python-poppler-qt: 0.24.2 -- OS: Windows-10-10.0.14393 

After installation, the installer asks whether to launch Frescobaldi. I answer Yes, however, I don't see the interface after several minutes. And I also don't see the the program in task manager.

After that, I try to launch the program from the start menu. After several attempts, I see the interface of the program. All functions are OK. When closed, I have to try many times to launch it again. Each time, I can see frescobaldi.exe in the task manager, but it disappear immediately.

I try to double click on the program icon to launch it. The same.

I try to launch it from right button (I mean "Edit with Frescobaldi..."). The same.

I try to launch the program from CMD interface. The same.

I don't know what's the problem. That prevents me from using Frescobaldi 3. I don't meet this problem with Frescobaldi 2.

Best,
Jinsong

**Comment by fedelibre** [comment]
@jszhao How can you have Frescobaldi 3.0.1 in Windows if it was never released?

I installed it some times ago on Windows 7 and I can launch it without any problem.
However, I'm not a Windows user so I did not test it.

Compared to you, I have more recent versions of python and python-ly. Don't know if that may help.

```
Frescobaldi: 3.0.0
Python: 3.5.3
python-ly: 0.9.5
Qt: 5.8.0
PyQt: 5.8
sip: 4.19.1
poppler: 0.44.0
python-poppler-qt: 0.24.2
OS: Windows-7-6.1.7601-SP1
```

**Comment by fedelibre** [comment]
Did you install [Micorsoft Visual C++ 2015 (x86 package)](https://www.microsoft.com/en-us/download/details.aspx?id=48145)?

**Comment by jszhao** [comment]
@fedelibre The version info was extracted from the program I installed. It seems that the release was replaced by another newer one (I don't mean the version number, I mean the distribution package). And I think the problem has been fixed, although I don't know who fixed it, Frescobaldi or Windows 10.

Thanks for the attention on my issue.
