### ISSUE TITLE
Several issues with Frescobaldi

### ISSUE THREAD

**Issue by Alex1952** [wbsoft/frescobaldi#953]
Issue 1: When using too many grace notes Frescobaldi gives the following message when running the code:
"programming error: Going back in MIDI time."

Issue 2: Instruments with names longer than one short word get chopped off

Issue 3: If a bar contains 64-notes (e.g., 64 "a"s each of a 1/64 value) the bar runs off the page allowing only a view of about 2/3 of it.

**Comment by uliska** [comment]
All of these are LilyPond issues, but presumably no bugs.

Please refer to the lilypond-user mailing list, providing minimal but compilable examples.
