### ISSUE TITLE
Wish: Either command "rename file" or option to delete upon "save as"

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#980]
When I use the command "Save as..." I think in 50% of the cases the intention is to *rename* the file, while in the other half I want to make a *copy* from it.

It would be nice to have the option of renaming a file directly.
This could either be implemented as an additional command "rename" (with a dialog where I can either simply enter a new name to rename in the same directory or use Qt's "save as" dialog) or by providing an option in the existing "save as" dialog, e.g. a check box "rename (delete current file)".

Maybe these two functions could be merged with "save copy or selection as..." in *one* dialog?

@wbsoft Opinions?

**Comment by wyj1026** [comment]
I think this is very useful, could I take up this issue and make a pr?  : )

**Comment by uliska** [comment]
Of course, you're welcome.
Should be a task that is quite accessible for a first-time contribution.
