### ISSUE TITLE
Lilypond to MusicXML export

### ISSUE THREAD

**Issue by ashutoshsaboo** [wbsoft/frescobaldi#983]
Hi!
I was looking for an API to export .ly to musicxml format. I see Frescobaldi had a GSoC project related to the same. Is there a Python based API (preferably) which can help me? If there are APIs that can help me with this in some other language as well, it'd help me a lot!
Thanks! :smile:

**Comment by cguckes** [comment]
AFAIK this feature was present in a previous version of Frescobaldi. I would love to have that again!

**Comment by uliska** [comment]
Sorry, I originally forgot to comment on this.

There are different things here:

1)
Frescobaldi has an option File->Export->Export MusicXML.
This is very experimental and therefore has to be made available by checking the "experimental features" in Frescobaldi's Preferences.
This year's GSoC project is working on improving and extending this export

2)
The export is powered by the `python-ly` engine, a pure-Python library. This can be used independently from Frescobaldi, both as a command line script and a Python module (which seems to be what @ashutoshsaboo is looking for. Have a look at http://python-ly.readthedocs.io/en/latest/ to see if it helps you get started

**Comment by uliska** [comment]
Oh, I forgot that python-ly also has an HTTP server available (embarrassing, as I added it ...), but probably that's not useful here.

**Comment by cguckes** [comment]
Apparently one needs to restart Frescobaldi in order to show the experimental features. In my case, the export doesn't work.

```
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
    writer.parse_text(doc.toPlainText(), orgname)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 102, in parse_text
    self.parse_document(doc)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 119, in parse_document
    self.parse_tree(mustree)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 133, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 145, in parse_nodes
    func_call(m)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 587, in End
    self.mediator.change_tuplet_type(len(self.tuplet) - 1, "stop")
  File "/usr/lib/python3/dist-packages/ly/musicxml/ly2xml_mediator.py", line 596, in change_tuplet_type
    self.current_note.tuplet[index].ttype = newtype
IndexError: list index out of range
```

is this Frescobaldi related or do I need to contact the python-ly guys?

**Comment by uliska** [comment]
Well, "the guys" are basically the same, but you should open an issue on the python-ly tracker (https://github.com/wbsoft/python-ly/issues), givng the traceback and possibly a minimal example `ly` file.

**Comment by fedelibre** [comment]
I would close this issue, since it seems that the discussion moved to https://github.com/wbsoft/python-ly/issues/51
