### ISSUE TITLE
Please add Ctrl+= shortcut for Zoom-In

### ISSUE THREAD

**Issue by yurivict** [wbsoft/frescobaldi#990]
Browsers support it, so that users can use familiar shortcuts. Currently it's Ctrl+Shift+=

Chrome, for example, supports all combinations: Ctrl+-, Ctrl+=, Ctrl+Shift+-, Ctrl+Shift+=
IMO, it's best.

**Comment by uliska** [comment]
What exactly do you want to zoom, and from which working place?
You can zoom in and out of the music view and the manuscript view with configurable keyboard shortcuts:

![grafik](https://user-images.githubusercontent.com/1812148/29272479-88d739d8-8100-11e7-8263-3bbad6709ef0.png)

**Comment by uliska** [comment]
I assume my reply has made this obsolete. Feel free to reopen, but with further details, @yurivict .
