### ISSUE TITLE
VCS: widgets/differ.py file?

### ISSUE THREAD

**Issue by uliska** [wbsoft/frescobaldi#994]
Is it appropriate to have the file [`frescobaldi_app/widgets/differ.py`](https://github.com/wbsoft/frescobaldi/blob/rewrite-vcs/frescobaldi_app/widgets/differ.py)? Currently it "only" exports a *function* (`ori_highlight_diff`) and not a *widget*.

I see from `git grep "differ\."` that the file is only imported from the `vcsdiffwindow.py` file in `widgets`, so it may make sense to have the code in that directory. But OTOH in *that* case one could also directly copy the code into the other file.

If on the other hand this might be used in other places too (e.g. the diff view after doing convert-ly) the file should be moved somewhere else - so why not into the `vcs` directory.

**Comment by wenxin-bupt** [comment]
`differ.py` 's work is using two line lists to generate the HTML formatted diff contents.  In my plan, it will be used in the "popup discard window" and "partial stage window". `differ.py` is imported by two popup windows. I thought it belongs to `widgets/`.

`convert-ly`'s diff result display seems very powerful.  I'm not sure whether `differ.py` is compatible with it now. But it would be better if these windows share the same diff display. I agree with it that we should move `differ.py` into `vcs` directory.

**Comment by uliska** [comment]
OK, then please move the file as-is to the `vcs` module (should be trivial):

I've added https://github.com/wbsoft/frescobaldi/issues/995 to keep track of this later.
