### ISSUE TITLE
Can't open file 'musicxml2ly': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Kavanerd** [wbsoft/frescobaldi#997]
Hi there,

I am very new to this and so am not really sure whether this has been answered already. When I try to import a MusicXML file into Frescobaldi (I want to turn a score written in Sibelius into a Lilypond file to incorporate into a LaTeX document), I get the following error message.

The file couldn't be converted. Error message:
/System/Library/Frameworks/Python.framework/Versions/2.6/bin/python2.6: can't open file 'musicxml2ly': [Errno 2] No such file or directory

Could someone explain with some very simple step-by-step instructions (!) exactly what I need to do to fix this issue? I have included some screenshots in case this provides any help.

<img width="481" alt="screen shot 2017-08-18 at 12 40 15" src="https://user-images.githubusercontent.com/31131091/29457531-7af58918-8412-11e7-9ca2-0051c7d69744.png">

<img width="598" alt="screen shot 2017-08-18 at 12 40 24" src="https://user-images.githubusercontent.com/31131091/29457532-7af9f66a-8412-11e7-918e-ee30c7972249.png">

I am running on Mac OS Sierra (10.12.3).

Many thanks!

**Comment by tobik** [comment]
You have to select al LilyPond version in this dialog? 
If there is no LilyPond version available, do you have any LilyPond configured in Edit > Preferences > Lilypond Preferences > LilyPond versions to use?

**Comment by fedelibre** [comment]
@Kavanerd 
It seems you don't have any LilyPond installed. Have you entered the full path to your lilypond binary?

You should ask for support on [Frescobaldi mailing list](https://groups.google.com/forum/#!forum/frescobaldi).
