### ISSUE TITLE
No module named PyQt5.QtCore

### ISSUE THREAD

**Issue by bitwo** [wbsoft/frescobaldi#998]
~/frescobaldi-3.0.0$ python frescobaldi
Traceback (most recent call last):
  File "frescobaldi", line 7, in <module>
    import main
  File "/home/bb/frescobaldi-3.0.0/frescobaldi_app/main.py", line 33, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
ImportError: No module named PyQt5.QtCore
But
sudo apt-get install python3-pyqt5
...
»python3-pyqt5« ist bereits die neuste Version (5.5.1+dfsg-3ubuntu4).
python3-pyqt5 wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

**Comment by wenxin-bupt** [comment]
There is a lazy way: reinstall modules follow this wiki's guide.  [Running-Frescobaldi-3-From-Source-Git-(Linux)](https://github.com/wbsoft/frescobaldi/wiki/Running-Frescobaldi-3-From-Source-Git-(Linux))

And here are the  versions of my dependent modules:

Frescobaldi: 3.0.0
Python: 3.5.2
python-ly: 0.9.5
Qt: 5.5.1
PyQt: 5.5.1
sip: 4.17
poppler: 0.38.0
python-poppler-qt: 0.24.2
OS: Linux-4.8.0-39-generic-x86_64-with-Ubuntu-16.04-xenial
